"""Report-derived staleness invariants (the 2026-07-14 incident, #282).

The affected-rerun bot commits refreshed comparison reports
(``dashboard/public/data/<suite>.json``); the conformance scoreboard +
per-policy detail (``conformance/scoreboard.json``,
``conformance/detail/<jur>.json`` and their dashboard mirrors) are *derived*
from those reports. When the pre-fix bot refreshed the il/ky/oh/va income-tax
reports without regenerating the scoreboard, the committed detail went stale
and CI's ``conformance_scoreboard.py --check`` gate turned main red for every
open PR until someone regenerated by hand.

These tests pin the underlying invariant the fix relies on — a report refresh
makes the committed scoreboard stale (``--check`` fails), and regenerating
makes it pass again — plus a belt-and-braces check that this branch's
committed artifacts already match a fresh computation. The bot-path fix itself
(per-leg regeneration in ``scripts/commit_refreshed_report.sh``) has its own
behavioral suite in ``tests/test_commit_refreshed_report.py``.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parents[1]
SCRIPTS = REPO_ROOT / "scripts"


def _load_script(name: str):
    module_path = SCRIPTS / name
    spec = importlib.util.spec_from_file_location(name.replace(".py", ""), module_path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module

def _sandbox_scoreboard(tmp_path):
    """Load conformance_scoreboard.py with all its I/O redirected into tmp_path."""
    sb = _load_script("conformance_scoreboard.py")
    data = tmp_path / "dashboard" / "public" / "data"
    conf = tmp_path / "conformance"
    (conf / "detail").mkdir(parents=True)
    data.mkdir(parents=True)
    sb.REPO_ROOT = tmp_path
    sb.DASHBOARD_DATA_DIR = data
    sb.CONFORMANCE_DIR = conf
    sb.DETAIL_DIR = conf / "detail"
    sb.SCOREBOARD_PATH = conf / "scoreboard.json"
    sb.DASHBOARD_SCOREBOARD_PATH = data / "conformance_scoreboard.json"
    return sb, data, conf


def _minimal_universe_yaml() -> str:
    from axiom_oracles.conformance.loader import OracleIdentity, Universe, serialize
    from axiom_oracles.conformance.schema import UniversePolicy

    policy = UniversePolicy(
        id="tx:a",
        oracle_policy_name="a",
        output_vars=("a_s",),
        in_scope=True,
        suite="suite-a",
    )
    universe = Universe(
        jurisdiction="tx",
        oracle=OracleIdentity("M", "R", "S", "TX", "euromod"),
        policies=[policy],
    )
    return serialize(universe)


def _report(suite: str, *, comparisons: int, matches: int) -> dict:
    return {
        "suite": suite,
        "engines": {"left": "euromod", "right": "axiom"},
        "summary": {
            "comparison_count": comparisons,
            "match_count": matches,
            "mismatch_count": comparisons - matches,
        },
        "mismatches": [],
    }


def _run_check(sb, monkeypatch) -> int:
    monkeypatch.setattr(sys, "argv", ["conformance_scoreboard.py", "--check"])
    return sb.main()


def _regenerate(sb) -> None:
    """Exactly what the per-leg `conformance_scoreboard.py` regeneration does."""
    document, details = sb.build_scoreboard()
    sb.write_all(document, details)


def test_report_refresh_reds_the_scoreboard_until_regenerated(tmp_path, monkeypatch):
    """A committed report refresh leaves the scoreboard stale (``--check`` fails);
    regenerating — what the per-leg commit script does — makes it pass again. This is the
    2026-07-14 incident (#282) reproduced as an automated gate."""
    sb, data, conf = _sandbox_scoreboard(tmp_path)
    (conf / "tx.yaml").write_text(_minimal_universe_yaml())
    report_path = data / "suite-a.json"
    report_path.write_text(json.dumps(_report("suite-a", comparisons=5, matches=5)))

    # Freshly generated → the gate is green.
    _regenerate(sb)
    assert _run_check(sb, monkeypatch) == 0

    # Simulate the affected-rerun refreshing this report (its numbers move) WITHOUT
    # regenerating the scoreboard — the exact bot behavior that caused the incident.
    report_path.write_text(json.dumps(_report("suite-a", comparisons=5, matches=3)))
    assert _run_check(sb, monkeypatch) == 1, (
        "a refreshed report must make the committed scoreboard stale — if this "
        "no longer fails, the --check gate has stopped guarding staleness"
    )

    # Regenerate (the per-leg commit script) → green again, no human in the loop.
    _regenerate(sb)
    assert _run_check(sb, monkeypatch) == 0


def test_committed_scoreboard_is_consistent_with_committed_reports():
    """Belt-and-braces: the scoreboard/detail committed on this branch already
    match a fresh computation from the committed reports + universes. Mirrors the
    CI --check gate so a stale artifact is also caught by a local `pytest`."""
    sb = _load_script("conformance_scoreboard.py")
    document, details = sb.build_scoreboard()
    expected = sb._serialize(document)
    for path in (sb.SCOREBOARD_PATH, sb.DASHBOARD_SCOREBOARD_PATH):
        assert path.read_text() == expected, f"{path} is stale — regenerate it"
    for jurisdiction, scores in details.items():
        expected_detail = sb._serialize(sb._detail_document(jurisdiction, scores))
        for path in (
            sb.DETAIL_DIR / f"{jurisdiction}.json",
            sb.DASHBOARD_DATA_DIR / f"conformance_detail_{jurisdiction}.json",
        ):
            assert path.read_text() == expected_detail, f"{path} is stale"
