"""Regression guard for the affected-rerun → conformance-scoreboard staleness bug.

Background (2026-07-14 incident, fixed reactively in #282): the affected-rerun
bot commits refreshed comparison reports (``dashboard/public/data/<suite>.json``)
but the conformance scoreboard + per-policy detail
(``conformance/scoreboard.json``, ``conformance/detail/<jur>.json`` and their
dashboard mirrors) are *derived* from those reports. When the bot refreshed the
il/ky/oh/va income-tax reports without regenerating the scoreboard, the committed
detail went stale and CI's ``conformance_scoreboard.py --check`` gate turned main
red for every open PR until someone regenerated by hand.

The systemic fix is a post-matrix ``reconcile`` job in ``affected-rerun.yml`` that
regenerates the aggregates once, on the full refreshed report set, in the same
run. These tests pin BOTH halves of that fix:

* the workflow keeps a reconcile job that regenerates the scoreboard and pushes
  the ``conformance/`` aggregates (so the job can't be quietly dropped); and
* the underlying invariant it relies on — a report refresh makes the committed
  scoreboard stale (``--check`` fails), and regenerating makes it pass again.
"""

from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).parents[1]
SCRIPTS = REPO_ROOT / "scripts"
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "affected-rerun.yml"


def _load_script(name: str):
    module_path = SCRIPTS / name
    spec = importlib.util.spec_from_file_location(name.replace(".py", ""), module_path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def _workflow() -> dict:
    return yaml.safe_load(WORKFLOW.read_text())


def _reconcile_job() -> dict:
    jobs = _workflow()["jobs"]
    assert "reconcile" in jobs, (
        "affected-rerun.yml must keep a `reconcile` job that regenerates the "
        "conformance aggregates after refreshing reports — without it a report "
        "refresh reds main for every open PR (the 2026-07-14 incident, #282)."
    )
    return jobs["reconcile"]


# The report-derived generators the reconcile job must run in WRITE mode. These
# are exactly the artifacts behind ci.yml's report-derived --check gates:
#   - apply_dispositions.py     → dispositioned reports + euromod-be rollup
#   - check_vacuous_gate.py     → freshness.json
#   - conformance_scoreboard.py → scoreboard + per-policy detail (+ mirrors)
#   - conformance_burndown.py   → burn-down series
# (rule_verification / grids / compositions / universe / affected_map are NOT
# report-derived, so they are intentionally absent.)
REPORT_DERIVED_GENERATORS = (
    "apply_dispositions.py",
    "check_vacuous_gate.py",
    "conformance_scoreboard.py",
    "conformance_burndown.py",
)


# ---------------------------------------------------------------------------
# Workflow-lint: the reconcile job must exist and do the right things
#
# These assertions target INDIVIDUAL steps, and distinguish a WRITE-mode
# `scripts/foo.py` from a `scripts/foo.py --check`. Concatenating every step and
# substring-matching would let a `--check` in the verify step satisfy a
# "regenerates foo" assertion even if the write-mode regen were deleted — a
# vacuous test. We avoid that by scanning per line, per step.
# ---------------------------------------------------------------------------


def _run_scripts() -> list[str]:
    """The `run:` script of every step in the reconcile job."""
    return [step.get("run", "") for step in _reconcile_job()["steps"]]


def _push_step() -> str:
    """The reconcile step that commits + pushes the regenerated aggregates."""
    for run in _run_scripts():
        if "git push" in run:
            return run
    raise AssertionError("reconcile has no step that pushes the reconciled aggregates")


def _verify_step() -> str:
    """A reconcile step that self-verifies with --check but does not push."""
    for run in _run_scripts():
        if "--check" in run and "git push" not in run:
            return run
    return ""


def _invokes_write(run: str, generator: str) -> bool:
    """True iff `run` invokes `scripts/<generator>` in WRITE mode (no --check)."""
    needle = f"scripts/{generator}"
    for raw in run.splitlines():
        line = raw.strip()
        if line.startswith("#") or needle not in line:
            continue
        if "--check" not in line:
            return True
    return False


def test_reconcile_job_runs_after_the_rerun_matrix():
    rec = _reconcile_job()
    needs = rec["needs"]
    needs = [needs] if isinstance(needs, str) else needs
    assert "rerun" in needs, (
        "reconcile must run AFTER the rerun matrix so it sees every refreshed "
        "report; regenerating inside a matrix leg only ever sees a partial view."
    )


def test_reconcile_job_can_push():
    rec = _reconcile_job()
    assert rec.get("permissions", {}).get("contents") == "write", (
        "reconcile commits the regenerated aggregates, so it needs contents:write."
    )


def test_reconcile_commits_and_pushes_conformance():
    push = _push_step()
    assert "git commit" in push and "conformance/" in push, (
        "reconcile must commit the regenerated conformance/ aggregates."
    )
    assert "git push" in push, "reconcile must push the reconciled aggregates."


def test_reconcile_runs_even_when_some_matrix_legs_fail():
    # rerun is a fail-fast:false matrix, so one failed leg fails the whole job;
    # the legs that succeeded still pushed reports that need reconciling.
    guard = _reconcile_job()["if"]
    assert "always()" in guard, (
        "reconcile must use always() so a partially-failed matrix still gets "
        "its landed reports reconciled."
    )
    assert "needs.select.result == 'success'" in guard, (
        "reconcile must still gate on select succeeding (nothing to reconcile "
        "if selection itself failed)."
    )


def test_reconcile_self_verifies_with_check_after_pushing():
    verify = _verify_step()
    assert "scripts/conformance_scoreboard.py --check" in verify, (
        "reconcile should re-run the --check gate in a distinct verify step so a "
        "botched reconcile fails loudly here instead of leaving main red. (A "
        "GITHUB_TOKEN push does not retrigger main CI, so this is the only gate "
        "on what reconcile pushes.)"
    )


def test_reconcile_regenerates_every_report_derived_aggregate_in_write_mode():
    # The push step must invoke each generator in WRITE mode — a --check alone
    # (e.g. in the consistency guard or the verify step) does not regenerate.
    push = _push_step()
    for generator in REPORT_DERIVED_GENERATORS:
        assert _invokes_write(push, generator), (
            f"reconcile must run {generator} in write mode before committing — it "
            "produces a committed artifact CI derives from the refreshed reports."
        )

    # Producer before consumers: apply_dispositions REWRITES the reports that
    # freshness and the scoreboard then read. Regenerating a consumer first
    # would compute it from pre-disposition report bytes; the post-regen gate
    # would refuse to push, but the job would fail every run instead of
    # reconciling. Pin the write-mode order.
    def _write_idx(generator: str) -> int:
        needle = f"scripts/{generator}"
        for i, ln in enumerate(push.splitlines()):
            line = ln.strip()
            if (
                not line.startswith("#")
                and needle in line
                and "--check" not in line
            ):
                return i
        raise AssertionError(f"no write-mode invocation of {generator}")

    producer = _write_idx("apply_dispositions.py")
    for consumer in ("check_vacuous_gate.py", "conformance_scoreboard.py"):
        assert producer < _write_idx(consumer), (
            "apply_dispositions.py must regenerate the reports BEFORE "
            f"{consumer} reads them — reversed order computes the aggregate "
            "from pre-disposition bytes."
        )


def test_reconcile_validates_the_regenerated_tree_before_pushing():
    # The push step must gate on the real CI checks twice: skip when the
    # committed aggregates already pass, and — after regenerating — refuse to
    # push a tree that STILL fails them. A gate failure regeneration can't fix
    # (e.g. a config-schema error) is not derivation lag; pushing would add a
    # noise commit on a main that stays red for the same reason.
    push = _push_step()
    lines = push.splitlines()
    assert "if report_derived_gates" in push, (
        "reconcile must skip the commit when the committed aggregates already "
        "pass the report-derived gates."
    )

    # Ordering, per line: LAST write-mode generator < post-regen gate < commit.
    # (Substring order on the whole script would accept the guard being moved
    # above the generators, where it validates the wrong tree.)
    write_idxs = [
        i
        for i, ln in enumerate(lines)
        if ln.strip().startswith("uv run scripts/") and "--check" not in ln
    ]
    assert write_idxs, "push step lost its write-mode generator invocations"
    guard_idxs = [i for i, ln in enumerate(lines) if "! report_derived_gates" in ln]
    assert guard_idxs, (
        "reconcile must re-run the report-derived gates on the regenerated tree "
        "and refuse to push if they still fail (non-staleness failure)."
    )
    guard_idx = guard_idxs[-1]
    commit_idxs = [i for i, ln in enumerate(lines) if "git commit" in ln]
    assert commit_idxs, "push step lost its git commit"
    assert max(write_idxs) < guard_idx < min(commit_idxs), (
        "the post-regeneration validation must run AFTER every write-mode "
        "generator and BEFORE the commit/push — anywhere else it validates the "
        "wrong tree."
    )

    # Refusal: the guard's block must actually abort — a standalone `exit 1`
    # line (a substring match would accept dead text like `true || exit 1`).
    fi_idx = next(
        (i for i in range(guard_idx + 1, len(lines)) if lines[i].strip() == "fi"),
        None,
    )
    assert fi_idx is not None, "post-regen validation guard has no closing fi"
    assert any(
        ln.strip() == "exit 1" for ln in lines[guard_idx : fi_idx + 1]
    ), (
        "the post-regen validation must exit 1 when the regenerated tree still "
        "fails the gates — otherwise a non-staleness failure gets pushed anyway."
    )
    # The textual pins above are best-effort; the executable proof of this
    # behavior is test_push_step_behaves (which runs the real script).


# ---------------------------------------------------------------------------
# Behavioral: execute the REAL push-step script with uv/git stubbed
#
# Textual pins can be gamed by creative shell (`true || exit 1` contains the
# substring but never exits). Running the actual script under bash -e — the
# same interpreter GitHub Actions uses — is the sound version: whatever the
# text says, these tests observe what gets committed and pushed.
# ---------------------------------------------------------------------------


def _run_push_step(tmp_path, *, stale_gates: tuple, gates_fixable: bool):
    """Execute the reconcile push step under bash -e with uv/git stubbed.

    Each generator gets its own staleness marker, mirroring reality (a stale
    scoreboard is independent of a stale freshness registry): the uv stub fails
    ``scripts/<name>.py --check`` while ``$STATE/stale-<name>`` exists, and a
    write-mode invocation of that same script removes its own marker iff
    ``gates_fixable`` — i.e. the failure was derivation lag regeneration can
    fix, as opposed to e.g. a config-schema error it cannot. --check is matched
    as an exact argument word. The git stub logs every argv and succeeds.
    Returns (exit_code, [first git argv tokens]).
    """
    script = _push_step().replace(
        "${{ github.event.repository.default_branch }}", "main"
    )
    state = tmp_path / "state"
    state.mkdir()
    for gate in stale_gates:
        (state / f"stale-{gate.removesuffix('.py')}").touch()
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    # Strict stub: --check must be an exact argument word, the script path must
    # be a canonical scripts/<name>.py (no nested dirs), and <name> must be one
    # of the known generators — anything else exits 127, like a real missing
    # file would, so a typo'd or refactored-away path cannot pass silently.
    (bin_dir / "uv").write_text(
        "#!/bin/bash\n"
        'mode=write; name=""\n'
        'for a in "$@"; do\n'
        '  [ "$a" = "--check" ] && mode=check\n'
        '  case "$a" in\n'
        '    scripts/*/*) echo "stub uv: nested path $a" >&2; exit 127 ;;\n'
        '    scripts/*.py) name="${a##*/}"; name="${name%.py}" ;;\n'
        "  esac\n"
        "done\n"
        'case " $GATE_LIST " in\n'
        '  *" $name "*) ;;\n'
        '  *) echo "stub uv: unknown script $name" >&2; exit 127 ;;\n'
        "esac\n"
        'if [ "$mode" = check ]; then\n'
        '  [ ! -e "$STATE/stale-$name" ]\n'
        'elif [ "$GATES_FIXABLE" = 1 ]; then\n'
        '  rm -f "$STATE/stale-$name"\n'
        "fi\n"
    )
    (bin_dir / "git").write_text(
        '#!/bin/bash\necho "$*" >> "$STATE/git.log"\nexit 0\n'
    )
    (bin_dir / "sleep").write_text("#!/bin/bash\nexit 0\n")
    for stub in bin_dir.iterdir():
        stub.chmod(0o755)
    script_file = tmp_path / "push_step.sh"
    script_file.write_text(script)

    env = dict(os.environ)
    env["PATH"] = f"{bin_dir}:{env['PATH']}"
    env["STATE"] = str(state)
    env["GATES_FIXABLE"] = "1" if gates_fixable else "0"
    env["GATE_LIST"] = " ".join(GATE_NAMES)  # late-bound module global
    proc = subprocess.run(
        ["bash", "-e", str(script_file)],
        env=env,
        cwd=tmp_path,
        capture_output=True,
        text=True,
        timeout=60,
    )
    log_path = state / "git.log"
    git_ops = (
        [line.split()[0] for line in log_path.read_text().splitlines() if line]
        if log_path.exists()
        else []
    )
    return proc.returncode, git_ops


GATE_NAMES = tuple(g.removesuffix(".py") for g in REPORT_DERIVED_GENERATORS)


def test_push_step_skips_when_aggregates_already_consistent(tmp_path):
    code, git_ops = _run_push_step(tmp_path, stale_gates=(), gates_fixable=True)
    assert code == 0
    assert "commit" not in git_ops and "push" not in git_ops, (
        "nothing was stale — the step must not churn a commit"
    )


def test_push_step_commits_and_pushes_when_regeneration_fixes_the_gates(tmp_path):
    code, git_ops = _run_push_step(
        tmp_path, stale_gates=GATE_NAMES, gates_fixable=True
    )
    assert code == 0
    assert "commit" in git_ops and "push" in git_ops, (
        "derivation lag regeneration fixed must be committed and pushed — this "
        "is the whole point of the reconcile job (#282)"
    )
    assert git_ops.index("commit") < git_ops.index("push")


@pytest.mark.parametrize("gate", GATE_NAMES)
def test_push_step_reconciles_when_only_one_aggregate_is_stale(tmp_path, gate):
    # Each gate must individually participate in the consistency guard: with
    # only THIS aggregate stale, the step must still regenerate and push. This
    # fails if a gate is dropped from the guard chain, and — because `if fn`
    # suppresses errexit inside the function, leaving only the LAST command's
    # status — also fails if the && chain decays into separate statements.
    code, git_ops = _run_push_step(tmp_path, stale_gates=(gate,), gates_fixable=True)
    assert code == 0
    assert "commit" in git_ops and "push" in git_ops, (
        f"a stale {gate} artifact alone must trigger the reconcile — if it "
        "doesn't, that gate has fallen out of the guard and main stays red"
    )


def test_push_step_refuses_to_push_when_gates_still_fail_after_regen(tmp_path):
    # A gate failure regeneration cannot fix (e.g. a config-schema error) is
    # not derivation lag: the step must fail WITHOUT committing or pushing a
    # noise commit onto a main that stays red for the same reason.
    code, git_ops = _run_push_step(
        tmp_path, stale_gates=GATE_NAMES, gates_fixable=False
    )
    assert code != 0, "a non-staleness gate failure must fail the step loudly"
    assert "commit" not in git_ops and "push" not in git_ops, (
        "a tree that still fails the gates must never be committed or pushed"
    )


def test_push_step_refuses_when_a_single_gate_failure_is_not_fixable(tmp_path):
    code, git_ops = _run_push_step(
        tmp_path, stale_gates=("check_vacuous_gate",), gates_fixable=False
    )
    assert code != 0
    assert "commit" not in git_ops and "push" not in git_ops


# ---------------------------------------------------------------------------
# Behavioral: the incident, reproduced as a gate
# ---------------------------------------------------------------------------


def _sandbox_scoreboard(tmp_path):
    """Load conformance_scoreboard.py with all its I/O redirected into tmp_path."""
    sb = _load_script("conformance_scoreboard.py")
    data = tmp_path / "dashboard" / "public" / "data"
    conf = tmp_path / "conformance"
    (conf / "detail").mkdir(parents=True)
    data.mkdir(parents=True)
    sb.REPO_ROOT = tmp_path
    sb.DASHBOARD_DATA_DIR = data
    sb.CONFORMANCE_DIR = conf
    sb.DETAIL_DIR = conf / "detail"
    sb.SCOREBOARD_PATH = conf / "scoreboard.json"
    sb.DASHBOARD_SCOREBOARD_PATH = data / "conformance_scoreboard.json"
    return sb, data, conf


def _minimal_universe_yaml() -> str:
    from axiom_oracles.conformance.loader import OracleIdentity, Universe, serialize
    from axiom_oracles.conformance.schema import UniversePolicy

    policy = UniversePolicy(
        id="tx:a",
        oracle_policy_name="a",
        output_vars=("a_s",),
        in_scope=True,
        suite="suite-a",
    )
    universe = Universe(
        jurisdiction="tx",
        oracle=OracleIdentity("M", "R", "S", "TX", "euromod"),
        policies=[policy],
    )
    return serialize(universe)


def _report(suite: str, *, comparisons: int, matches: int) -> dict:
    return {
        "suite": suite,
        "engines": {"left": "euromod", "right": "axiom"},
        "summary": {
            "comparison_count": comparisons,
            "match_count": matches,
            "mismatch_count": comparisons - matches,
        },
        "mismatches": [],
    }


def _run_check(sb, monkeypatch) -> int:
    monkeypatch.setattr(sys, "argv", ["conformance_scoreboard.py", "--check"])
    return sb.main()


def _regenerate(sb) -> None:
    """Exactly what the reconcile job's `conformance_scoreboard.py` run does."""
    document, details = sb.build_scoreboard()
    sb.write_all(document, details)


def test_report_refresh_reds_the_scoreboard_until_regenerated(tmp_path, monkeypatch):
    """A committed report refresh leaves the scoreboard stale (``--check`` fails);
    regenerating — what the reconcile job does — makes it pass again. This is the
    2026-07-14 incident (#282) reproduced as an automated gate."""
    sb, data, conf = _sandbox_scoreboard(tmp_path)
    (conf / "tx.yaml").write_text(_minimal_universe_yaml())
    report_path = data / "suite-a.json"
    report_path.write_text(json.dumps(_report("suite-a", comparisons=5, matches=5)))

    # Freshly generated → the gate is green.
    _regenerate(sb)
    assert _run_check(sb, monkeypatch) == 0

    # Simulate the affected-rerun refreshing this report (its numbers move) WITHOUT
    # regenerating the scoreboard — the exact bot behavior that caused the incident.
    report_path.write_text(json.dumps(_report("suite-a", comparisons=5, matches=3)))
    assert _run_check(sb, monkeypatch) == 1, (
        "a refreshed report must make the committed scoreboard stale — if this "
        "no longer fails, the --check gate has stopped guarding staleness"
    )

    # Regenerate (the reconcile job) → green again, no human in the loop.
    _regenerate(sb)
    assert _run_check(sb, monkeypatch) == 0


def test_committed_scoreboard_is_consistent_with_committed_reports():
    """Belt-and-braces: the scoreboard/detail committed on this branch already
    match a fresh computation from the committed reports + universes. Mirrors the
    CI --check gate so a stale artifact is also caught by a local `pytest`."""
    sb = _load_script("conformance_scoreboard.py")
    document, details = sb.build_scoreboard()
    expected = sb._serialize(document)
    for path in (sb.SCOREBOARD_PATH, sb.DASHBOARD_SCOREBOARD_PATH):
        assert path.read_text() == expected, f"{path} is stale — regenerate it"
    for jurisdiction, scores in details.items():
        expected_detail = sb._serialize(sb._detail_document(jurisdiction, scores))
        for path in (
            sb.DETAIL_DIR / f"{jurisdiction}.json",
            sb.DASHBOARD_DATA_DIR / f"conformance_detail_{jurisdiction}.json",
        ):
            assert path.read_text() == expected_detail, f"{path} is stale"
