"use client";

/**
 * Per-jurisdiction conformance card.
 *
 * Answers one question against an exact predicate: is Axiom in full parity with
 * the oracle for this jurisdiction? Full parity ("CONFORMANT") means every policy
 * the oracle simulates is either covered by an Axiom suite that matches, or
 * excluded for a declared reason — with zero unexplained mismatches and zero
 * open Axiom-attributed gaps.
 *
 * Layout follows the taxsim-dashboard model: a headline with the CONFORMANT
 * badge and dual/triple rates side by side, then one dimensional breakdown — a
 * per-policy table (policy, suite, cases, raw, explained, status). A small
 * burn-down of the committed dated snapshots shows the gap closing over time.
 *
 * Data: /data/conformance_scoreboard.json (headline + predicate),
 * /data/conformance_detail_<jur>.json (per-policy rows),
 * /data/conformance_burndown.json (dated series). All generated by
 * scripts/conformance_scoreboard.py + scripts/conformance_burndown.py.
 */

import { useEffect, useState } from "react";
import {
  IconCircleCheck,
  IconAlertTriangle,
  IconArrowUpRight,
} from "@tabler/icons-react";

function pct(value) {
  if (value == null) return "—";
  return `${Number(value).toFixed(value >= 99.95 || value === 0 ? 0 : 1)}%`;
}

/** Small inline burn-down: coverage line rising, gap line falling. */
function BurnDown({ series }) {
  if (!series || series.length === 0) return null;
  const W = 260;
  const H = 64;
  const pad = 6;
  const maxScope = Math.max(...series.map((p) => p.in_scope), 1);
  const n = series.length;
  const x = (i) => (n === 1 ? W / 2 : pad + (i * (W - 2 * pad)) / (n - 1));
  const y = (v) => H - pad - (v / maxScope) * (H - 2 * pad);
  const line = (key) =>
    series.map((p, i) => `${i === 0 ? "M" : "L"}${x(i)},${y(p[key])}`).join(" ");

  const single = n === 1;
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
      <svg
        width={W}
        height={H}
        viewBox={`0 0 ${W} ${H}`}
        role="img"
        aria-label="Coverage and gap over time"
        style={{ maxWidth: "100%" }}
      >
        {!single && (
          <>
            <path d={line("covered")} fill="none" stroke="var(--good)" strokeWidth="2" />
            <path
              d={line("gap")}
              fill="none"
              stroke="var(--bad)"
              strokeWidth="2"
              strokeDasharray="3 3"
            />
          </>
        )}
        {series.map((p, i) => (
          <g key={p.date}>
            <circle cx={x(i)} cy={y(p.covered)} r="2.5" fill="var(--good)" />
            <circle cx={x(i)} cy={y(p.gap)} r="2.5" fill="var(--bad)" />
          </g>
        ))}
      </svg>
      <div
        className="mono"
        style={{
          display: "flex",
          gap: 12,
          fontSize: 10,
          color: "var(--ink-mute)",
        }}
      >
        <span style={{ color: "var(--good)" }}>● covered</span>
        <span style={{ color: "var(--bad)" }}>● gap to parity</span>
        <span>
          {series[0].date}
          {n > 1 ? ` → ${series[n - 1].date}` : " (history begins today)"}
        </span>
      </div>
    </div>
  );
}

function Metric({ label, value, tone }) {
  const color =
    tone === "good"
      ? "var(--good)"
      : tone === "bad"
        ? "var(--bad)"
        : "var(--ink)";
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
      <span
        className="mono"
        style={{
          fontSize: 11,
          textTransform: "uppercase",
          letterSpacing: "0.04em",
          color: "var(--ink-mute)",
        }}
      >
        {label}
      </span>
      <span style={{ fontSize: 22, fontWeight: 600, color }}>{value}</span>
    </div>
  );
}

function StatusPill({ status }) {
  const map = {
    conformant: ["badge badge-good", "conformant"],
    uncovered: ["badge badge-warn", "no suite yet"],
    unexplained: ["badge badge-bad", "unexplained"],
    "axiom-gap": ["badge badge-bad", "axiom gap"],
  };
  if (status && status.startsWith("excluded")) {
    const reason = status.split(":")[1] || "excluded";
    return <span className="badge">excluded · {reason.replace(/_/g, " ")}</span>;
  }
  const [cls, label] = map[status] || ["badge", status || "—"];
  return <span className={cls}>{label}</span>;
}

const cellHead = {
  textAlign: "left",
  padding: "8px 12px",
  fontSize: 11,
  textTransform: "uppercase",
  letterSpacing: "0.04em",
  color: "var(--ink-mute)",
  fontWeight: 600,
};
const cell = { padding: "8px 12px", verticalAlign: "top", fontSize: 13 };

export default function ConformanceCard({ region }) {
  const [scoreboard, setScoreboard] = useState(null);
  const [detail, setDetail] = useState(null);
  const [burndown, setBurndown] = useState(null);

  useEffect(() => {
    let alive = true;
    Promise.all([
      fetch("/data/conformance_scoreboard.json").then((r) => (r.ok ? r.json() : null)),
      fetch(`/data/conformance_detail_${region}.json`).then((r) =>
        r.ok ? r.json() : null,
      ),
      fetch("/data/conformance_burndown.json").then((r) => (r.ok ? r.json() : null)),
    ])
      .then(([s, d, b]) => {
        if (!alive) return;
        setScoreboard(s);
        setDetail(d);
        setBurndown(b);
      })
      .catch(() => {});
    return () => {
      alive = false;
    };
  }, [region]);

  if (!scoreboard) return null;
  const summary = (scoreboard.jurisdictions || []).find(
    (j) => j.jurisdiction === region,
  );
  if (!summary) return null;

  const conformant = summary.conformant;
  const series = burndown?.series?.[region] || [];
  const excl = summary.excluded_by_reason || {};

  // In-scope rows first (covered then uncovered), then excluded rows — the
  // dimensional breakdown table.
  const rows = (detail?.policies || [])
    .slice()
    .sort((a, b) => {
      const rank = (r) =>
        !r.in_scope ? 3 : r.status === "conformant" ? 0 : r.covered ? 1 : 2;
      if (rank(a) !== rank(b)) return rank(a) - rank(b);
      return a.oracle_policy_name.localeCompare(b.oracle_policy_name);
    });

  return (
    <section style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <div className="section-eyebrow">Oracle conformance</div>

      {/* Headline + predicate badge */}
      <div
        style={{
          border: `1px solid ${conformant ? "var(--good)" : "var(--hairline)"}`,
          background: conformant ? "var(--good-bg)" : "var(--paper-elevated)",
          borderRadius: 12,
          padding: "16px 18px",
          display: "flex",
          flexDirection: "column",
          gap: 14,
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-start",
            gap: 16,
            flexWrap: "wrap",
          }}
        >
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              {conformant ? (
                <IconCircleCheck size={20} color="var(--good)" />
              ) : (
                <IconAlertTriangle size={20} color="var(--bad)" />
              )}
              <span style={{ fontSize: 16, fontWeight: 700 }}>
                {conformant ? "CONFORMANT" : "Not yet conformant"}
              </span>
            </div>
            <p
              className="mono"
              style={{ fontSize: 12, color: "var(--ink-mute)", margin: "4px 0 0" }}
            >
              vs {summary.oracle}
            </p>
          </div>
          <div style={{ display: "flex", gap: 24, flexWrap: "wrap" }}>
            <Metric
              label="Covered"
              value={`${summary.covered}/${summary.policies_in_scope}`}
              tone={
                summary.covered === summary.policies_in_scope ? "good" : undefined
              }
            />
            <Metric
              label="Coverage"
              value={pct(summary.covered_pct)}
            />
            <Metric
              label="Unexplained"
              value={summary.unexplained_total}
              tone={summary.unexplained_total === 0 ? "good" : "bad"}
            />
            <Metric
              label="Axiom-attributed open"
              value={summary.axiom_attributed_open}
              tone={summary.axiom_attributed_open === 0 ? "good" : "bad"}
            />
          </div>
        </div>

        <p style={{ fontSize: 13, color: "var(--ink-mute)", margin: 0 }}>
          Full parity means every one of the {summary.policies_in_scope} in-scope
          policies is covered by a matching suite, with no unexplained mismatch and
          no open Axiom-attributed gap.{" "}
          {summary.oracle_attributed > 0 && (
            <>
              {summary.oracle_attributed} residual difference
              {summary.oracle_attributed === 1 ? " is" : "s are"} attributed to the
              oracle (upstream engine gaps), not Axiom.
            </>
          )}
        </p>

        {!conformant && summary.blocking_reasons?.length > 0 && (
          <ul
            style={{
              margin: 0,
              paddingLeft: 18,
              fontSize: 13,
              color: "var(--ink-soft)",
            }}
          >
            {summary.blocking_reasons.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        )}

        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-end",
            gap: 16,
            flexWrap: "wrap",
          }}
        >
          <div
            className="mono"
            style={{ fontSize: 12, color: "var(--ink-mute)" }}
          >
            {summary.excluded} excluded with a declared reason
            {Object.keys(excl).length > 0 && (
              <>
                {" · "}
                {Object.entries(excl)
                  .map(([k, v]) => `${k.replace(/_/g, " ")}: ${v}`)
                  .join(" · ")}
              </>
            )}
          </div>
          <BurnDown series={series} />
        </div>
      </div>

      {/* Per-policy dimensional breakdown */}
      {rows.length > 0 && (
        <div
          style={{
            border: "1px solid var(--hairline)",
            borderRadius: 10,
            overflowX: "auto",
          }}
        >
          <table
            style={{ width: "100%", borderCollapse: "collapse", minWidth: 640 }}
          >
            <thead>
              <tr style={{ background: "var(--paper-elevated)" }}>
                <th style={cellHead}>Oracle policy</th>
                <th style={cellHead}>Suite</th>
                <th style={cellHead}>Cases</th>
                <th style={cellHead}>Raw</th>
                <th style={cellHead}>Explained</th>
                <th style={cellHead}>Status</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => (
                <tr
                  key={r.id}
                  style={{
                    borderTop: "1px solid var(--hairline)",
                    opacity: r.in_scope ? 1 : 0.6,
                  }}
                >
                  <td style={cell}>
                    <span className="mono">{r.oracle_policy_name}</span>
                    {r.note && (
                      <span
                        title={r.note}
                        style={{ color: "var(--ink-mute)", cursor: "help" }}
                      >
                        {" "}ⓘ
                      </span>
                    )}
                  </td>
                  <td style={cell}>
                    <span className="mono" style={{ fontSize: 12 }}>
                      {r.suite || (r.in_scope ? "— (unassigned)" : "—")}
                    </span>
                  </td>
                  <td style={cell}>
                    {r.covered ? (
                      <span className="mono" style={{ fontSize: 12 }}>
                        {r.matches}/{r.comparisons}
                      </span>
                    ) : (
                      "—"
                    )}
                  </td>
                  <td style={cell}>
                    {r.covered ? (
                      <span style={{ color: "var(--ink-soft)" }}>
                        {pct(r.raw_match_rate)}
                      </span>
                    ) : (
                      "—"
                    )}
                  </td>
                  <td style={cell}>
                    {r.covered && r.explained_rate != null ? (
                      <span
                        style={{
                          color:
                            r.explained_rate >= 99.95
                              ? "var(--good)"
                              : "var(--ink-soft)",
                        }}
                      >
                        {pct(r.explained_rate)}
                      </span>
                    ) : r.covered ? (
                      pct(r.raw_match_rate)
                    ) : (
                      "—"
                    )}
                  </td>
                  <td style={cell}>
                    <StatusPill status={r.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <a
        href="https://github.com/TheAxiomFoundation/axiom-oracles/blob/main/conformance/README.md"
        target="_blank"
        rel="noreferrer"
        className="cite"
        style={{ display: "inline-flex", alignItems: "center", gap: 4, fontSize: 12 }}
      >
        How conformance is defined <IconArrowUpRight size={13} />
      </a>
    </section>
  );
}
