"use client";

import { suiteMeta, suiteLabel } from "../utils/suites";

/**
 * Per-suite report freshness (O2/O3). Each row shows how old a suite's report
 * is (from its provenance timestamp), which rulespec repos it is affected by,
 * and a stale badge when the report has aged past the freshness window. A
 * separate alarm strip surfaces executable coverage surfaces whose report is
 * missing or stale — the non-blocking half of the vacuous-verification gate
 * (the blocking half is the CI schema check).
 *
 * Data comes from dashboard/public/data/freshness.json (generated by
 * scripts/check_vacuous_gate.py), which stores only TIME-INVARIANT facts —
 * report timestamps, affected repos, the SHAs each ran against, and the
 * executable surfaces. Age and staleness are computed HERE, at render time,
 * against the current clock — so the committed data file never goes stale on
 * its own.
 */

function ageDays(generatedAt) {
  if (!generatedAt) return null;
  const when = Date.parse(generatedAt);
  if (Number.isNaN(when)) return null;
  return (Date.now() - when) / 86400000;
}

function ageLabel(days, unstamped) {
  if (unstamped || days == null) return "not yet stamped";
  if (days < 1) return "today";
  if (days < 2) return "1 day ago";
  return `${Math.round(days)} days ago`;
}

function FreshnessBadge({ days, unstamped, maxAge }) {
  if (unstamped || days == null) {
    return <span className="badge badge-warn">needs provenance</span>;
  }
  if (days > maxAge) {
    return <span className="badge badge-bad">stale &gt; {maxAge}d</span>;
  }
  return <span className="badge badge-good">fresh</span>;
}

function RepoChips({ repos, ranAgainst }) {
  if (!repos || repos.length === 0) {
    return <span className="mono" style={{ color: "var(--ink-mute)" }}>—</span>;
  }
  return (
    <span style={{ display: "inline-flex", flexWrap: "wrap", gap: 4 }}>
      {repos.map((repo) => {
        const short = repo.split("/").pop();
        const sha = ranAgainst?.[repo];
        return (
          <span
            key={repo}
            className="mono"
            title={sha ? `ran against ${sha}` : "ran against unknown SHA"}
            style={{
              fontSize: 11,
              padding: "1px 6px",
              borderRadius: 5,
              border: "1px solid var(--hairline)",
              color: sha ? "var(--ink-soft)" : "var(--warn)",
            }}
          >
            {short}
            {sha ? ` @${String(sha).slice(0, 7)}` : " @?"}
          </span>
        );
      })}
    </span>
  );
}

/** Derive freshness alarms from executable surfaces + current report ages. */
function computeAlarms(freshness, bySuite, maxAge) {
  const alarms = [];
  for (const surface of freshness.executable_surfaces || []) {
    const { program, jurisdiction, suites = [] } = surface;
    if (suites.length === 0) {
      alarms.push({
        program,
        jurisdiction,
        message: `${program} (${jurisdiction}) is marked executable but has no committed comparison report`,
      });
      continue;
    }
    for (const suite of suites) {
      const entry = bySuite[suite];
      if (!entry || entry.unstamped) continue; // unstamped shown per-row, not as alarm
      const days = ageDays(entry.generated_at);
      if (days != null && days > maxAge) {
        alarms.push({
          program,
          jurisdiction,
          suite,
          message: `${program} (${jurisdiction}) report ${suite} is ${Math.round(days)} days old (> ${maxAge})`,
        });
      }
    }
  }
  return alarms;
}

export default function FreshnessRegister({ freshness, region }) {
  if (!freshness || !Array.isArray(freshness.suites)) return null;

  const maxAge = freshness.max_age_days || 14;
  const bySuite = Object.fromEntries(
    freshness.suites.map((s) => [s.suite, s]),
  );

  // Only show suites for the active region so the register tracks the country
  // toggle like every other section.
  const rows = freshness.suites
    .filter((s) => (region ? suiteMeta(s.suite).region === region : true))
    .map((s) => ({ ...s, days: ageDays(s.generated_at) }))
    .sort((a, b) => {
      // Attention-first: stale, then unstamped, then by age descending.
      const rank = (s) =>
        s.unstamped ? 1 : s.days != null && s.days > maxAge ? 0 : 2;
      if (rank(a) !== rank(b)) return rank(a) - rank(b);
      return (b.days || 0) - (a.days || 0);
    });

  if (rows.length === 0) return null;

  const alarms = computeAlarms(freshness, bySuite, maxAge).filter((a) => {
    if (!region) return true;
    if (a.suite) return suiteMeta(a.suite).region === region;
    const j = String(a.jurisdiction || "").toLowerCase();
    if (j === "uk") return region === "uk";
    if (j === "be") return region === "be";
    return region === "us";
  });

  const staleCount = rows.filter(
    (r) => !r.unstamped && r.days != null && r.days > maxAge,
  ).length;

  return (
    <section style={{ display: "flex", flexDirection: "column", gap: 10 }}>
      <div className="section-eyebrow">Report freshness</div>
      <p style={{ fontSize: 13, color: "var(--ink-mute)", margin: 0 }}>
        How current each verification report is, versus the rulespec repos it
        depends on. Reports refresh automatically when their rules change (every
        6 hours), with a weekly full rerun as backstop.
        {staleCount > 0 && (
          <> <strong>{staleCount}</strong> report{staleCount === 1 ? "" : "s"} past
          the {maxAge}-day window.</>
        )}
      </p>

      {alarms.length > 0 && (
        <div
          style={{
            border: "1px solid var(--bad, #b91c1c)",
            background: "var(--bad-bg, #fef2f2)",
            borderRadius: 10,
            padding: "10px 14px",
            display: "flex",
            flexDirection: "column",
            gap: 6,
          }}
        >
          <span
            className="mono"
            style={{ fontSize: 12, fontWeight: 600, color: "var(--bad)" }}
          >
            {alarms.length} coverage freshness alarm{alarms.length === 1 ? "" : "s"}
          </span>
          {alarms.map((a) => (
            <span
              key={`${a.program}-${a.jurisdiction}-${a.suite ?? "none"}`}
              style={{ fontSize: 13 }}
            >
              {a.message}
            </span>
          ))}
        </div>
      )}

      <div
        style={{
          border: "1px solid var(--hairline)",
          borderRadius: 10,
          overflow: "hidden",
        }}
      >
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
          <thead>
            <tr style={{ background: "var(--paper-elevated)" }}>
              <th style={cellHead}>Suite</th>
              <th style={cellHead}>Last run</th>
              <th style={cellHead}>Status</th>
              <th style={cellHead}>Affected rulespec repos</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((entry) => (
              <tr
                key={entry.suite}
                style={{ borderTop: "1px solid var(--hairline)" }}
              >
                <td style={cell}>{suiteLabel(entry.suite)}</td>
                <td style={cell}>
                  <span className="mono" style={{ fontSize: 12 }}>
                    {ageLabel(entry.days, entry.unstamped)}
                  </span>
                  {entry.run_kind && (
                    <span
                      className="mono"
                      style={{ fontSize: 11, color: "var(--ink-mute)" }}
                    >
                      {" "}· {entry.run_kind}
                    </span>
                  )}
                </td>
                <td style={cell}>
                  <FreshnessBadge
                    days={entry.days}
                    unstamped={entry.unstamped}
                    maxAge={maxAge}
                  />
                </td>
                <td style={cell}>
                  <RepoChips
                    repos={entry.affected_repos}
                    ranAgainst={entry.ran_against}
                  />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

const cellHead = {
  textAlign: "left",
  padding: "8px 12px",
  fontSize: 11,
  textTransform: "uppercase",
  letterSpacing: "0.04em",
  color: "var(--ink-mute)",
  fontWeight: 600,
};

const cell = {
  padding: "8px 12px",
  verticalAlign: "top",
};
