"""Child Winter Heating Payment suite for the UKMOD ``bchht_s`` oracle.

The Child Winter Heating Payment (Winter Heating Assistance for Children and
Young People (Scotland) Regulations 2020, SSI 2020/352) is a devolved flat
annual payment for a severely disabled child or young person in Scotland who
receives the highest rate of the care component of Disability Living Allowance /
the enhanced daily living component of Personal Independence Payment (or the
Child/Adult Disability Payment equivalents). rulespec-uk encodes the statutory
payable value (uk/policies/govuk/child-winter-heating-payment): a flat GBP
265.50 per year (regulation 10(1)).

UKMOD's ``bchht_uk`` computes ``bchht_s`` for a qualifying disabled child in a
Scotland household (drgn1=12) whose disability input carries the high-rate care
passport (``bdisc``). Verified on the x64 runner (UKMOD_PUBLIC_B2026.03 /
UK_2026): ``bchht_s`` = 265.50/year, matching the statutory GBP 265.50 exactly
(no annualisation convention applies — the payment is defined as a flat annual
amount, not a weekly rate).

The rulespec-uk payable value is the statutory amount (the module encodes the
GBP 265.50 flat value, not the disability-passport eligibility, which is UKMOD's
determination). UKMOD take-up is disabled via ``euromod_policy_switch_overrides``
(BTA_uk / random_uk = false) so the payment fires deterministically.

This suite runs where the x64 UKMOD runtime and model checkout are available and
is regenerated by scripts/regenerate_euromod_uk.sh; on runners without them it
re-emits the committed dashboard report.
"""

from __future__ import annotations

from ..core.case import Case, Concepts, Entity


UK_SCOPE = {"type": "country", "geoid": "UK"}
UK_CWHA_METADATA = {
    "locale": "UK",
    "scope": UK_SCOPE,
    "axiom_entity": "Family",
    "axiom_entity_id": "benefit_unit",
}

CWHA_MODULE = "uk:policies/govuk/child-winter-heating-payment"

# The Child Winter Heating Payment 2026-27 value applies from 2026-04; UKMOD
# UK_2026 uses the same value.
UK_CWHA_PERIOD = "2026-04-06"

# UKMOD demographic / labour codes (shared with the Scottish Child Payment suite).
_DEC_CHILD = 4
_LES_EMPLOYED = 3
_LES_CHILD = 6
_DCT = 15
_DRGN_SCOTLAND = 12
_AMRTN_SOCIAL_RENTER = 5
_HEAD_AGE = 40
_HEAD_MONTHLY_EARNINGS = 400.0
# High-rate care passport for the qualifying disabled child (monthly amount that
# UKMOD reads as the high-rate DLA care / PIP daily living component).
_HIGH_RATE_CARE_MONTHLY = 478.0
_TAKEUP_OVERRIDES = (("BTA_uk", False), ("random_uk", False))


def uk_child_winter_heating_payment_cases() -> list[Case]:
    """Single disabled-child Scotland Child Winter Heating Payment case."""

    return [
        _cwha_case("uk-cwha-scotland-disabled-child10", child_age=10),
    ]


def _cwha_case(case_id: str, *, child_age: int) -> Case:
    rows = _euromod_household_rows(child_age=child_age)
    return Case(
        case_id=case_id,
        period=UK_CWHA_PERIOD,
        facts={
            Concepts.YEARLY_EARNED_INCOME: _HEAD_MONTHLY_EARNINGS * 12.0,
        },
        metadata={
            **UK_CWHA_METADATA,
            "scenario": "scotland-child-winter-heating-payment",
            "child_age": child_age,
            # The payable value is the flat statutory amount (reg 10(1)); the
            # module takes no inputs, so the pipeline returns GBP 265.50 directly.
            "axiom_inputs": {},
            "euromod_inputs": rows,
            "euromod_policy_switch_overrides": [list(p) for p in _TAKEUP_OVERRIDES],
        },
        entities=_entities(child_age=child_age),
        outputs=(Concepts.UK_HOUSEHOLD_CHILD_WINTER_HEATING_PAYMENT_AWARD,),
    )


def _entities(*, child_age: int) -> tuple[Entity, ...]:
    return (
        Entity(
            entity_id="head",
            kind="person",
            facts={
                Concepts.PERSON_AGE: _HEAD_AGE,
                Concepts.HOUSEHOLD_RELATION: "HeadOfHousehold",
                Concepts.YEARLY_EARNED_INCOME: _HEAD_MONTHLY_EARNINGS * 12.0,
            },
        ),
        Entity(
            entity_id="child",
            kind="person",
            facts={
                Concepts.PERSON_AGE: child_age,
                Concepts.HOUSEHOLD_RELATION: "Child",
                Concepts.YEARLY_EARNED_INCOME: 0.0,
            },
        ),
    )


def _euromod_household_rows(*, child_age: int) -> list[dict[str, float | int]]:
    head_id, child_id = 101, 201
    return [
        {
            "idhh": 1,
            "idperson": head_id,
            "idpartner": 0,
            "idmother": 0,
            "idfather": 0,
            "idmotherbio": 0,
            "idfatherbio": 0,
            "drgn1": _DRGN_SCOTLAND,
            "dct": _DCT,
            "dwt": 1000.0,
            "dag": _HEAD_AGE,
            "dgn": 1,
            "dms": 1,
            "dhr": 1,
            "dec": 0,
            "ddi": 0,
            "les": _LES_EMPLOYED,
            "lhw": 20,
            "lhw01": 20,
            "loc": 5,
            "amrtn": _AMRTN_SOCIAL_RENTER,
            "yem": _HEAD_MONTHLY_EARNINGS,
            "yse": 0.0,
            "yiy": 0.0,
            "poa": 0.0,
            "boact00": 0.0,
            "xhcrt": 500.0,
            "xhcsc": 0.0,
            "afc": 0.0,
        },
        {
            "idhh": 1,
            "idperson": child_id,
            "idpartner": 0,
            "idmother": head_id,
            "idfather": 0,
            "idmotherbio": head_id,
            "idfatherbio": 0,
            "drgn1": _DRGN_SCOTLAND,
            "dct": _DCT,
            "dwt": 1000.0,
            "dag": child_age,
            "dgn": 1,
            "dms": 1,
            "dhr": 0,
            "dec": _DEC_CHILD,
            "ddi": 1,
            "les": _LES_CHILD,
            "lhw": 0,
            "lhw01": 0,
            "loc": 5,
            "amrtn": _AMRTN_SOCIAL_RENTER,
            "yem": 0.0,
            "yse": 0.0,
            "yiy": 0.0,
            "poa": 0.0,
            "boact00": 0.0,
            "xhcrt": 0.0,
            "xhcsc": 0.0,
            "afc": 0.0,
            "bdisc": _HIGH_RATE_CARE_MONTHLY,
        },
    ]
