"""Contribution-based JSA suite for the UKMOD ``bunct_s`` oracle.

Contribution-based (contributory) jobseeker's allowance is a reserved, UK-wide
benefit. rulespec-uk encodes the age-related weekly amount (Jobseeker's
Allowance Regulations 1996, SI 1996/207, regulation 79(1) as amended for 2026-27
by the Social Security Benefits Up-rating Order 2026,
uk/policies/govuk/contribution-based-jobseekers-allowance): GBP 75.65/week for a
claimant who has not attained 25 and GBP 95.55/week for a claimant aged 25 or
over, annualised over 52 weeks.

UKMOD's ``bunct_uk`` computes ``bunct_s`` for an unemployed claimant (les=5) who
receives contribution-based JSA (bunct>0) and satisfies the contribution
condition (liwwh). Verified on the x64 runner (UKMOD_PUBLIC_B2026.03 / UK_2026):

- under-25 claimant: ``bunct_s`` = 3,944.61/year (75.65 * 365 / 7)
- 25-or-over claimant: ``bunct_s`` = 4,982.25/year (95.55 * 365 / 7)

The weekly statutory rate is identical to the pipeline's (75.65 / 95.55); the
only residual is the annualisation convention (UKMOD 365/7 weeks/year vs the
pipeline's 52), dispositioned explained_residual, exactly as for the Scottish
Child Payment suite. UKMOD take-up is disabled via
``euromod_policy_switch_overrides`` (BTA_uk / random_uk = false) so the award
fires deterministically.

This suite runs where the x64 UKMOD runtime and model checkout are available and
is regenerated by scripts/regenerate_euromod_uk.sh; on runners without them it
re-emits the committed dashboard report.
"""

from __future__ import annotations

from ..core.case import Case, Concepts, Entity


UK_SCOPE = {"type": "country", "geoid": "UK"}
UK_JSA_METADATA = {
    "locale": "UK",
    "scope": UK_SCOPE,
    "axiom_entity": "Family",
    "axiom_entity_id": "benefit_unit",
}

JSA_MODULE = "uk:policies/govuk/contribution-based-jobseekers-allowance"

UK_JSA_PERIOD = "2026-04-06"

# UKMOD demographic / labour codes. Contribution-based JSA is reserved (UK-wide),
# so the region is England (drgn1=2); the amount is not devolved.
_DCT = 15
_DRGN_ENGLAND = 2
_LES_UNEMPLOYED = 5
_AMRTN_SOCIAL_RENTER = 5
# UKMOD contribution-based JSA passport: a positive award marker (bunct) and the
# contribution weeks (liwwh) that satisfy the first/second contribution
# conditions for a full contributory award.
_JSA_AWARD_MARKER = 100.0
_JSA_CONTRIBUTION_WEEKS = 260
_TAKEUP_OVERRIDES = (("BTA_uk", False), ("random_uk", False))


def uk_contribution_based_jsa_cases() -> list[Case]:
    """Under-25 and 25-or-over contribution-based JSA cases for UKMOD UK_2026."""

    return [
        _jsa_case("uk-jsa-contributory-under25", claimant_age=22, attained_25=False),
        _jsa_case("uk-jsa-contributory-25plus", claimant_age=40, attained_25=True),
    ]


def _jsa_case(case_id: str, *, claimant_age: int, attained_25: bool) -> Case:
    rows = _euromod_household_rows(claimant_age=claimant_age)
    return Case(
        case_id=case_id,
        period=UK_JSA_PERIOD,
        facts={
            Concepts.YEARLY_EARNED_INCOME: 0.0,
        },
        metadata={
            **UK_JSA_METADATA,
            "scenario": "contribution-based-jsa",
            "claimant_age": claimant_age,
            "axiom_inputs": {
                _pipeline_input("entitled_to_contribution_based_jsa"): True,
                _pipeline_input("claimant_has_attained_age_25"): attained_25,
            },
            "euromod_inputs": rows,
            "euromod_policy_switch_overrides": [list(p) for p in _TAKEUP_OVERRIDES],
        },
        entities=_entities(claimant_age=claimant_age),
        outputs=(Concepts.UK_HOUSEHOLD_CONTRIBUTION_BASED_JSA_AWARD,),
    )


def _pipeline_input(name: str) -> str:
    return f"{JSA_MODULE}#input.{name}"


def _entities(*, claimant_age: int) -> tuple[Entity, ...]:
    return (
        Entity(
            entity_id="claimant",
            kind="person",
            facts={
                Concepts.PERSON_AGE: claimant_age,
                Concepts.HOUSEHOLD_RELATION: "HeadOfHousehold",
                Concepts.YEARLY_EARNED_INCOME: 0.0,
            },
        ),
    )


def _euromod_household_rows(*, claimant_age: int) -> list[dict[str, float | int]]:
    claimant_id = 101
    return [
        {
            "idhh": 1,
            "idperson": claimant_id,
            "idpartner": 0,
            "idmother": 0,
            "idfather": 0,
            "idmotherbio": 0,
            "idfatherbio": 0,
            "drgn1": _DRGN_ENGLAND,
            "dct": _DCT,
            "dwt": 1000.0,
            "dag": claimant_age,
            "dgn": 1,
            "dms": 1,
            "dhr": 1,
            "dec": 0,
            "ddi": 0,
            "les": _LES_UNEMPLOYED,
            "lhw": 0,
            "lhw01": 0,
            "loc": 5,
            "amrtn": _AMRTN_SOCIAL_RENTER,
            "yem": 0.0,
            "yse": 0.0,
            "yiy": 0.0,
            "poa": 0.0,
            "boact00": 0.0,
            "xhcrt": 0.0,
            "xhcsc": 0.0,
            "afc": 0.0,
            "bunct": _JSA_AWARD_MARKER,
            "liwwh": _JSA_CONTRIBUTION_WEEKS,
        },
    ]
