"""Scottish Carer Supplement suite for the UKMOD ``bcrdicm_s`` oracle.

The Scottish Carer Supplement is the Scottish top-up paid in addition to Carer
Support Payment (Carer's Assistance (Carer Support Payment) (Scotland)
Regulations 2023, SSI 2023/302, regulation 16(1A)). rulespec-uk encodes the
supplement weekly rate (uk/policies/govuk/scottish-carer-supplement): GBP
11.70/week, annualised over 52 weeks (608.40/year). The base Carer Support
Payment rate (GBP 86.45) is a separate award and is not included.

UKMOD's ``bcrdicm_uk`` computes ``bcrdicm_s`` — the carer supplement top-up — for
a carer in a Scotland benefit unit (drgn1=12) who receives the underlying carer
award (bcrdi>0). Verified on the x64 runner (UKMOD_PUBLIC_B2026.03 / UK_2026):
``bcrdicm_s`` = 609.55/year (about GBP 11.69/week annualised at 365/7). The
pipeline's supplement (11.70 * 52 = 608.40) differs only by a small
annualisation/uprating-timing residual, dispositioned explained_residual. UKMOD
take-up is disabled via ``euromod_policy_switch_overrides`` (BTA_uk / random_uk =
false) so the supplement fires deterministically.

This suite runs where the x64 UKMOD runtime and model checkout are available and
is regenerated by scripts/regenerate_euromod_uk.sh; on runners without them it
re-emits the committed dashboard report.
"""

from __future__ import annotations

from ..core.case import Case, Concepts, Entity


UK_SCOPE = {"type": "country", "geoid": "UK"}
UK_SCS_METADATA = {
    "locale": "UK",
    "scope": UK_SCOPE,
    "axiom_entity": "Family",
    "axiom_entity_id": "benefit_unit",
}

SCS_MODULE = "uk:policies/govuk/scottish-carer-supplement"

UK_SCS_PERIOD = "2026-04-06"

# UKMOD demographic / labour codes.
_DCT = 15
_DRGN_SCOTLAND = 12
_LES_CARER = 6
_AMRTN_SOCIAL_RENTER = 5
_CARER_AGE = 40
# UKMOD carer award passport: a positive monthly carer-award marker (bcrdi) for
# a carer in Scotland, which triggers the Scottish Carer Supplement top-up.
_CARER_AWARD_MONTHLY = 361.0
_TAKEUP_OVERRIDES = (("BTA_uk", False), ("random_uk", False))


def uk_scottish_carer_supplement_cases() -> list[Case]:
    """Single Scotland carer Scottish Carer Supplement case for UKMOD UK_2026."""

    return [
        _scs_case("uk-scs-scotland-carer"),
    ]


def _scs_case(case_id: str) -> Case:
    rows = _euromod_household_rows()
    return Case(
        case_id=case_id,
        period=UK_SCS_PERIOD,
        facts={
            Concepts.YEARLY_EARNED_INCOME: 0.0,
        },
        metadata={
            **UK_SCS_METADATA,
            "scenario": "scotland-scottish-carer-supplement",
            "axiom_inputs": {
                _pipeline_input("entitled_to_scottish_carer_supplement"): True,
            },
            "euromod_inputs": rows,
            "euromod_policy_switch_overrides": [list(p) for p in _TAKEUP_OVERRIDES],
        },
        entities=_entities(),
        outputs=(Concepts.UK_HOUSEHOLD_SCOTTISH_CARER_SUPPLEMENT_AWARD,),
    )


def _pipeline_input(name: str) -> str:
    return f"{SCS_MODULE}#input.{name}"


def _entities() -> tuple[Entity, ...]:
    return (
        Entity(
            entity_id="carer",
            kind="person",
            facts={
                Concepts.PERSON_AGE: _CARER_AGE,
                Concepts.HOUSEHOLD_RELATION: "HeadOfHousehold",
                Concepts.YEARLY_EARNED_INCOME: 0.0,
            },
        ),
    )


def _euromod_household_rows() -> list[dict[str, float | int]]:
    carer_id = 101
    return [
        {
            "idhh": 1,
            "idperson": carer_id,
            "idpartner": 0,
            "idmother": 0,
            "idfather": 0,
            "idmotherbio": 0,
            "idfatherbio": 0,
            "drgn1": _DRGN_SCOTLAND,
            "dct": _DCT,
            "dwt": 1000.0,
            "dag": _CARER_AGE,
            "dgn": 1,
            "dms": 1,
            "dhr": 1,
            "dec": 0,
            "ddi": 0,
            "les": _LES_CARER,
            "lhw": 0,
            "lhw01": 0,
            "loc": 5,
            "amrtn": _AMRTN_SOCIAL_RENTER,
            "yem": 0.0,
            "yse": 0.0,
            "yiy": 0.0,
            "poa": 0.0,
            "boact00": 0.0,
            "xhcrt": 0.0,
            "xhcsc": 0.0,
            "afc": 0.0,
            "bcrdi": _CARER_AWARD_MONTHLY,
        },
    ]
