"""Scottish Child Payment suite for the UKMOD ``bchmt_s`` oracle.

The Scottish Child Payment (Scottish Child Payment Regulations 2020, SSI
2020/351) is a devolved weekly payment for a qualifying child under 16 whose
applicant or partner receives a qualifying means-tested benefit. rulespec-uk
encodes it per child (uk/policies/govuk/scottish-child-payment): the weekly
amount for a child, gated on Scotland residence, the maximum child age, and the
qualifying-benefit passport. UKMOD's ``bchmt_uk`` computes ``bchmt_s`` at the
benefit-unit level — the summed qualifying-child payment, passporting off
``il_bchmt`` (the sum of the qualifying means-tested awards boamt_s + bsadi_s +
bunmt_s + bsa_s + bwkmt_s + bfamt_s + bsauc_s) for a Scotland benefit unit
(drgn1=12), take-up-adjusted by the stochastic ``i_rand_tu`` draw against
``$SCPTUu6y`` (under 6) / ``$SCPTU6to15y`` (6-15).

The grid is SINGLE-CHILD Scotland benefit units so the per-child rulespec-uk
amount equals UKMOD's benefit-unit ``bchmt_s`` directly (no multi-child summing,
which the per-child module cannot express through a single case-level child_age
input). Each unit is a lone parent working part-time on a low income, so UKMOD
pays Universal Credit ``bsauc_s`` (the qualifying passport) and the Scottish
Child Payment fires. The qualifying-benefit passport is supplied to the pipeline
as ``applicant_or_partner_receives_qualifying_benefit`` = whether UKMOD's unit is
on a qualifying award.

Verified UKMOD conventions (UKMOD_PUBLIC_B2026.03 / UK_2026, executed on the x64
runner — numbers emitted only there):

- Scottish Child Payment is *simulated*: ``bchmt_uk`` (Switch=on) computes
  ``bchmt_s`` from statute. For a single qualifying child in a Scotland benefit
  unit on Universal Credit, ``bchmt_s`` = 1,470.43/year, matching the weekly
  rate 28.20 the pipeline encodes (28.20 * 365 / 7 = 1,470.43).

- WEEKS CONVENTION: UKMOD annualizes the weekly rate at 365/7 = 52.142857
  weeks/year (1,470.43); the rulespec-uk pipeline uses
  ``scottish_child_payment_weeks_in_year`` = 52 (28.20 * 52 = 1,466.40). The
  weekly statutory rate is identical (28.20); only the annualization convention
  differs, a period-conversion residual dispositioned explained_residual in
  ``dispositions/uk-scottish-child-payment.yaml`` (not an encoding gap on either
  side). An income sweep is not used because the amount is flat (SCP is not
  income-tapered — the qualifying-benefit passport is a gate, not a taper).

- ``bchmt_s`` embeds UKMOD's Scottish Child Payment take-up draw (i_rand_tu vs
  $SCPTUu6y / $SCPTU6to15y). The comparison pins those two rates to 1.0 through
  ``euromod_constant_overrides`` (the or#168 pinning path) so the engine returns
  the statutory entitlement; the qualifying Universal Credit passport is kept on
  by pinning its take-up ($ISTUChild) to 1.0 and setting $UCtransition=0 (Full
  Legacy path off), so a Scotland low-income family reliably draws the UC award
  that passports the payment. Residual take-up zeros (if any) are dispositioned
  upstream_engine_gap, the same EUROMOD-platform behaviour documented for the UC
  and Pension Credit suites.

This suite runs where the x64 UKMOD runtime and model checkout are available and
is regenerated by scripts/regenerate_euromod_uk.sh; on runners without them it
re-emits the committed dashboard report.
"""

from __future__ import annotations

from ..core.case import Case, Concepts, Entity


UK_SCOPE = {"type": "country", "geoid": "UK"}
UK_SCP_METADATA = {
    "locale": "UK",
    "scope": UK_SCOPE,
    "axiom_entity": "Family",
    "axiom_entity_id": "benefit_unit",
}

# rulespec-uk per-child Scottish Child Payment module (SSI 2020/351).
SCP_MODULE = "uk:policies/govuk/scottish-child-payment"

# The Scottish Child Payment 2026-27 weekly rate applies from 2026-04; UKMOD
# UK_2026 uses the same rate.
UK_SCP_PERIOD = "2026-04"

# UKMOD demographic / labour codes (shared with the UC/HB/PC suites).
_DMS_SINGLE = 1
_DEC_CHILD = 4
_LES_EMPLOYED = 3
_LES_CHILD = 6
_DCT = 15
_DRGN_SCOTLAND = 12
# Social renter so a Universal Credit housing element is available; the SCP
# comparison does not depend on tenure (the qualifying passport is UC).
_AMRTN_SOCIAL_RENTER = 5
_HEAD_AGE = 30
# Pin the SCP take-up rates and the UC-child take-up so the qualifying award and
# the Scottish Child Payment both fire deterministically; disable the legacy/UC
# transition sampling so a Scotland low-income family stays on Universal Credit.
_CONSTANT_OVERRIDES = (
    ("$UCtransition", "0"),
    ("$SCPTUu6y", "1.0"),
    ("$SCPTU6to15y", "1.0"),
    ("$ISTUChild", "1.0"),
)
_TAKEUP_OVERRIDES = (("BTA_uk", False), ("random_uk", False))


def uk_scottish_child_payment_cases() -> list[Case]:
    """Single-child Scotland Scottish Child Payment cases for UKMOD UK_2026."""

    return [
        # Qualifying children across the two take-up age bands (under 6, 6-15).
        _scp_case("uk-scp-scotland-child4-uc", child_age=4, on_qualifying_benefit=True),
        _scp_case("uk-scp-scotland-child7-uc", child_age=7, on_qualifying_benefit=True),
        _scp_case(
            "uk-scp-scotland-child15-uc", child_age=15, on_qualifying_benefit=True
        ),
        # Age gate: a child of 16 is over the maximum age, so the payment is nil
        # on both engines.
        _scp_case(
            "uk-scp-scotland-child16-uc", child_age=16, on_qualifying_benefit=True
        ),
    ]


def _scp_case(case_id: str, *, child_age: int, on_qualifying_benefit: bool) -> Case:
    rows = _euromod_household_rows(child_age=child_age)
    return Case(
        case_id=case_id,
        period=UK_SCP_PERIOD,
        facts={
            Concepts.YEARLY_EARNED_INCOME: _HEAD_MONTHLY_EARNINGS * 12.0,
        },
        metadata={
            **UK_SCP_METADATA,
            "scenario": "scotland-scottish-child-payment",
            "child_age": child_age,
            "on_qualifying_benefit": on_qualifying_benefit,
            "axiom_inputs": {
                _pipeline_input("person_lives_in_scotland"): True,
                _pipeline_input("child_age"): child_age,
                _pipeline_input(
                    "applicant_or_partner_receives_qualifying_benefit"
                ): on_qualifying_benefit,
            },
            "euromod_inputs": rows,
            "euromod_policy_switch_overrides": [list(p) for p in _TAKEUP_OVERRIDES],
            "euromod_constant_overrides": [list(p) for p in _CONSTANT_OVERRIDES],
        },
        entities=_entities(child_age=child_age),
        outputs=(Concepts.UK_HOUSEHOLD_SCOTTISH_CHILD_PAYMENT_AWARD,),
    )


def _pipeline_input(name: str) -> str:
    return f"{SCP_MODULE}#input.{name}"


# A low part-time earned income so UKMOD pays Universal Credit (the qualifying
# passport for the Scottish Child Payment).
_HEAD_MONTHLY_EARNINGS = 400.0


def _entities(*, child_age: int) -> tuple[Entity, ...]:
    return (
        Entity(
            entity_id="head",
            kind="person",
            facts={
                Concepts.PERSON_AGE: _HEAD_AGE,
                Concepts.HOUSEHOLD_RELATION: "HeadOfHousehold",
                Concepts.YEARLY_EARNED_INCOME: _HEAD_MONTHLY_EARNINGS * 12.0,
            },
        ),
        Entity(
            entity_id="child",
            kind="person",
            facts={
                Concepts.PERSON_AGE: child_age,
                Concepts.HOUSEHOLD_RELATION: "Child",
                Concepts.YEARLY_EARNED_INCOME: 0.0,
            },
        ),
    )


def _euromod_household_rows(*, child_age: int) -> list[dict[str, float | int]]:
    head_id, child_id = 101, 201
    return [
        {
            "idhh": 1,
            "idperson": head_id,
            "idpartner": 0,
            "idmother": 0,
            "idfather": 0,
            "idmotherbio": 0,
            "idfatherbio": 0,
            "drgn1": _DRGN_SCOTLAND,
            "dct": _DCT,
            "dwt": 1000.0,
            "dag": _HEAD_AGE,
            "dgn": 1,
            "dms": _DMS_SINGLE,
            "dhr": 1,
            "dec": 0,
            "ddi": 0,
            "les": _LES_EMPLOYED,
            "lhw": 20,
            "lhw01": 20,
            "loc": 5,
            "amrtn": _AMRTN_SOCIAL_RENTER,
            "yem": _HEAD_MONTHLY_EARNINGS,
            "yse": 0.0,
            "yiy": 0.0,
            "poa": 0.0,
            "boact00": 0.0,
            "xhcrt": 500.0,
            "xhcsc": 0.0,
            "afc": 0.0,
        },
        {
            "idhh": 1,
            "idperson": child_id,
            "idpartner": 0,
            "idmother": head_id,
            "idfather": 0,
            "idmotherbio": head_id,
            "idfatherbio": 0,
            "drgn1": _DRGN_SCOTLAND,
            "dct": _DCT,
            "dwt": 1000.0,
            "dag": child_age,
            "dgn": 1,
            "dms": _DMS_SINGLE,
            "dhr": 0,
            "dec": _DEC_CHILD,
            "ddi": 0,
            "les": _LES_CHILD,
            "lhw": 0,
            "lhw01": 0,
            "loc": 5,
            "amrtn": _AMRTN_SOCIAL_RENTER,
            "yem": 0.0,
            "yse": 0.0,
            "yiy": 0.0,
            "poa": 0.0,
            "boact00": 0.0,
            "xhcrt": 0.0,
            "xhcsc": 0.0,
            "afc": 0.0,
        },
    ]
