#!/usr/bin/env python3
"""Build the source-completeness ledger for DK boerne- og ungeydelse.

The ledger has an explicit trust split:

* ``generated_facts`` are re-derived from the pinned corpus release and the
  exact tracked bytes at a RuleSpec git ref;
* ``committed_decisions`` are the reviewable exclusions and input-grounding
  decisions preserved across generation; and
* ``computed`` is a pure join of those two blocks.

``--check`` performs the full reproduction and fails closed when either source
is missing.  :func:`validate_artifact` separately checks the committed
artifact's internal derivation without requiring sibling repositories, so
certificate generation remains hermetic.

Usage::

    .venv/bin/python scripts/closure_ledger.py --generate
    .venv/bin/python scripts/closure_ledger.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
ARTIFACT_PATH = REPO_ROOT / "conformance" / "closure" / "dk-boerne-og-ungeydelse.yaml"
CORPUS_RELEASE_PATH = (
    Path.home()
    / "TheAxiomFoundation"
    / "_worktrees"
    / "axiom-corpus-dk-campaign"
    / "data"
    / "corpus"
    / "provisions"
    / "dk"
    / "statute"
    / "2026-08-04-dk-full-parity-tier1-current.jsonl"
)
CORPUS_REF = "HEAD"
RULESPEC_ROOT = Path.home() / "TheAxiomFoundation" / "rulespec-dk"
RULESPEC_REF = "main"

SCHEMA = "axiom_oracles.closure.ledger.v3"
PROGRAM_ID = "dk/boerne-og-ungeydelse"
CORPUS_ROOT = "dk/statute/lbk-603-2025/boerne-og-ungeydelsesloven"
STATUSES = (
    "encoded",
    "partially-encoded",
    "classified-with-reason",
    "excluded-with-reason",
    "pending",
)
GROUNDINGS = ("captured", "uncaptured")
LEAF_KINDS = ("world_fact", "law_derived")
INSTRUMENT_GRAPH_PATH = (
    REPO_ROOT / "conformance" / "closure" / "dk-instrument-graph.json"
)
INSTRUMENT_GRAPH_SCHEMA = "axiom_oracles.closure.instrument_graph.v1"
INSTRUMENT_ACT_ELI = "https://retsinformation.dk/eli/lta/2025/603"
INSTRUMENT_STATUSES = (
    "encoded",
    "classified-with-reason",
    "excluded-with-reason",
    "pending",
)
INSTRUMENT_RELATIONS = ("basis_for", "changed_by")
SUPPLEMENTAL_RELATION = "bears_on"

_HEADER = """# axiom_oracles.closure.ledger.v3 — GENERATED facts + committed decisions.
# provision_spine, rulespec_modules, module_inputs, computed, and source hashes are
# regenerated by scripts/closure_ledger.py.  Edit only committed_decisions; the
# generator preserves those rows and --check fails on any other drift.
"""
_HEX_SHA256 = re.compile(r"^[0-9a-f]{64}$")
#: A git object id: 40 lowercase hex chars with at least one of a-f. A
#: decimal-only 40-char string is not a realistic commit (P ≈ (10/16)^40)
#: and is exactly the YAML !!str-digit forgery shape (delta-audit #8), so it
#: is rejected outright rather than compared.
_HEX_GIT_SHA = re.compile(r"^(?=[0-9a-f]{40}$)(?=.*[a-f])[0-9a-f]{40}$")
_IDENTIFIER = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")
_FORMULA_PROOF_PATH = re.compile(r"^versions\[(0|[1-9][0-9]*)\]\.formula$")
_RESERVED_FORMULA_WORDS = frozenset({"and", "else", "false", "if", "not", "or", "true"})
_PROOF_ATOM_FIELDS = (
    "corpus_citation_path",
    "rule",
    "path",
    "kind",
    "excerpt_sha256",
    "formula_sha256",
)


class ClosureLedgerError(ValueError):
    """Raised when a committed closure artifact is not internally valid."""

    def __init__(self, errors: Sequence[str]):
        self.errors = tuple(errors)
        super().__init__("; ".join(self.errors))


@dataclass(frozen=True)
class ClosureSummary:
    """Hermetically derived certificate inputs from a valid artifact."""

    closed: bool
    encoded_count: int
    partially_encoded_count: int
    pending_count: int
    frontier_complete: bool
    non_encoded_reasons_complete: bool
    instrument_count: int
    instrument_pending_count: int
    instrument_frontier_complete: bool
    open_dependency_count: int
    dependency_closed: bool


@dataclass(frozen=True)
class VerificationResult:
    """Result of re-deriving a committed artifact from its external sources."""

    document: dict[str, Any] | None
    expected: dict[str, Any] | None
    errors: tuple[str, ...]

    @property
    def valid(self) -> bool:
        return not self.errors

    @property
    def closed(self) -> bool:
        if not self.valid or self.document is None:
            return False
        computed = self.document.get("computed")
        return bool(isinstance(computed, Mapping) and computed.get("closed") is True)


class _SourceError(RuntimeError):
    pass


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _git_bytes(root: Path, *args: str) -> bytes:
    result = subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        check=False,
    )
    if result.returncode:
        detail = result.stderr.decode(errors="replace").strip()
        raise _SourceError(f"git {' '.join(args)} failed in {root}: {detail}")
    return result.stdout


def _resolve_commit(root: Path, ref: str, *, label: str) -> str:
    commit = _git_bytes(root, "rev-parse", "--verify", f"{ref}^{{commit}}")
    value = commit.decode().strip()
    if not _HEX_GIT_SHA.fullmatch(value):
        raise _SourceError(f"{label} ref {ref!r} did not resolve to a full commit SHA")
    return value


def _rulespec_commit(root: Path, ref: str) -> str:
    return _resolve_commit(root, ref, label="rulespec")


def _rulespec_paths(root: Path, ref: str) -> list[str]:
    raw = _git_bytes(
        root,
        "ls-tree",
        "-r",
        "-z",
        "--name-only",
        ref,
        "--",
        "dk/statutes",
    )
    return sorted(
        path.decode()
        for path in raw.split(b"\0")
        if path and path.endswith(b".yaml") and not path.endswith(b".test.yaml")
    )


def _rulespec_blob(root: Path, ref: str, path: str) -> bytes:
    return _git_bytes(root, "show", f"{ref}:{path}")


def _module_id(path: str) -> str:
    without_suffix = path.removesuffix(".yaml")
    jurisdiction, separator, remainder = without_suffix.partition("/")
    if not separator:
        raise _SourceError(f"invalid RuleSpec module path: {path}")
    return f"{jurisdiction}:{remainder}"


def _load_yaml_bytes(data: bytes, *, label: str) -> Any:
    try:
        return yaml.safe_load(data)
    except yaml.YAMLError as exc:
        raise _SourceError(f"could not parse {label}: {exc}") from exc


def _corpus_blob(path: Path, ref: str) -> tuple[str, str, bytes]:
    """Read a tracked corpus path through one immutable resolved commit."""

    if not path.parent.is_dir():
        raise _SourceError(f"corpus release parent is missing: {path.parent}")
    repo_raw = _git_bytes(path.parent, "rev-parse", "--show-toplevel")
    repo_root = Path(repo_raw.decode().strip()).resolve()
    try:
        relative = path.resolve().relative_to(repo_root).as_posix()
    except ValueError as exc:
        raise _SourceError(
            f"corpus release is outside its git repository: {path}"
        ) from exc
    commit = _resolve_commit(repo_root, ref, label="corpus")
    tracked = _git_bytes(
        repo_root,
        "ls-tree",
        "-z",
        "--name-only",
        commit,
        "--",
        relative,
    )
    tracked_paths = [value.decode() for value in tracked.split(b"\0") if value]
    if tracked_paths != [relative]:
        raise _SourceError(
            f"corpus release is not tracked at {ref} ({commit}): {relative}"
        )
    blob = _git_bytes(repo_root, "show", f"{commit}:{relative}")
    return relative, commit, blob


def _read_corpus_spine(
    path: Path, ref: str
) -> tuple[dict[str, Any], list[dict[str, Any]], dict[str, str]]:
    relative_path, commit, blob = _corpus_blob(path, ref)
    try:
        lines = blob.decode("utf-8").splitlines()
    except UnicodeDecodeError as exc:
        raise _SourceError(
            f"corpus blob {commit}:{relative_path} is not UTF-8: {exc}"
        ) from exc

    document_row: dict[str, Any] | None = None
    provisions: list[dict[str, Any]] = []
    provision_bodies: dict[str, str] = {}
    for line_number, line in enumerate(lines, start=1):
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            raise _SourceError(
                f"{commit}:{relative_path}:{line_number}: invalid JSON: {exc}"
            ) from exc
        if row.get("citation_path") == CORPUS_ROOT and row.get("kind") == "document":
            if document_row is not None:
                raise _SourceError(f"duplicate corpus document row for {CORPUS_ROOT}")
            document_row = row
            continue
        if (
            row.get("kind") == "section"
            and row.get("parent_citation_path") == CORPUS_ROOT
        ):
            body = row.get("body")
            heading = row.get("heading")
            citation_path = row.get("citation_path")
            ordinal = row.get("ordinal")
            if (
                not isinstance(body, str)
                or not body.strip()
                or not isinstance(heading, str)
                or not heading.strip()
                or not isinstance(citation_path, str)
                or not citation_path.startswith(f"{CORPUS_ROOT}/")
                or isinstance(ordinal, bool)
                or not isinstance(ordinal, int)
            ):
                raise _SourceError(
                    f"{commit}:{relative_path}:{line_number}: malformed provision "
                    f"under {CORPUS_ROOT}"
                )
            provisions.append(
                {
                    "ordinal": ordinal,
                    "citation_path": citation_path,
                    "heading": heading,
                    "body_sha256": _sha256_bytes(body.encode()),
                }
            )
            provision_bodies[citation_path] = body

    if document_row is None:
        raise _SourceError(f"corpus release has no document row for {CORPUS_ROOT}")
    provisions.sort(key=lambda row: (row["ordinal"], row["citation_path"]))
    citations = [row["citation_path"] for row in provisions]
    ordinals = [row["ordinal"] for row in provisions]
    if len(citations) != len(set(citations)):
        raise _SourceError(
            f"corpus release has duplicate provisions under {CORPUS_ROOT}"
        )
    if ordinals != list(range(1, len(provisions) + 1)):
        raise _SourceError(
            f"corpus provision ordinals under {CORPUS_ROOT} are not contiguous from 1"
        )
    metadata = document_row.get("metadata")
    block_count = metadata.get("block_count") if isinstance(metadata, Mapping) else None
    if block_count != len(provisions):
        raise _SourceError(
            f"corpus document declares {block_count!r} blocks but yielded "
            f"{len(provisions)} direct paragraffer"
        )

    generated_source = {
        "repository": "TheAxiomFoundation/axiom-corpus",
        "ref": commit,
        "commit": commit,
        "path": relative_path,
        "sha256": _sha256_bytes(blob),
        "version": document_row.get("version"),
        "source_id": document_row.get("source_id"),
        "source_as_of": document_row.get("source_as_of"),
        "citation_root": CORPUS_ROOT,
        "declared_block_count": block_count,
    }
    return generated_source, provisions, provision_bodies


def _formula_inputs(
    document: Mapping[str, Any], module_id: str
) -> list[dict[str, Any]]:
    rules = document.get("rules")
    if not isinstance(rules, list):
        rules = []
    local_names = {
        row.get("name")
        for row in rules
        if isinstance(row, Mapping) and isinstance(row.get("name"), str)
    }
    imports = document.get("imports")
    imported_names = {
        value.rsplit("#", 1)[-1]
        for value in imports or []
        if isinstance(value, str) and "#" in value
    }
    readers: dict[str, set[str]] = {}
    for rule in rules:
        if not isinstance(rule, Mapping) or not isinstance(rule.get("name"), str):
            continue
        rule_name = rule["name"]
        versions = rule.get("versions")
        if not isinstance(versions, list):
            continue
        for version in versions:
            if not isinstance(version, Mapping):
                continue
            formula = version.get("formula")
            if not isinstance(formula, str):
                continue
            for match in _IDENTIFIER.finditer(formula):
                name = match.group()
                if name in local_names or name in imported_names:
                    continue
                if name.lower() in _RESERVED_FORMULA_WORDS:
                    continue
                # RuleSpec built-ins are call-shaped.  Inputs are bare symbols,
                # so excluding calls avoids a hand-maintained function catalog.
                if formula[match.end() :].lstrip().startswith("("):
                    continue
                readers.setdefault(name, set()).add(rule_name)
    return [
        {
            "slot": f"{module_id}#input.{name}",
            "name": name,
            "module": module_id,
            "read_by": sorted(rule_names),
        }
        for name, rule_names in sorted(readers.items())
    ]


def _provision_proof_atoms(
    document: Mapping[str, Any],
    *,
    label: str,
    proof_validation_required: bool,
    provision_bodies: Mapping[str, str] | None,
) -> list[dict[str, Any]]:
    """Return proof atoms that cite a direct provision in this corpus spine."""

    rules = document.get("rules")
    if not isinstance(rules, list):
        return []
    result: list[dict[str, Any]] = []
    for rule_index, rule in enumerate(rules):
        if not isinstance(rule, Mapping):
            continue
        rule_name = rule.get("name")
        metadata = rule.get("metadata")
        proof = metadata.get("proof") if isinstance(metadata, Mapping) else None
        atoms = proof.get("atoms") if isinstance(proof, Mapping) else None
        if atoms is None:
            continue
        if not isinstance(atoms, list):
            raise _SourceError(
                f"{label}: rules[{rule_index}].metadata.proof.atoms must be a list"
            )
        for atom_index, atom in enumerate(atoms):
            if not isinstance(atom, Mapping):
                raise _SourceError(
                    f"{label}: rules[{rule_index}] proof atom {atom_index} "
                    "must be a mapping"
                )
            source = atom.get("source")
            citation = (
                source.get("corpus_citation_path")
                if isinstance(source, Mapping)
                else None
            )
            # A corpus-root atom supports a composition as a whole. Only atoms
            # naming a direct provision can establish atom-level partial
            # encoding of one ledger row.
            if not isinstance(citation, str) or not citation.startswith(
                f"{CORPUS_ROOT}/"
            ):
                continue
            if not proof_validation_required:
                raise _SourceError(
                    f"{label}: corpus-root composed proof atoms require "
                    "module.proof_validation.required=true"
                )
            path = atom.get("path")
            kind = atom.get("kind")
            excerpt = source.get("excerpt")
            if not isinstance(rule_name, str) or not rule_name.strip():
                raise _SourceError(
                    f"{label}: rules[{rule_index}] with a provision proof atom "
                    "must have a name"
                )
            if not isinstance(path, str) or not path.strip():
                raise _SourceError(
                    f"{label}: rules[{rule_index}] proof atom {atom_index} "
                    "must have a path"
                )
            path_match = _FORMULA_PROOF_PATH.fullmatch(path)
            versions = rule.get("versions")
            if path_match is None or not isinstance(versions, list):
                raise _SourceError(
                    f"{label}: rules[{rule_index}] proof atom {atom_index} path "
                    f"{path!r} does not resolve to a version formula"
                )
            version_index = int(path_match.group(1))
            if version_index >= len(versions):
                raise _SourceError(
                    f"{label}: rules[{rule_index}] proof atom {atom_index} path "
                    f"{path!r} does not resolve to a version formula"
                )
            version = versions[version_index]
            formula = version.get("formula") if isinstance(version, Mapping) else None
            if not isinstance(formula, str) or not formula.strip():
                raise _SourceError(
                    f"{label}: rules[{rule_index}] proof atom {atom_index} path "
                    f"{path!r} does not resolve to a version formula"
                )
            if not isinstance(kind, str) or not kind.strip():
                raise _SourceError(
                    f"{label}: rules[{rule_index}] proof atom {atom_index} "
                    "must have a kind"
                )
            if not isinstance(excerpt, str) or not excerpt.strip():
                raise _SourceError(
                    f"{label}: rules[{rule_index}] proof atom {atom_index} "
                    "must have a source excerpt"
                )
            provision_body = (
                provision_bodies.get(citation)
                if isinstance(provision_bodies, Mapping)
                else None
            )
            if not isinstance(provision_body, str):
                raise _SourceError(
                    f"{label}: proof atom citation {citation!r} has no pinned "
                    "corpus provision body"
                )
            if excerpt not in provision_body:
                raise _SourceError(
                    f"{label}: rules[{rule_index}] proof atom {atom_index} excerpt "
                    f"does not occur in pinned corpus provision {citation}"
                )
            result.append(
                {
                    "rule": rule_name,
                    "path": path,
                    "kind": kind,
                    "corpus_citation_path": citation,
                    "excerpt_sha256": _sha256_bytes(excerpt.encode()),
                    "formula_sha256": _sha256_bytes(formula.encode()),
                }
            )
    result.sort(key=lambda row: tuple(row[field] for field in _PROOF_ATOM_FIELDS))
    keys = [tuple(row[field] for field in _PROOF_ATOM_FIELDS) for row in result]
    if len(keys) != len(set(keys)):
        raise _SourceError(f"{label}: duplicate provision proof atoms")
    return result


def _read_rulespec_facts(
    root: Path,
    ref: str,
    *,
    provision_bodies: Mapping[str, str] | None = None,
) -> tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]]]:
    if not root.is_dir():
        raise _SourceError(f"rulespec checkout is missing: {root}")
    commit = _rulespec_commit(root, ref)
    modules: list[dict[str, Any]] = []
    module_inputs: list[dict[str, Any]] = []
    content_digest = hashlib.sha256()

    # Resolve the moving ref once, then enumerate and read every blob through
    # that immutable commit.  A concurrent main update cannot mix trees.
    for path in _rulespec_paths(root, commit):
        blob = _rulespec_blob(root, commit, path)
        document = _load_yaml_bytes(blob, label=f"{commit}:{path}")
        if not isinstance(document, Mapping) or document.get("format") != "rulespec/v1":
            continue
        module = document.get("module")
        if not isinstance(module, Mapping):
            continue
        verification = module.get("source_verification")
        source_citation = (
            verification.get("corpus_citation_path")
            if isinstance(verification, Mapping)
            else None
        )
        if not isinstance(source_citation, str) or not (
            source_citation == CORPUS_ROOT
            or source_citation.startswith(f"{CORPUS_ROOT}/")
        ):
            continue

        rules = document.get("rules")
        rule_count = len(rules) if isinstance(rules, list) else 0
        summary = module.get("summary")
        if not isinstance(summary, str) or not summary.strip():
            raise _SourceError(f"{ref}:{path}: selected module has no summary")
        module_status = module.get("status")
        if module_status is not None and (
            not isinstance(module_status, str) or not module_status.strip()
        ):
            raise _SourceError(f"{ref}:{path}: malformed module status")
        if module_status not in (None, "entity_not_supported"):
            raise _SourceError(
                f"{ref}:{path}: unsupported module status {module_status!r}; "
                "only entity_not_supported is a closure classification"
            )
        source_sha256 = (
            verification.get("source_sha256")
            if isinstance(verification, Mapping)
            else None
        )
        if source_citation != CORPUS_ROOT and not _HEX_SHA256.fullmatch(
            str(source_sha256 or "")
        ):
            raise _SourceError(
                f"{ref}:{path}: direct provision modules require a full "
                "module.source_verification.source_sha256"
            )
        module_id = _module_id(path)
        entry = {
            "path": path,
            "module_id": module_id,
            "sha256": _sha256_bytes(blob),
            "source_citation_path": source_citation,
            "rule_count": rule_count,
            "summary": summary.strip(),
        }
        if source_citation != CORPUS_ROOT:
            entry["source_sha256"] = source_sha256
        else:
            proof_validation = module.get("proof_validation")
            proof_validation_required = (
                isinstance(proof_validation, Mapping)
                and proof_validation.get("required") is True
            )
            entry["proof_validation_required"] = proof_validation_required
            entry["proof_atoms"] = _provision_proof_atoms(
                document,
                label=f"{commit}:{path}",
                proof_validation_required=proof_validation_required,
                provision_bodies=provision_bodies,
            )
        if module_status is not None:
            entry["status"] = module_status
        modules.append(entry)
        module_inputs.extend(_formula_inputs(document, module_id))
        content_digest.update(path.encode())
        content_digest.update(b"\0")
        content_digest.update(blob)
        content_digest.update(b"\0")

    modules.sort(key=lambda row: row["path"])
    module_inputs.sort(key=lambda row: row["slot"])
    if not modules:
        raise _SourceError(
            f"rulespec {ref!r} contains no tracked modules rooted at {CORPUS_ROOT}"
        )
    rulespec = {
        "repository": "TheAxiomFoundation/rulespec-dk",
        # Record the RESOLVED commit as the ref, never a branch name: a ledger
        # is a statement about one commit, and --check re-derives at that
        # commit whatever branch tips have moved to (the executable receipt
        # made the same move for launch-audit finding #6).
        "ref": commit,
        "commit": commit,
        "selected_content_sha256": content_digest.hexdigest(),
    }
    return rulespec, modules, module_inputs


_INSTRUMENT_ROW_KEYS = (
    "eli",
    "relation",
    "title",
    "title_short",
    "type_document",
    "in_force",
    "date_document",
)


# Semantic hash of the embedded graph: recomputable from the artifact
# alone, so hermetic validation binds the rows to the recorded sha (a
# graph edit with a stale sha is an error, not silent drift).
def _instrument_graph_sha(
    act_eli: Any,
    retrieved_at: Any,
    instruments: Sequence[Mapping[str, Any]],
) -> str:
    canonical = json.dumps(
        {
            "act_eli": act_eli,
            "retrieved_at": retrieved_at,
            "instruments": [
                {key: row.get(key) for key in _INSTRUMENT_ROW_KEYS}
                for row in instruments
            ],
        },
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return _sha256_bytes(canonical.encode())


def _read_instrument_graph(path: Path = INSTRUMENT_GRAPH_PATH) -> dict[str, Any]:
    """Load the committed subordinate-instrument snapshot (hermetic).

    The snapshot is captured by ``scripts/refresh_instrument_graph.py`` (the
    only network-using step); this reader binds its exact bytes into the
    generated facts, so any edit to the snapshot fails ``--check`` as drift.
    """

    try:
        data = path.read_bytes()
    except OSError as exc:
        raise _SourceError(f"could not read instrument graph {path}: {exc}") from exc
    try:
        snapshot = json.loads(data)
    except json.JSONDecodeError as exc:
        raise _SourceError(f"instrument graph is not valid JSON: {exc}") from exc
    if not isinstance(snapshot, Mapping):
        raise _SourceError("instrument graph must be a JSON object")
    if snapshot.get("schema") != INSTRUMENT_GRAPH_SCHEMA:
        raise _SourceError(f"instrument graph schema must be {INSTRUMENT_GRAPH_SCHEMA}")
    instruments = snapshot.get("instruments")
    if not isinstance(instruments, list) or not instruments:
        raise _SourceError("instrument graph must list at least one instrument")
    rows: list[dict[str, Any]] = []
    for index, raw in enumerate(instruments):
        if not isinstance(raw, Mapping) or set(raw) != set(_INSTRUMENT_ROW_KEYS):
            raise _SourceError(f"instrument graph row {index} has unexpected keys")
        rows.append({key: raw[key] for key in _INSTRUMENT_ROW_KEYS})
    try:
        snapshot_path = str(path.relative_to(REPO_ROOT))
    except ValueError:
        # Hermetic fixtures pass a temp path outside the repository; record
        # its basename so the artifact stays machine-independent.
        snapshot_path = path.name
    return {
        "snapshot_path": snapshot_path,
        "snapshot_sha256": _instrument_graph_sha(
            snapshot.get("act_eli"), snapshot.get("retrieved_at"), rows
        ),
        "act_eli": snapshot.get("act_eli"),
        "retrieved_at": snapshot.get("retrieved_at"),
        "instruments": rows,
    }


def _empty_decisions() -> dict[str, list[Any]]:
    return {
        "provisions": [],
        "input_grounding": [],
        "instrument_dispositions": [],
        "supplemental_instruments": [],
    }


def _load_decisions(path: Path) -> dict[str, Any]:
    if not path.exists():
        return _empty_decisions()
    try:
        document = yaml.safe_load(path.read_text())
    except (OSError, yaml.YAMLError) as exc:
        raise _SourceError(
            f"could not read committed decisions from {path}: {exc}"
        ) from exc
    if not isinstance(document, Mapping):
        raise _SourceError(f"closure artifact is not a YAML mapping: {path}")
    decisions = document.get("committed_decisions")
    if decisions is None:
        return _empty_decisions()
    if not isinstance(decisions, Mapping):
        raise _SourceError("committed_decisions must be a mapping")
    return dict(decisions)


def _canonical_instrument_rows(
    raw_rows: Any,
    *,
    section: str,
    graph_elis: set[str],
    supplemental: bool,
    errors: list[str],
) -> list[dict[str, Any]]:
    if not isinstance(raw_rows, list):
        errors.append(f"committed_decisions.{section} must be a list")
        raw_rows = []
    rows: list[dict[str, Any]] = []
    seen: set[str] = set()
    for index, decision in enumerate(raw_rows):
        label = f"committed_decisions.{section}[{index}]"
        if not isinstance(decision, Mapping):
            errors.append(f"{label} must be a mapping")
            continue
        eli = decision.get("eli")
        if not isinstance(eli, str) or not eli.startswith(
            "https://retsinformation.dk/eli/"
        ):
            errors.append(f"{label}.eli must be a retsinformation ELI URI")
            continue
        if eli in seen:
            errors.append(f"duplicate instrument disposition: {eli}")
            continue
        seen.add(eli)
        if supplemental:
            if eli in graph_elis:
                errors.append(
                    f"{label}: {eli} is already in the derived instrument graph"
                )
        elif eli not in graph_elis:
            errors.append(f"{label}: {eli} is not in the derived instrument graph")
        status = decision.get("status")
        classification = decision.get("classification")
        reason = decision.get("reason")
        if status not in INSTRUMENT_STATUSES:
            errors.append(f"{label}.status must be one of {INSTRUMENT_STATUSES}")
        row: dict[str, Any] = {"eli": eli, "status": status}
        if supplemental:
            title_short = decision.get("title_short")
            provenance = decision.get("provenance")
            if not isinstance(title_short, str) or not title_short.strip():
                errors.append(f"{label}.title_short must be non-empty")
            if not isinstance(provenance, str) or not provenance.strip():
                errors.append(
                    f"{label}.provenance must record how the instrument was found"
                )
            row["title_short"] = title_short
            row["relation"] = SUPPLEMENTAL_RELATION
            row["provenance"] = (
                provenance.strip() if isinstance(provenance, str) else provenance
            )
        if status != "pending":
            if not isinstance(classification, str) or not classification.strip():
                errors.append(f"{label}.classification must be non-empty")
            if not isinstance(reason, str) or not reason.strip():
                errors.append(f"{label}.reason must be non-empty")
            row["classification"] = classification
            row["reason"] = reason.strip() if isinstance(reason, str) else reason
            bears = decision.get("bears_on_computed_surface")
            if status in ("classified-with-reason", "excluded-with-reason"):
                if not isinstance(bears, bool):
                    errors.append(
                        f"{label}.bears_on_computed_surface must be true or "
                        "false: does this instrument bear on any computed "
                        "output (an open dependency until encoded), or not"
                    )
                else:
                    row["bears_on_computed_surface"] = bears
            elif bears is not None:
                errors.append(
                    f"{label}.bears_on_computed_surface is only valid for "
                    "classified or excluded instruments"
                )
        elif classification is not None or reason is not None:
            errors.append(f"{label}: pending rows carry no classification or reason")
        if status == "encoded":
            encoded_by = decision.get("encoded_by")
            if not isinstance(encoded_by, str) or not encoded_by.strip():
                errors.append(f"{label}.encoded_by must name the encoding module")
            row["encoded_by"] = encoded_by
        elif decision.get("encoded_by") is not None:
            errors.append(f"{label}.encoded_by is only valid for encoded instruments")
        bearing = decision.get("bearing")
        if bearing is not None:
            if not isinstance(bearing, str) or not bearing.strip():
                errors.append(f"{label}.bearing must be a non-empty string when given")
            else:
                row["bearing"] = bearing.strip()
        known = {
            "eli",
            "status",
            "classification",
            "reason",
            "bearing",
            "encoded_by",
            "bears_on_computed_surface",
        }
        if supplemental:
            known |= {"title_short", "provenance", "relation"}
        unknown = set(decision) - known
        if unknown:
            errors.append(f"{label} has unexpected keys: {sorted(unknown)}")
        rows.append(row)
    if not supplemental:
        missing = sorted(graph_elis - seen)
        if missing:
            errors.append(
                "instruments missing committed dispositions: " + ", ".join(missing)
            )
    rows.sort(key=lambda row: row["eli"])
    return rows


def _canonical_decisions(
    raw: Any,
    *,
    provision_order: Mapping[str, int],
    input_names: set[str],
    instrument_elis: set[str],
    errors: list[str],
) -> dict[str, Any]:
    if not isinstance(raw, Mapping):
        errors.append("committed_decisions must be a mapping")
        raw = {}

    raw_provisions = raw.get("provisions", [])
    if not isinstance(raw_provisions, list):
        errors.append("committed_decisions.provisions must be a list")
        raw_provisions = []
    provisions: list[dict[str, Any]] = []
    seen_provisions: set[str] = set()
    for index, decision in enumerate(raw_provisions):
        label = f"committed_decisions.provisions[{index}]"
        if not isinstance(decision, Mapping):
            errors.append(f"{label} must be a mapping")
            continue
        citation = decision.get("citation_path")
        if not isinstance(citation, str) or citation not in provision_order:
            errors.append(f"{label}.citation_path is not in the generated spine")
            continue
        if citation in seen_provisions:
            errors.append(f"duplicate provision decision: {citation}")
            continue
        seen_provisions.add(citation)
        status = decision.get("status")
        classification = decision.get("classification")
        reason = decision.get("reason")
        if status != "excluded-with-reason":
            errors.append(f"{label}.status must be excluded-with-reason")
        if not isinstance(classification, str) or not classification.strip():
            errors.append(f"{label}.classification must be non-empty")
        if not isinstance(reason, str) or not reason.strip():
            errors.append(f"{label}.reason must be non-empty")
        provisions.append(
            {
                "citation_path": citation,
                "status": status,
                "classification": classification,
                "reason": reason.strip() if isinstance(reason, str) else reason,
            }
        )
    provisions.sort(key=lambda row: provision_order[row["citation_path"]])

    raw_grounding = raw.get("input_grounding", [])
    if not isinstance(raw_grounding, list):
        errors.append("committed_decisions.input_grounding must be a list")
        raw_grounding = []
    grounding: list[dict[str, Any]] = []
    seen_inputs: set[str] = set()
    for index, decision in enumerate(raw_grounding):
        label = f"committed_decisions.input_grounding[{index}]"
        if not isinstance(decision, Mapping):
            errors.append(f"{label} must be a mapping")
            continue
        name = decision.get("name")
        if not isinstance(name, str) or name not in input_names:
            errors.append(f"{label}.name is not a parsed module input")
            continue
        if name in seen_inputs:
            errors.append(f"duplicate input-grounding decision: {name}")
            continue
        seen_inputs.add(name)
        disposition = decision.get("grounding")
        reason = decision.get("reason")
        scope = decision.get("uncaptured_scope")
        if disposition not in GROUNDINGS:
            errors.append(f"{label}.grounding must be one of {GROUNDINGS}")
        if not isinstance(reason, str) or not reason.strip():
            errors.append(f"{label}.reason must be non-empty")
        if disposition == "uncaptured":
            if not isinstance(scope, str) or not scope.strip():
                errors.append(f"{label}.uncaptured_scope must be non-empty")
        elif scope is not None:
            errors.append(
                f"{label}.uncaptured_scope is only valid for uncaptured inputs"
            )
        leaf_kind = decision.get("leaf_kind")
        if leaf_kind not in LEAF_KINDS:
            errors.append(f"{label}.leaf_kind must be one of {LEAF_KINDS}")
        derivation = decision.get("derivation_instrument")
        if leaf_kind == "law_derived":
            if not isinstance(derivation, str) or not derivation.strip():
                errors.append(
                    f"{label}.derivation_instrument must name the legal rule "
                    "that defines this quantity"
                )
        elif derivation is not None:
            errors.append(
                f"{label}.derivation_instrument is only valid for law_derived leaves"
            )
        row = {
            "name": name,
            "grounding": disposition,
            "leaf_kind": leaf_kind,
            "reason": reason.strip() if isinstance(reason, str) else reason,
        }
        if leaf_kind == "law_derived" and isinstance(derivation, str):
            row["derivation_instrument"] = derivation.strip()
        if disposition == "uncaptured":
            row["uncaptured_scope"] = scope.strip() if isinstance(scope, str) else scope
        grounding.append(row)
    grounding.sort(key=lambda row: row["name"])
    missing = sorted(input_names - seen_inputs)
    if missing:
        errors.append(
            "module inputs missing committed grounding decisions: " + ", ".join(missing)
        )
    extra = sorted(seen_inputs - input_names)
    if extra:
        errors.append(
            "committed grounding decisions have extra inputs: " + ", ".join(extra)
        )

    dispositions = _canonical_instrument_rows(
        raw.get("instrument_dispositions", []),
        section="instrument_dispositions",
        graph_elis=instrument_elis,
        supplemental=False,
        errors=errors,
    )
    supplemental = _canonical_instrument_rows(
        raw.get("supplemental_instruments", []),
        section="supplemental_instruments",
        graph_elis=instrument_elis,
        supplemental=True,
        errors=errors,
    )
    return {
        "provisions": provisions,
        "input_grounding": grounding,
        "instrument_dispositions": dispositions,
        "supplemental_instruments": supplemental,
    }


def _derive_computed(
    generated: Mapping[str, Any],
    decisions: Mapping[str, Any],
    errors: list[str],
) -> dict[str, Any]:
    spine = generated.get("provision_spine")
    modules = generated.get("rulespec_modules")
    module_inputs = generated.get("module_inputs")
    if not isinstance(spine, list):
        errors.append("generated_facts.provision_spine must be a list")
        spine = []
    if not isinstance(modules, list):
        errors.append("generated_facts.rulespec_modules must be a list")
        modules = []
    if not isinstance(module_inputs, list):
        errors.append("generated_facts.module_inputs must be a list")
        module_inputs = []

    provision_decisions = {
        row["citation_path"]: row
        for row in decisions.get("provisions", [])
        if isinstance(row, Mapping) and isinstance(row.get("citation_path"), str)
    }
    direct_modules: dict[str, Mapping[str, Any]] = {}
    atom_modules: dict[str, dict[str, int]] = {}
    for module in modules:
        if not isinstance(module, Mapping):
            continue
        citation = module.get("source_citation_path")
        if not isinstance(citation, str):
            continue
        if citation == CORPUS_ROOT:
            if module.get("proof_validation_required") is not True:
                continue
            module_path = module.get("path")
            if not isinstance(module_path, str):
                continue
            for atom in module.get("proof_atoms") or []:
                if not isinstance(atom, Mapping):
                    continue
                atom_citation = atom.get("corpus_citation_path")
                if isinstance(atom_citation, str):
                    by_module = atom_modules.setdefault(atom_citation, {})
                    by_module[module_path] = by_module.get(module_path, 0) + 1
            continue
        if citation in direct_modules:
            errors.append(f"multiple RuleSpec modules directly join {citation}")
            continue
        direct_modules[citation] = module

    ledger: list[dict[str, Any]] = []
    for provision in spine:
        if not isinstance(provision, Mapping):
            continue
        citation = provision.get("citation_path")
        if not isinstance(citation, str):
            continue
        row = {
            "ordinal": provision.get("ordinal"),
            "citation_path": citation,
            "heading": provision.get("heading"),
            "body_sha256": provision.get("body_sha256"),
        }
        module = direct_modules.get(citation)
        decision = provision_decisions.get(citation)
        if module is not None and decision is not None:
            errors.append(
                f"{citation}: committed exclusion overlaps a direct RuleSpec module"
            )
        if citation in atom_modules and decision is not None:
            errors.append(
                f"{citation}: committed exclusion hides composed-module proof atoms"
            )
        if module is not None and module.get("status") == "entity_not_supported":
            row.update(
                {
                    "status": "classified-with-reason",
                    "classification": module["status"],
                    "reason": module.get("summary"),
                    "classified_by": module.get("path"),
                }
            )
        elif (
            module is not None
            and isinstance(module.get("rule_count"), int)
            and module.get("rule_count") > 0
        ):
            row.update({"status": "encoded", "encoded_by": module.get("path")})
        elif citation in atom_modules:
            citing_modules = sorted(atom_modules[citation])
            row.update(
                {
                    "status": "partially-encoded",
                    "partially_encoded_by": citing_modules,
                    "proof_atom_count": sum(atom_modules[citation].values()),
                }
            )
        elif decision is not None:
            row.update(
                {
                    "status": "excluded-with-reason",
                    "classification": decision.get("classification"),
                    "reason": decision.get("reason"),
                }
            )
        else:
            row["status"] = "pending"
        ledger.append(row)

    counts = {status: 0 for status in STATUSES}
    for row in ledger:
        status = row.get("status")
        if status in counts:
            counts[status] += 1
    counts = {"total": len(ledger), **counts}
    partially_encoded = [
        row["citation_path"]
        for row in ledger
        if row.get("status") == "partially-encoded"
    ]
    pending = [row["citation_path"] for row in ledger if row.get("status") == "pending"]
    reasons_complete = all(
        row.get("status") == "encoded"
        or row.get("status") == "partially-encoded"
        or row.get("status") == "pending"
        or (isinstance(row.get("reason"), str) and bool(row["reason"].strip()))
        for row in ledger
    )

    slots_by_name: dict[str, list[str]] = {}
    for row in module_inputs:
        if not isinstance(row, Mapping):
            continue
        name = row.get("name")
        slot = row.get("slot")
        if isinstance(name, str) and isinstance(slot, str):
            slots_by_name.setdefault(name, []).append(slot)
    grounding_rows = decisions.get("input_grounding", [])
    grounding_by_name = {
        row["name"]: row
        for row in grounding_rows
        if isinstance(row, Mapping) and isinstance(row.get("name"), str)
    }
    frontier_complete = set(grounding_by_name) == set(slots_by_name)
    frontier: list[dict[str, Any]] = []
    for name in sorted(slots_by_name):
        decision = grounding_by_name.get(name)
        if decision is None:
            continue
        if decision.get("grounding") == "uncaptured":
            scope = decision.get("uncaptured_scope")
            if not isinstance(scope, str) or not scope.strip():
                frontier_complete = False
            frontier.append(
                {
                    "input": name,
                    "slots": sorted(slots_by_name[name]),
                    "uncaptured_scope": scope,
                    "reason": decision.get("reason"),
                }
            )
        elif decision.get("grounding") != "captured":
            frontier_complete = False

    graph = generated.get("instrument_graph")
    graph_rows = (
        graph.get("instruments") if isinstance(graph, Mapping) else None
    ) or []
    disposition_by_eli = {
        row["eli"]: row
        for row in decisions.get("instrument_dispositions", [])
        if isinstance(row, Mapping) and isinstance(row.get("eli"), str)
    }
    instrument_ledger: list[dict[str, Any]] = []
    for graph_row in graph_rows:
        if not isinstance(graph_row, Mapping):
            continue
        eli = graph_row.get("eli")
        if not isinstance(eli, str):
            continue
        row = {
            "eli": eli,
            "relation": graph_row.get("relation"),
            "title_short": graph_row.get("title_short"),
            "type_document": graph_row.get("type_document"),
            "in_force": graph_row.get("in_force"),
        }
        decision = disposition_by_eli.get(eli)
        if decision is None:
            row["status"] = "pending"
        else:
            row["status"] = decision.get("status")
            for key in (
                "classification",
                "reason",
                "bearing",
                "encoded_by",
                "bears_on_computed_surface",
            ):
                if decision.get(key) is not None:
                    row[key] = decision[key]
        instrument_ledger.append(row)
    for extra_row in decisions.get("supplemental_instruments", []):
        if not isinstance(extra_row, Mapping):
            continue
        row = {
            "eli": extra_row.get("eli"),
            "relation": SUPPLEMENTAL_RELATION,
            "title_short": extra_row.get("title_short"),
            "provenance": extra_row.get("provenance"),
            "status": extra_row.get("status"),
        }
        for key in (
                "classification",
                "reason",
                "bearing",
                "encoded_by",
                "bears_on_computed_surface",
            ):
            if extra_row.get(key) is not None:
                row[key] = extra_row[key]
        instrument_ledger.append(row)
    instrument_counts = {status: 0 for status in INSTRUMENT_STATUSES}
    for row in instrument_ledger:
        status = row.get("status")
        if status in instrument_counts:
            instrument_counts[status] += 1
    instrument_pending = [
        row["eli"] for row in instrument_ledger if row.get("status") == "pending"
    ]
    instrument_reasons_complete = all(
        row.get("status") == "pending"
        or (isinstance(row.get("reason"), str) and bool(row["reason"].strip()))
        for row in instrument_ledger
    )
    instrument_complete = (
        bool(graph_rows) and not instrument_pending and instrument_reasons_complete
    )

    law_derived_inputs = sorted(
        {
            row["name"]
            for row in grounding_rows
            if isinstance(row, Mapping)
            and row.get("leaf_kind") == "law_derived"
            and isinstance(row.get("name"), str)
            and row["name"] in slots_by_name
        }
    )
    instruments_bearing = sorted(
        {
            row["eli"]
            for row in instrument_ledger
            if row.get("status") in ("classified-with-reason", "excluded-with-reason")
            and row.get("bears_on_computed_surface") is True
            and isinstance(row.get("eli"), str)
        }
    )
    dependency_closed = not law_derived_inputs and not instruments_bearing

    computed = {
        "ledger": ledger,
        "provision_counts": counts,
        "partially_encoded": partially_encoded,
        "pending": pending,
        "boundary_frontier": {
            "parsed_input_count": len(slots_by_name),
            "uncaptured_input_count": len(frontier),
            "complete": frontier_complete,
            "inputs": frontier,
        },
        "instrument_frontier": {
            "instrument_count": len(graph_rows),
            "supplemental_count": len(decisions.get("supplemental_instruments", [])),
            "counts": {"total": len(instrument_ledger), **instrument_counts},
            "pending": instrument_pending,
            "complete": instrument_complete,
            "ledger": instrument_ledger,
        },
        "dependency_closure": {
            "law_derived_inputs": law_derived_inputs,
            "instruments_bearing_on_computed": instruments_bearing,
            "open_dependency_count": len(law_derived_inputs)
            + len(instruments_bearing),
            "closed": dependency_closed,
        },
        "non_encoded_reasons_complete": reasons_complete,
        "closed": (
            not pending
            and not partially_encoded
            and frontier_complete
            and reasons_complete
            and instrument_complete
            and dependency_closed
        ),
    }
    return computed


def _generated_fact_errors(generated: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(generated, Mapping):
        return ["generated_facts must be a mapping"]
    expected_keys = {
        "corpus_release",
        "rulespec",
        "provision_spine",
        "rulespec_modules",
        "module_inputs",
        "instrument_graph",
    }
    if set(generated) != expected_keys:
        errors.append(
            "generated_facts keys must be exactly: " + ", ".join(sorted(expected_keys))
        )

    graph = generated.get("instrument_graph")
    if not isinstance(graph, Mapping):
        errors.append("generated_facts.instrument_graph must be a mapping")
    else:
        if set(graph) != {
            "snapshot_path",
            "snapshot_sha256",
            "act_eli",
            "retrieved_at",
            "instruments",
        }:
            errors.append("instrument_graph has unexpected or missing keys")
        if not _HEX_SHA256.fullmatch(str(graph.get("snapshot_sha256", ""))):
            errors.append("instrument_graph.snapshot_sha256 must be a full sha256")
        else:
            embedded_rows = [
                row
                for row in (graph.get("instruments") or [])
                if isinstance(row, Mapping)
            ]
            expected_sha = _instrument_graph_sha(
                graph.get("act_eli"), graph.get("retrieved_at"), embedded_rows
            )
            if graph.get("snapshot_sha256") != expected_sha:
                errors.append(
                    "instrument_graph.snapshot_sha256 does not match the "
                    "embedded graph content (edited rows or stale sha)"
                )
        if graph.get("act_eli") != INSTRUMENT_ACT_ELI:
            errors.append(f"instrument_graph.act_eli must be {INSTRUMENT_ACT_ELI}")
        retrieved = graph.get("retrieved_at")
        if not isinstance(retrieved, str) or not re.fullmatch(
            r"\d{4}-\d{2}-\d{2}", retrieved
        ):
            errors.append("instrument_graph.retrieved_at must be an ISO date")
        graph_rows = graph.get("instruments")
        if not isinstance(graph_rows, list) or not graph_rows:
            errors.append("instrument_graph.instruments must be a non-empty list")
            graph_rows = []
        graph_elis: list[str] = []
        for index, row in enumerate(graph_rows):
            if not isinstance(row, Mapping):
                errors.append(f"instrument_graph.instruments[{index}] must be a mapping")
                continue
            if set(row) != set(_INSTRUMENT_ROW_KEYS):
                errors.append(
                    f"instrument_graph.instruments[{index}] has unexpected keys"
                )
            eli = row.get("eli")
            graph_elis.append(eli if isinstance(eli, str) else "")
            if not isinstance(eli, str) or not eli.startswith(
                "https://retsinformation.dk/eli/"
            ):
                errors.append(
                    f"instrument_graph.instruments[{index}].eli must be an ELI URI"
                )
            if row.get("relation") not in INSTRUMENT_RELATIONS:
                errors.append(
                    f"instrument_graph.instruments[{index}].relation must be one of "
                    + ", ".join(INSTRUMENT_RELATIONS)
                )
            if not isinstance(row.get("in_force"), bool):
                errors.append(
                    f"instrument_graph.instruments[{index}].in_force must be a bool"
                )
        if len(graph_elis) != len(set(graph_elis)):
            errors.append("instrument_graph.instruments has duplicate ELIs")

    corpus = generated.get("corpus_release")
    if not isinstance(corpus, Mapping):
        errors.append("generated_facts.corpus_release must be a mapping")
    else:
        corpus_keys = {
            "repository",
            "ref",
            "commit",
            "path",
            "sha256",
            "version",
            "source_id",
            "source_as_of",
            "citation_root",
            "declared_block_count",
        }
        if set(corpus) != corpus_keys:
            errors.append("corpus_release has unexpected or missing provenance keys")
        if corpus.get("repository") != "TheAxiomFoundation/axiom-corpus":
            errors.append(
                "corpus_release.repository must identify TheAxiomFoundation/axiom-corpus"
            )
        if not isinstance(corpus.get("ref"), str) or not corpus["ref"].strip():
            errors.append("corpus_release.ref must be non-empty")
        elif corpus.get("ref") != corpus.get("commit"):
            errors.append(
                "corpus_release.ref must equal corpus_release.commit (a resolved "
                "sha, never a branch name)"
            )
        # isinstance first: `str(...)` would let a 40-DIGIT YAML integer
        # (a legal, silently-typed scalar) pass as a "sha" (delta-audit #7).
        if not isinstance(corpus.get("commit"), str) or not _HEX_GIT_SHA.fullmatch(
            corpus["commit"]
        ):
            errors.append("corpus_release.commit must be a full git commit SHA")
        if not isinstance(corpus.get("path"), str) or not corpus["path"].endswith(
            ".jsonl"
        ):
            errors.append("corpus_release.path must identify a JSONL file")
        if corpus.get("citation_root") != CORPUS_ROOT:
            errors.append(
                "corpus_release.citation_root is not the declared program root"
            )
        if not _HEX_SHA256.fullmatch(str(corpus.get("sha256", ""))):
            errors.append("corpus_release.sha256 must be a full sha256")

    rulespec = generated.get("rulespec")
    if not isinstance(rulespec, Mapping):
        errors.append("generated_facts.rulespec must be a mapping")
    else:
        if rulespec.get("repository") != "TheAxiomFoundation/rulespec-dk":
            errors.append(
                "rulespec.repository must identify TheAxiomFoundation/rulespec-dk"
            )
        if not isinstance(rulespec.get("commit"), str) or not _HEX_GIT_SHA.fullmatch(
            rulespec["commit"]
        ):
            errors.append("rulespec.commit must be a full git commit SHA string")
        if rulespec.get("ref") != rulespec.get("commit"):
            errors.append(
                "rulespec.ref must equal rulespec.commit (a resolved sha, never a "
                "branch name)"
            )
        if not _HEX_SHA256.fullmatch(str(rulespec.get("selected_content_sha256", ""))):
            errors.append("rulespec.selected_content_sha256 must be a full sha256")

    spine = generated.get("provision_spine")
    if not isinstance(spine, list) or not spine:
        errors.append("generated_facts.provision_spine must be a non-empty list")
        spine = []
    spine_citations: list[str] = []
    for index, row in enumerate(spine):
        if not isinstance(row, Mapping):
            errors.append(f"provision_spine[{index}] must be a mapping")
            continue
        citation = row.get("citation_path")
        spine_citations.append(citation if isinstance(citation, str) else "")
        if set(row) != {"ordinal", "citation_path", "heading", "body_sha256"}:
            errors.append(f"provision_spine[{index}] has unexpected keys")
        if row.get("ordinal") != index + 1:
            errors.append(f"provision_spine[{index}] has a non-contiguous ordinal")
        if not isinstance(citation, str) or not citation.startswith(f"{CORPUS_ROOT}/"):
            errors.append(f"provision_spine[{index}] has an invalid citation_path")
        if not isinstance(row.get("heading"), str) or not row["heading"].strip():
            errors.append(f"provision_spine[{index}] has an invalid heading")
        if not _HEX_SHA256.fullmatch(str(row.get("body_sha256", ""))):
            errors.append(f"provision_spine[{index}] has an invalid body_sha256")
    if len(spine_citations) != len(set(spine_citations)):
        errors.append("generated provision spine has duplicate citation paths")
    if isinstance(corpus, Mapping) and corpus.get("declared_block_count") != len(spine):
        errors.append("generated provision spine disagrees with declared_block_count")
    spine_body_hashes = {
        row["citation_path"]: row["body_sha256"]
        for row in spine
        if isinstance(row, Mapping)
        and isinstance(row.get("citation_path"), str)
        and isinstance(row.get("body_sha256"), str)
    }

    modules = generated.get("rulespec_modules")
    if not isinstance(modules, list) or not modules:
        errors.append("generated_facts.rulespec_modules must be a non-empty list")
        modules = []
    module_ids: set[str] = set()
    module_paths: set[str] = set()
    for index, row in enumerate(modules):
        if not isinstance(row, Mapping):
            errors.append(f"rulespec_modules[{index}] must be a mapping")
            continue
        module_id = row.get("module_id")
        path = row.get("path")
        required = {
            "path",
            "module_id",
            "sha256",
            "source_citation_path",
            "rule_count",
            "summary",
        }
        direct = row.get("source_citation_path") != CORPUS_ROOT
        if direct:
            required.add("source_sha256")
        else:
            required.add("proof_atoms")
            required.add("proof_validation_required")
        if set(row) not in (required, required | {"status"}):
            errors.append(f"rulespec_modules[{index}] has unexpected keys")
        if not isinstance(path, str) or not path.endswith(".yaml"):
            errors.append(f"rulespec_modules[{index}] has an invalid path")
        elif path in module_paths:
            errors.append(f"duplicate RuleSpec module path: {path}")
        else:
            module_paths.add(path)
        if not isinstance(module_id, str) or not module_id.startswith("dk:statutes/"):
            errors.append(f"rulespec_modules[{index}] has an invalid module_id")
        elif module_id in module_ids:
            errors.append(f"duplicate RuleSpec module id: {module_id}")
        else:
            module_ids.add(module_id)
        if not _HEX_SHA256.fullmatch(str(row.get("sha256", ""))):
            errors.append(f"rulespec_modules[{index}] has an invalid sha256")
        citation = row.get("source_citation_path")
        if not isinstance(citation, str) or not (
            citation == CORPUS_ROOT or citation.startswith(f"{CORPUS_ROOT}/")
        ):
            errors.append(f"rulespec_modules[{index}] is outside the corpus root")
        if (
            isinstance(citation, str)
            and citation != CORPUS_ROOT
            and citation not in spine_citations
        ):
            errors.append(
                f"rulespec_modules[{index}] cites a provision outside the spine"
            )
        if direct and not _HEX_SHA256.fullmatch(str(row.get("source_sha256", ""))):
            errors.append(
                f"rulespec_modules[{index}] direct module has an invalid source_sha256"
            )
        if direct and row.get("source_sha256") != spine_body_hashes.get(citation):
            errors.append(
                f"rulespec_modules[{index}] source_sha256 does not match the "
                "corpus provision body_sha256"
            )
        if row.get("status") not in (None, "entity_not_supported"):
            errors.append(
                f"rulespec_modules[{index}] has unsupported status {row.get('status')!r}"
            )
        if (
            isinstance(row.get("rule_count"), bool)
            or not isinstance(row.get("rule_count"), int)
            or row["rule_count"] < 0
        ):
            errors.append(f"rulespec_modules[{index}] has an invalid rule_count")
        if not isinstance(row.get("summary"), str) or not row["summary"].strip():
            errors.append(f"rulespec_modules[{index}] has an invalid summary")
        proof_atoms = row.get("proof_atoms")
        if not direct:
            proof_validation_required = row.get("proof_validation_required")
            if not isinstance(proof_validation_required, bool):
                errors.append(
                    f"rulespec_modules[{index}].proof_validation_required "
                    "must be a boolean"
                )
            if not isinstance(proof_atoms, list):
                errors.append(f"rulespec_modules[{index}].proof_atoms must be a list")
                proof_atoms = []
            expected_atom_keys = {
                "rule",
                "path",
                "kind",
                "corpus_citation_path",
                "excerpt_sha256",
                "formula_sha256",
            }
            for atom_index, atom in enumerate(proof_atoms):
                label = f"rulespec_modules[{index}].proof_atoms[{atom_index}]"
                if not isinstance(atom, Mapping):
                    errors.append(f"{label} must be a mapping")
                    continue
                if set(atom) != expected_atom_keys:
                    errors.append(f"{label} has unexpected keys")
                for field in ("rule", "path", "kind"):
                    if not isinstance(atom.get(field), str) or not atom[field].strip():
                        errors.append(f"{label}.{field} must be non-empty")
                atom_citation = atom.get("corpus_citation_path")
                if atom_citation not in spine_citations:
                    errors.append(f"{label} cites a provision outside the spine")
                if not _HEX_SHA256.fullmatch(str(atom.get("excerpt_sha256", ""))):
                    errors.append(f"{label}.excerpt_sha256 must be a full sha256")
                if not _HEX_SHA256.fullmatch(str(atom.get("formula_sha256", ""))):
                    errors.append(f"{label}.formula_sha256 must be a full sha256")
            if proof_atoms and proof_validation_required is not True:
                errors.append(
                    f"rulespec_modules[{index}] proof atoms require "
                    "proof_validation_required=true"
                )
            if all(isinstance(atom, Mapping) for atom in proof_atoms):
                atom_keys = [
                    tuple(str(atom.get(field, "")) for field in _PROOF_ATOM_FIELDS)
                    for atom in proof_atoms
                ]
                if atom_keys != sorted(atom_keys):
                    errors.append(
                        f"rulespec_modules[{index}].proof_atoms are not canonical"
                    )
                if len(atom_keys) != len(set(atom_keys)):
                    errors.append(
                        f"rulespec_modules[{index}].proof_atoms contain duplicates"
                    )

    module_inputs = generated.get("module_inputs")
    if not isinstance(module_inputs, list) or not module_inputs:
        errors.append("generated_facts.module_inputs must be a non-empty list")
        module_inputs = []
    slots: set[str] = set()
    for index, row in enumerate(module_inputs):
        if not isinstance(row, Mapping):
            errors.append(f"module_inputs[{index}] must be a mapping")
            continue
        if set(row) != {"slot", "name", "module", "read_by"}:
            errors.append(f"module_inputs[{index}] has unexpected keys")
        slot = row.get("slot")
        name = row.get("name")
        module = row.get("module")
        if not isinstance(slot, str) or slot != f"{module}#input.{name}":
            errors.append(f"module_inputs[{index}] has an invalid #input slot")
        elif slot in slots:
            errors.append(f"duplicate module input slot: {slot}")
        else:
            slots.add(slot)
        if module not in module_ids:
            errors.append(f"module_inputs[{index}] references an unknown module")
        readers = row.get("read_by")
        if (
            not isinstance(readers, list)
            or not readers
            or not all(isinstance(value, str) and value for value in readers)
        ):
            errors.append(f"module_inputs[{index}].read_by must be non-empty")
    return errors


def _validation_errors(document: Any) -> list[str]:
    if not isinstance(document, Mapping):
        return ["closure artifact must be a mapping"]
    errors: list[str] = []
    if document.get("schema") != SCHEMA:
        errors.append(f"schema must be {SCHEMA}")
    program = document.get("program")
    if not isinstance(program, Mapping):
        errors.append("program must be a mapping")
    else:
        if program.get("id") != PROGRAM_ID:
            errors.append(f"program.id must be {PROGRAM_ID}")
        if program.get("corpus_root") != CORPUS_ROOT:
            errors.append(f"program.corpus_root must be {CORPUS_ROOT}")

    generated = document.get("generated_facts")
    errors.extend(_generated_fact_errors(generated))
    if not isinstance(generated, Mapping):
        return errors
    spine = generated.get("provision_spine")
    module_inputs = generated.get("module_inputs")
    provision_order = {
        row["citation_path"]: index
        for index, row in enumerate(spine or [])
        if isinstance(row, Mapping) and isinstance(row.get("citation_path"), str)
    }
    input_names = {
        row["name"]
        for row in module_inputs or []
        if isinstance(row, Mapping) and isinstance(row.get("name"), str)
    }
    graph = generated.get("instrument_graph")
    instrument_elis = {
        row["eli"]
        for row in ((graph.get("instruments") if isinstance(graph, Mapping) else None) or [])
        if isinstance(row, Mapping) and isinstance(row.get("eli"), str)
    }
    decision_errors: list[str] = []
    decisions = _canonical_decisions(
        document.get("committed_decisions"),
        provision_order=provision_order,
        input_names=input_names,
        instrument_elis=instrument_elis,
        errors=decision_errors,
    )
    errors.extend(decision_errors)
    if document.get("committed_decisions") != decisions:
        errors.append("committed_decisions are not canonical")

    derive_errors: list[str] = []
    expected_computed = _derive_computed(generated, decisions, derive_errors)
    errors.extend(derive_errors)
    committed_computed = document.get("computed")
    if committed_computed != expected_computed:
        expected_ledger = {
            row["citation_path"]: row.get("status")
            for row in expected_computed["ledger"]
        }
        actual_ledger = {
            row.get("citation_path"): row.get("status")
            for row in (
                committed_computed.get("ledger", [])
                if isinstance(committed_computed, Mapping)
                else []
            )
            if isinstance(row, Mapping)
        }
        if actual_ledger != expected_ledger:
            errors.append(
                "computed ledger does not cover the generated spine/status join"
            )
        expected_frontier = {
            row["input"] for row in expected_computed["boundary_frontier"]["inputs"]
        }
        actual_frontier = {
            row.get("input")
            for row in (
                committed_computed.get("boundary_frontier", {}).get("inputs", [])
                if isinstance(committed_computed, Mapping)
                and isinstance(committed_computed.get("boundary_frontier"), Mapping)
                else []
            )
            if isinstance(row, Mapping)
        }
        if actual_frontier != expected_frontier:
            errors.append("computed boundary frontier omits or adds a parsed input")
        errors.append("computed block is stale or internally inconsistent")
    return errors


def validate_artifact(document: Mapping[str, Any]) -> ClosureSummary:
    """Validate a committed artifact without reading sibling repositories.

    The function re-derives the ledger, frontier, and ``closed`` value from the
    artifact's generated facts plus committed decisions.  It raises
    :class:`ClosureLedgerError` on any inconsistency.
    """

    errors = _validation_errors(document)
    if errors:
        raise ClosureLedgerError(errors)
    computed = document["computed"]
    return ClosureSummary(
        closed=computed["closed"],
        encoded_count=computed["provision_counts"]["encoded"],
        partially_encoded_count=computed["provision_counts"]["partially-encoded"],
        pending_count=computed["provision_counts"]["pending"],
        frontier_complete=computed["boundary_frontier"]["complete"],
        non_encoded_reasons_complete=computed["non_encoded_reasons_complete"],
        instrument_count=computed["instrument_frontier"]["counts"]["total"],
        instrument_pending_count=len(computed["instrument_frontier"]["pending"]),
        instrument_frontier_complete=computed["instrument_frontier"]["complete"],
        open_dependency_count=computed["dependency_closure"]["open_dependency_count"],
        dependency_closed=computed["dependency_closure"]["closed"],
    )


def build_artifact(
    *,
    corpus_release: Path,
    corpus_ref: str,
    rulespec_root: Path,
    rulespec_ref: str,
    committed_decisions: Mapping[str, Any],
    instrument_graph_path: Path = INSTRUMENT_GRAPH_PATH,
) -> tuple[dict[str, Any], tuple[str, ...]]:
    """Rebuild generated facts and computed claims, preserving decisions."""

    corpus, spine, provision_bodies = _read_corpus_spine(corpus_release, corpus_ref)
    rulespec, modules, module_inputs = _read_rulespec_facts(
        rulespec_root,
        rulespec_ref,
        provision_bodies=provision_bodies,
    )
    body_hashes = {row["citation_path"]: row["body_sha256"] for row in spine}
    for module in modules:
        citation = module["source_citation_path"]
        if citation == CORPUS_ROOT:
            continue
        if module.get("source_sha256") != body_hashes.get(citation):
            raise _SourceError(
                f"{rulespec_ref}:{module['path']}: source_sha256 does not match "
                f"the corpus body for {citation}"
            )
    instrument_graph = _read_instrument_graph(instrument_graph_path)
    generated = {
        "corpus_release": corpus,
        "rulespec": rulespec,
        "provision_spine": spine,
        "rulespec_modules": modules,
        "module_inputs": module_inputs,
        "instrument_graph": instrument_graph,
    }
    provision_order = {row["citation_path"]: index for index, row in enumerate(spine)}
    input_names = {row["name"] for row in module_inputs}
    instrument_elis = {row["eli"] for row in instrument_graph["instruments"]}
    errors: list[str] = []
    decisions = _canonical_decisions(
        committed_decisions,
        provision_order=provision_order,
        input_names=input_names,
        instrument_elis=instrument_elis,
        errors=errors,
    )
    computed = _derive_computed(generated, decisions, errors)
    document = {
        "schema": SCHEMA,
        "program": {"id": PROGRAM_ID, "corpus_root": CORPUS_ROOT},
        "generated_facts": generated,
        "committed_decisions": decisions,
        "computed": computed,
    }
    errors.extend(_validation_errors(document))
    return document, tuple(dict.fromkeys(errors))


def serialize_artifact(document: Mapping[str, Any]) -> str:
    return _HEADER + yaml.safe_dump(
        dict(document),
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )


def verify_artifact(
    *,
    artifact_path: Path = ARTIFACT_PATH,
    corpus_release: Path = CORPUS_RELEASE_PATH,
    corpus_ref: str | None = None,
    rulespec_root: Path = RULESPEC_ROOT,
    rulespec_ref: str | None = None,
    instrument_graph_path: Path = INSTRUMENT_GRAPH_PATH,
) -> VerificationResult:
    """Fully reproduce ``artifact_path`` from corpus and RuleSpec sources.

    With ``corpus_ref`` / ``rulespec_ref`` left ``None`` the reproduction is
    PINNED to the commits the artifact records (the ledger is a statement
    about one corpus commit and one rulespec commit; a branch tip moving with
    unrelated commits must not make it stale — and this is what certify's
    ``--verify-producers`` and the default ``--check`` exercise). Pass a ref
    explicitly to ask instead whether the ledger is CURRENT against it.
    """

    errors: list[str] = []
    try:
        text = artifact_path.read_text()
        loaded = yaml.safe_load(text)
    except (OSError, yaml.YAMLError) as exc:
        return VerificationResult(
            None, None, (f"could not read {artifact_path}: {exc}",)
        )
    if not isinstance(loaded, dict):
        return VerificationResult(
            None, None, (f"{artifact_path} is not a YAML mapping",)
        )
    facts = loaded.get("generated_facts") if isinstance(loaded.get("generated_facts"), dict) else {}
    if corpus_ref is None:
        recorded = (facts.get("corpus_release") or {}).get("commit") if isinstance(facts.get("corpus_release"), dict) else None
        corpus_ref = recorded if isinstance(recorded, str) and recorded else CORPUS_REF
    if rulespec_ref is None:
        recorded = (facts.get("rulespec") or {}).get("commit") if isinstance(facts.get("rulespec"), dict) else None
        rulespec_ref = recorded if isinstance(recorded, str) and recorded else RULESPEC_REF
    errors.extend(_validation_errors(loaded))
    try:
        expected, build_errors = build_artifact(
            corpus_release=corpus_release,
            corpus_ref=corpus_ref,
            rulespec_root=rulespec_root,
            rulespec_ref=rulespec_ref,
            committed_decisions=loaded.get("committed_decisions", {}),
            instrument_graph_path=instrument_graph_path,
        )
    except _SourceError as exc:
        return VerificationResult(
            loaded, None, tuple(dict.fromkeys([*errors, str(exc)]))
        )
    errors.extend(build_errors)
    if text != serialize_artifact(expected):
        errors.append(
            "closure artifact drift: run scripts/closure_ledger.py --generate"
        )
    return VerificationResult(
        loaded,
        expected,
        tuple(dict.fromkeys(errors)),
    )


def run(
    *,
    check: bool,
    artifact_path: Path,
    corpus_release: Path,
    corpus_ref: str | None,
    rulespec_root: Path,
    rulespec_ref: str | None,
    instrument_graph_path: Path = INSTRUMENT_GRAPH_PATH,
) -> int:
    if check:
        result = verify_artifact(
            artifact_path=artifact_path,
            corpus_release=corpus_release,
            corpus_ref=corpus_ref,
            rulespec_root=rulespec_root,
            rulespec_ref=rulespec_ref,
            instrument_graph_path=instrument_graph_path,
        )
        if result.errors:
            for error in result.errors:
                print(f"closure ledger error: {error}", file=sys.stderr)
            return 1
        assert result.document is not None
        summary = validate_artifact(result.document)
        print(
            "closure ledger up to date: "
            f"closed={str(summary.closed).lower()}, "
            f"encoded={summary.encoded_count}, "
            f"partially_encoded={summary.partially_encoded_count}, "
            f"pending={summary.pending_count}, "
            f"frontier_complete={str(summary.frontier_complete).lower()}, "
            f"instruments={summary.instrument_count}, "
            f"instrument_pending={summary.instrument_pending_count}, "
            f"instrument_frontier_complete="
            f"{str(summary.instrument_frontier_complete).lower()}, "
            f"open_dependencies={summary.open_dependency_count}, "
            f"dependency_closed={str(summary.dependency_closed).lower()}"
        )
        return 0

    if corpus_ref is None:
        corpus_ref = CORPUS_REF
    if rulespec_ref is None:
        rulespec_ref = RULESPEC_REF
    try:
        decisions = _load_decisions(artifact_path)
        document, errors = build_artifact(
            corpus_release=corpus_release,
            corpus_ref=corpus_ref,
            rulespec_root=rulespec_root,
            rulespec_ref=rulespec_ref,
            committed_decisions=decisions,
            instrument_graph_path=instrument_graph_path,
        )
    except _SourceError as exc:
        print(f"closure ledger error: {exc}", file=sys.stderr)
        return 1
    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    artifact_path.write_text(serialize_artifact(document))
    if errors:
        for error in errors:
            print(f"closure ledger error: {error}", file=sys.stderr)
        print(
            f"Wrote {artifact_path}, but committed decisions are incomplete or invalid.",
            file=sys.stderr,
        )
        return 1
    print(f"Wrote {artifact_path}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--generate", action="store_true", help="Regenerate the artifact")
    mode.add_argument(
        "--check", action="store_true", help="Fail on source or artifact drift"
    )
    parser.add_argument("--artifact", type=Path, default=ARTIFACT_PATH)
    parser.add_argument("--corpus-release", type=Path, default=CORPUS_RELEASE_PATH)
    parser.add_argument(
        "--corpus-ref",
        default=None,
        help=(
            f"corpus ref (default: {CORPUS_REF!r} for --generate; for --check the "
            "RECORDED corpus commit — pass a ref explicitly to ask whether the "
            "ledger is current against it)"
        ),
    )
    parser.add_argument("--rulespec-root", type=Path, default=RULESPEC_ROOT)
    parser.add_argument(
        "--instrument-graph",
        type=Path,
        default=INSTRUMENT_GRAPH_PATH,
        help="committed subordinate-instrument snapshot (see refresh_instrument_graph.py)",
    )
    parser.add_argument(
        "--rulespec-ref",
        default=None,
        help=(
            f"rulespec ref (default: {RULESPEC_REF!r} for --generate; for --check "
            "the RECORDED rulespec commit — pass a ref explicitly to ask whether "
            "the ledger is current against it)"
        ),
    )
    args = parser.parse_args(argv)
    return run(
        check=args.check,
        artifact_path=args.artifact,
        corpus_release=args.corpus_release,
        corpus_ref=args.corpus_ref,
        rulespec_root=args.rulespec_root,
        rulespec_ref=args.rulespec_ref,
        instrument_graph_path=args.instrument_graph,
    )


if __name__ == "__main__":
    raise SystemExit(main())
