#!/usr/bin/env python3
"""Build the source-completeness ledger for DK boerne- og ungeydelse.

The ledger has an explicit trust split:

* ``generated_facts`` are re-derived from the pinned corpus release and the
  exact tracked bytes at a RuleSpec git ref;
* ``committed_decisions`` are the reviewable exclusions and input-grounding
  decisions preserved across generation; and
* ``computed`` is a pure join of those two blocks.

``--check`` performs the full reproduction and fails closed when either source
is missing.  :func:`validate_artifact` separately checks the committed
artifact's internal derivation without requiring sibling repositories, so
certificate generation remains hermetic.

Usage::

    .venv/bin/python scripts/closure_ledger.py --generate
    .venv/bin/python scripts/closure_ledger.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
ARTIFACT_PATH = REPO_ROOT / "conformance" / "closure" / "dk-boerne-og-ungeydelse.yaml"
CORPUS_RELEASE_PATH = (
    Path.home()
    / "TheAxiomFoundation"
    / "_worktrees"
    / "axiom-corpus-dk-campaign"
    / "data"
    / "corpus"
    / "provisions"
    / "dk"
    / "statute"
    / "2026-08-04-dk-full-parity-tier1-current.jsonl"
)
CORPUS_REF = "HEAD"
RULESPEC_ROOT = Path.home() / "TheAxiomFoundation" / "rulespec-dk"
RULESPEC_REF = "main"

SCHEMA = "axiom_oracles.closure.ledger.v1"
PROGRAM_ID = "dk/boerne-og-ungeydelse"
CORPUS_ROOT = "dk/statute/lbk-603-2025/boerne-og-ungeydelsesloven"
STATUSES = (
    "encoded",
    "classified-with-reason",
    "excluded-with-reason",
    "pending",
)
GROUNDINGS = ("captured", "uncaptured")

_HEADER = """# axiom_oracles.closure.ledger.v1 — GENERATED facts + committed decisions.
# provision_spine, rulespec_modules, module_inputs, computed, and source hashes are
# regenerated by scripts/closure_ledger.py.  Edit only committed_decisions; the
# generator preserves those rows and --check fails on any other drift.
"""
_HEX_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_HEX_GIT_SHA = re.compile(r"^[0-9a-f]{40}$")
_IDENTIFIER = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")
_RESERVED_FORMULA_WORDS = frozenset({"and", "else", "false", "if", "not", "or", "true"})


class ClosureLedgerError(ValueError):
    """Raised when a committed closure artifact is not internally valid."""

    def __init__(self, errors: Sequence[str]):
        self.errors = tuple(errors)
        super().__init__("; ".join(self.errors))


@dataclass(frozen=True)
class ClosureSummary:
    """Hermetically derived certificate inputs from a valid artifact."""

    closed: bool
    pending_count: int
    frontier_complete: bool
    non_encoded_reasons_complete: bool


@dataclass(frozen=True)
class VerificationResult:
    """Result of re-deriving a committed artifact from its external sources."""

    document: dict[str, Any] | None
    expected: dict[str, Any] | None
    errors: tuple[str, ...]

    @property
    def valid(self) -> bool:
        return not self.errors

    @property
    def closed(self) -> bool:
        if not self.valid or self.document is None:
            return False
        computed = self.document.get("computed")
        return bool(isinstance(computed, Mapping) and computed.get("closed") is True)


class _SourceError(RuntimeError):
    pass


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _git_bytes(root: Path, *args: str) -> bytes:
    result = subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        check=False,
    )
    if result.returncode:
        detail = result.stderr.decode(errors="replace").strip()
        raise _SourceError(f"git {' '.join(args)} failed in {root}: {detail}")
    return result.stdout


def _resolve_commit(root: Path, ref: str, *, label: str) -> str:
    commit = _git_bytes(root, "rev-parse", "--verify", f"{ref}^{{commit}}")
    value = commit.decode().strip()
    if not _HEX_GIT_SHA.fullmatch(value):
        raise _SourceError(f"{label} ref {ref!r} did not resolve to a full commit SHA")
    return value


def _rulespec_commit(root: Path, ref: str) -> str:
    return _resolve_commit(root, ref, label="rulespec")


def _rulespec_paths(root: Path, ref: str) -> list[str]:
    raw = _git_bytes(
        root,
        "ls-tree",
        "-r",
        "-z",
        "--name-only",
        ref,
        "--",
        "dk/statutes",
    )
    return sorted(
        path.decode()
        for path in raw.split(b"\0")
        if path and path.endswith(b".yaml") and not path.endswith(b".test.yaml")
    )


def _rulespec_blob(root: Path, ref: str, path: str) -> bytes:
    return _git_bytes(root, "show", f"{ref}:{path}")


def _module_id(path: str) -> str:
    without_suffix = path.removesuffix(".yaml")
    jurisdiction, separator, remainder = without_suffix.partition("/")
    if not separator:
        raise _SourceError(f"invalid RuleSpec module path: {path}")
    return f"{jurisdiction}:{remainder}"


def _load_yaml_bytes(data: bytes, *, label: str) -> Any:
    try:
        return yaml.safe_load(data)
    except yaml.YAMLError as exc:
        raise _SourceError(f"could not parse {label}: {exc}") from exc


def _corpus_blob(path: Path, ref: str) -> tuple[str, str, bytes]:
    """Read a tracked corpus path through one immutable resolved commit."""

    if not path.parent.is_dir():
        raise _SourceError(f"corpus release parent is missing: {path.parent}")
    repo_raw = _git_bytes(path.parent, "rev-parse", "--show-toplevel")
    repo_root = Path(repo_raw.decode().strip()).resolve()
    try:
        relative = path.resolve().relative_to(repo_root).as_posix()
    except ValueError as exc:
        raise _SourceError(
            f"corpus release is outside its git repository: {path}"
        ) from exc
    commit = _resolve_commit(repo_root, ref, label="corpus")
    tracked = _git_bytes(
        repo_root,
        "ls-tree",
        "-z",
        "--name-only",
        commit,
        "--",
        relative,
    )
    tracked_paths = [value.decode() for value in tracked.split(b"\0") if value]
    if tracked_paths != [relative]:
        raise _SourceError(
            f"corpus release is not tracked at {ref} ({commit}): {relative}"
        )
    blob = _git_bytes(repo_root, "show", f"{commit}:{relative}")
    return relative, commit, blob


def _read_corpus_spine(
    path: Path, ref: str
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    relative_path, commit, blob = _corpus_blob(path, ref)
    try:
        lines = blob.decode("utf-8").splitlines()
    except UnicodeDecodeError as exc:
        raise _SourceError(
            f"corpus blob {commit}:{relative_path} is not UTF-8: {exc}"
        ) from exc

    document_row: dict[str, Any] | None = None
    provisions: list[dict[str, Any]] = []
    for line_number, line in enumerate(lines, start=1):
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            raise _SourceError(
                f"{commit}:{relative_path}:{line_number}: invalid JSON: {exc}"
            ) from exc
        if row.get("citation_path") == CORPUS_ROOT and row.get("kind") == "document":
            if document_row is not None:
                raise _SourceError(f"duplicate corpus document row for {CORPUS_ROOT}")
            document_row = row
            continue
        if (
            row.get("kind") == "section"
            and row.get("parent_citation_path") == CORPUS_ROOT
        ):
            body = row.get("body")
            heading = row.get("heading")
            citation_path = row.get("citation_path")
            ordinal = row.get("ordinal")
            if (
                not isinstance(body, str)
                or not body.strip()
                or not isinstance(heading, str)
                or not heading.strip()
                or not isinstance(citation_path, str)
                or not citation_path.startswith(f"{CORPUS_ROOT}/")
                or isinstance(ordinal, bool)
                or not isinstance(ordinal, int)
            ):
                raise _SourceError(
                    f"{commit}:{relative_path}:{line_number}: malformed provision "
                    f"under {CORPUS_ROOT}"
                )
            provisions.append(
                {
                    "ordinal": ordinal,
                    "citation_path": citation_path,
                    "heading": heading,
                    "body_sha256": _sha256_bytes(body.encode()),
                }
            )

    if document_row is None:
        raise _SourceError(f"corpus release has no document row for {CORPUS_ROOT}")
    provisions.sort(key=lambda row: (row["ordinal"], row["citation_path"]))
    citations = [row["citation_path"] for row in provisions]
    ordinals = [row["ordinal"] for row in provisions]
    if len(citations) != len(set(citations)):
        raise _SourceError(
            f"corpus release has duplicate provisions under {CORPUS_ROOT}"
        )
    if ordinals != list(range(1, len(provisions) + 1)):
        raise _SourceError(
            f"corpus provision ordinals under {CORPUS_ROOT} are not contiguous from 1"
        )
    metadata = document_row.get("metadata")
    block_count = metadata.get("block_count") if isinstance(metadata, Mapping) else None
    if block_count != len(provisions):
        raise _SourceError(
            f"corpus document declares {block_count!r} blocks but yielded "
            f"{len(provisions)} direct paragraffer"
        )

    generated_source = {
        "repository": "TheAxiomFoundation/axiom-corpus",
        "ref": ref,
        "commit": commit,
        "path": relative_path,
        "sha256": _sha256_bytes(blob),
        "version": document_row.get("version"),
        "source_id": document_row.get("source_id"),
        "source_as_of": document_row.get("source_as_of"),
        "citation_root": CORPUS_ROOT,
        "declared_block_count": block_count,
    }
    return generated_source, provisions


def _formula_inputs(
    document: Mapping[str, Any], module_id: str
) -> list[dict[str, Any]]:
    rules = document.get("rules")
    if not isinstance(rules, list):
        rules = []
    local_names = {
        row.get("name")
        for row in rules
        if isinstance(row, Mapping) and isinstance(row.get("name"), str)
    }
    imports = document.get("imports")
    imported_names = {
        value.rsplit("#", 1)[-1]
        for value in imports or []
        if isinstance(value, str) and "#" in value
    }
    readers: dict[str, set[str]] = {}
    for rule in rules:
        if not isinstance(rule, Mapping) or not isinstance(rule.get("name"), str):
            continue
        rule_name = rule["name"]
        versions = rule.get("versions")
        if not isinstance(versions, list):
            continue
        for version in versions:
            if not isinstance(version, Mapping):
                continue
            formula = version.get("formula")
            if not isinstance(formula, str):
                continue
            for match in _IDENTIFIER.finditer(formula):
                name = match.group()
                if name in local_names or name in imported_names:
                    continue
                if name.lower() in _RESERVED_FORMULA_WORDS:
                    continue
                # RuleSpec built-ins are call-shaped.  Inputs are bare symbols,
                # so excluding calls avoids a hand-maintained function catalog.
                if formula[match.end() :].lstrip().startswith("("):
                    continue
                readers.setdefault(name, set()).add(rule_name)
    return [
        {
            "slot": f"{module_id}#input.{name}",
            "name": name,
            "module": module_id,
            "read_by": sorted(rule_names),
        }
        for name, rule_names in sorted(readers.items())
    ]


def _read_rulespec_facts(
    root: Path, ref: str
) -> tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]]]:
    if not root.is_dir():
        raise _SourceError(f"rulespec checkout is missing: {root}")
    commit = _rulespec_commit(root, ref)
    modules: list[dict[str, Any]] = []
    module_inputs: list[dict[str, Any]] = []
    content_digest = hashlib.sha256()

    # Resolve the moving ref once, then enumerate and read every blob through
    # that immutable commit.  A concurrent main update cannot mix trees.
    for path in _rulespec_paths(root, commit):
        blob = _rulespec_blob(root, commit, path)
        document = _load_yaml_bytes(blob, label=f"{commit}:{path}")
        if not isinstance(document, Mapping) or document.get("format") != "rulespec/v1":
            continue
        module = document.get("module")
        if not isinstance(module, Mapping):
            continue
        verification = module.get("source_verification")
        source_citation = (
            verification.get("corpus_citation_path")
            if isinstance(verification, Mapping)
            else None
        )
        if not isinstance(source_citation, str) or not (
            source_citation == CORPUS_ROOT
            or source_citation.startswith(f"{CORPUS_ROOT}/")
        ):
            continue

        rules = document.get("rules")
        rule_count = len(rules) if isinstance(rules, list) else 0
        summary = module.get("summary")
        if not isinstance(summary, str) or not summary.strip():
            raise _SourceError(f"{ref}:{path}: selected module has no summary")
        module_status = module.get("status")
        if module_status is not None and (
            not isinstance(module_status, str) or not module_status.strip()
        ):
            raise _SourceError(f"{ref}:{path}: malformed module status")
        if module_status not in (None, "entity_not_supported"):
            raise _SourceError(
                f"{ref}:{path}: unsupported module status {module_status!r}; "
                "only entity_not_supported is a closure classification"
            )
        source_sha256 = (
            verification.get("source_sha256")
            if isinstance(verification, Mapping)
            else None
        )
        if source_citation != CORPUS_ROOT and not _HEX_SHA256.fullmatch(
            str(source_sha256 or "")
        ):
            raise _SourceError(
                f"{ref}:{path}: direct provision modules require a full "
                "module.source_verification.source_sha256"
            )
        module_id = _module_id(path)
        entry = {
            "path": path,
            "module_id": module_id,
            "sha256": _sha256_bytes(blob),
            "source_citation_path": source_citation,
            "rule_count": rule_count,
            "summary": summary.strip(),
        }
        if source_citation != CORPUS_ROOT:
            entry["source_sha256"] = source_sha256
        if module_status is not None:
            entry["status"] = module_status
        modules.append(entry)
        module_inputs.extend(_formula_inputs(document, module_id))
        content_digest.update(path.encode())
        content_digest.update(b"\0")
        content_digest.update(blob)
        content_digest.update(b"\0")

    modules.sort(key=lambda row: row["path"])
    module_inputs.sort(key=lambda row: row["slot"])
    if not modules:
        raise _SourceError(
            f"rulespec {ref!r} contains no tracked modules rooted at {CORPUS_ROOT}"
        )
    rulespec = {
        "repository": "TheAxiomFoundation/rulespec-dk",
        "ref": ref,
        "commit": commit,
        "selected_content_sha256": content_digest.hexdigest(),
    }
    return rulespec, modules, module_inputs


def _empty_decisions() -> dict[str, list[Any]]:
    return {"provisions": [], "input_grounding": []}


def _load_decisions(path: Path) -> dict[str, Any]:
    if not path.exists():
        return _empty_decisions()
    try:
        document = yaml.safe_load(path.read_text())
    except (OSError, yaml.YAMLError) as exc:
        raise _SourceError(
            f"could not read committed decisions from {path}: {exc}"
        ) from exc
    if not isinstance(document, Mapping):
        raise _SourceError(f"closure artifact is not a YAML mapping: {path}")
    decisions = document.get("committed_decisions")
    if decisions is None:
        return _empty_decisions()
    if not isinstance(decisions, Mapping):
        raise _SourceError("committed_decisions must be a mapping")
    return dict(decisions)


def _canonical_decisions(
    raw: Any,
    *,
    provision_order: Mapping[str, int],
    input_names: set[str],
    errors: list[str],
) -> dict[str, Any]:
    if not isinstance(raw, Mapping):
        errors.append("committed_decisions must be a mapping")
        raw = {}

    raw_provisions = raw.get("provisions", [])
    if not isinstance(raw_provisions, list):
        errors.append("committed_decisions.provisions must be a list")
        raw_provisions = []
    provisions: list[dict[str, Any]] = []
    seen_provisions: set[str] = set()
    for index, decision in enumerate(raw_provisions):
        label = f"committed_decisions.provisions[{index}]"
        if not isinstance(decision, Mapping):
            errors.append(f"{label} must be a mapping")
            continue
        citation = decision.get("citation_path")
        if not isinstance(citation, str) or citation not in provision_order:
            errors.append(f"{label}.citation_path is not in the generated spine")
            continue
        if citation in seen_provisions:
            errors.append(f"duplicate provision decision: {citation}")
            continue
        seen_provisions.add(citation)
        status = decision.get("status")
        classification = decision.get("classification")
        reason = decision.get("reason")
        if status != "excluded-with-reason":
            errors.append(f"{label}.status must be excluded-with-reason")
        if not isinstance(classification, str) or not classification.strip():
            errors.append(f"{label}.classification must be non-empty")
        if not isinstance(reason, str) or not reason.strip():
            errors.append(f"{label}.reason must be non-empty")
        provisions.append(
            {
                "citation_path": citation,
                "status": status,
                "classification": classification,
                "reason": reason.strip() if isinstance(reason, str) else reason,
            }
        )
    provisions.sort(key=lambda row: provision_order[row["citation_path"]])

    raw_grounding = raw.get("input_grounding", [])
    if not isinstance(raw_grounding, list):
        errors.append("committed_decisions.input_grounding must be a list")
        raw_grounding = []
    grounding: list[dict[str, Any]] = []
    seen_inputs: set[str] = set()
    for index, decision in enumerate(raw_grounding):
        label = f"committed_decisions.input_grounding[{index}]"
        if not isinstance(decision, Mapping):
            errors.append(f"{label} must be a mapping")
            continue
        name = decision.get("name")
        if not isinstance(name, str) or name not in input_names:
            errors.append(f"{label}.name is not a parsed module input")
            continue
        if name in seen_inputs:
            errors.append(f"duplicate input-grounding decision: {name}")
            continue
        seen_inputs.add(name)
        disposition = decision.get("grounding")
        reason = decision.get("reason")
        scope = decision.get("uncaptured_scope")
        if disposition not in GROUNDINGS:
            errors.append(f"{label}.grounding must be one of {GROUNDINGS}")
        if not isinstance(reason, str) or not reason.strip():
            errors.append(f"{label}.reason must be non-empty")
        if disposition == "uncaptured":
            if not isinstance(scope, str) or not scope.strip():
                errors.append(f"{label}.uncaptured_scope must be non-empty")
        elif scope is not None:
            errors.append(
                f"{label}.uncaptured_scope is only valid for uncaptured inputs"
            )
        row = {
            "name": name,
            "grounding": disposition,
            "reason": reason.strip() if isinstance(reason, str) else reason,
        }
        if disposition == "uncaptured":
            row["uncaptured_scope"] = scope.strip() if isinstance(scope, str) else scope
        grounding.append(row)
    grounding.sort(key=lambda row: row["name"])
    missing = sorted(input_names - seen_inputs)
    if missing:
        errors.append(
            "module inputs missing committed grounding decisions: " + ", ".join(missing)
        )
    extra = sorted(seen_inputs - input_names)
    if extra:
        errors.append(
            "committed grounding decisions have extra inputs: " + ", ".join(extra)
        )
    return {"provisions": provisions, "input_grounding": grounding}


def _derive_computed(
    generated: Mapping[str, Any],
    decisions: Mapping[str, Any],
    errors: list[str],
) -> dict[str, Any]:
    spine = generated.get("provision_spine")
    modules = generated.get("rulespec_modules")
    module_inputs = generated.get("module_inputs")
    if not isinstance(spine, list):
        errors.append("generated_facts.provision_spine must be a list")
        spine = []
    if not isinstance(modules, list):
        errors.append("generated_facts.rulespec_modules must be a list")
        modules = []
    if not isinstance(module_inputs, list):
        errors.append("generated_facts.module_inputs must be a list")
        module_inputs = []

    provision_decisions = {
        row["citation_path"]: row
        for row in decisions.get("provisions", [])
        if isinstance(row, Mapping) and isinstance(row.get("citation_path"), str)
    }
    direct_modules: dict[str, Mapping[str, Any]] = {}
    for module in modules:
        if not isinstance(module, Mapping):
            continue
        citation = module.get("source_citation_path")
        if not isinstance(citation, str) or citation == CORPUS_ROOT:
            continue
        if citation in direct_modules:
            errors.append(f"multiple RuleSpec modules directly join {citation}")
            continue
        direct_modules[citation] = module

    ledger: list[dict[str, Any]] = []
    for provision in spine:
        if not isinstance(provision, Mapping):
            continue
        citation = provision.get("citation_path")
        if not isinstance(citation, str):
            continue
        row = {
            "ordinal": provision.get("ordinal"),
            "citation_path": citation,
            "heading": provision.get("heading"),
            "body_sha256": provision.get("body_sha256"),
        }
        module = direct_modules.get(citation)
        decision = provision_decisions.get(citation)
        if module is not None and decision is not None:
            errors.append(
                f"{citation}: committed exclusion overlaps a direct RuleSpec module"
            )
        if module is not None and module.get("status") == "entity_not_supported":
            row.update(
                {
                    "status": "classified-with-reason",
                    "classification": module["status"],
                    "reason": module.get("summary"),
                    "classified_by": module.get("path"),
                }
            )
        elif (
            module is not None
            and isinstance(module.get("rule_count"), int)
            and module.get("rule_count") > 0
        ):
            row.update({"status": "encoded", "encoded_by": module.get("path")})
        elif decision is not None:
            row.update(
                {
                    "status": "excluded-with-reason",
                    "classification": decision.get("classification"),
                    "reason": decision.get("reason"),
                }
            )
        else:
            row["status"] = "pending"
        ledger.append(row)

    counts = {status: 0 for status in STATUSES}
    for row in ledger:
        status = row.get("status")
        if status in counts:
            counts[status] += 1
    counts = {"total": len(ledger), **counts}
    pending = [row["citation_path"] for row in ledger if row.get("status") == "pending"]
    reasons_complete = all(
        row.get("status") == "encoded"
        or row.get("status") == "pending"
        or (isinstance(row.get("reason"), str) and bool(row["reason"].strip()))
        for row in ledger
    )

    slots_by_name: dict[str, list[str]] = {}
    for row in module_inputs:
        if not isinstance(row, Mapping):
            continue
        name = row.get("name")
        slot = row.get("slot")
        if isinstance(name, str) and isinstance(slot, str):
            slots_by_name.setdefault(name, []).append(slot)
    grounding_rows = decisions.get("input_grounding", [])
    grounding_by_name = {
        row["name"]: row
        for row in grounding_rows
        if isinstance(row, Mapping) and isinstance(row.get("name"), str)
    }
    frontier_complete = set(grounding_by_name) == set(slots_by_name)
    frontier: list[dict[str, Any]] = []
    for name in sorted(slots_by_name):
        decision = grounding_by_name.get(name)
        if decision is None:
            continue
        if decision.get("grounding") == "uncaptured":
            scope = decision.get("uncaptured_scope")
            if not isinstance(scope, str) or not scope.strip():
                frontier_complete = False
            frontier.append(
                {
                    "input": name,
                    "slots": sorted(slots_by_name[name]),
                    "uncaptured_scope": scope,
                    "reason": decision.get("reason"),
                }
            )
        elif decision.get("grounding") != "captured":
            frontier_complete = False

    computed = {
        "ledger": ledger,
        "provision_counts": counts,
        "pending": pending,
        "boundary_frontier": {
            "parsed_input_count": len(slots_by_name),
            "uncaptured_input_count": len(frontier),
            "complete": frontier_complete,
            "inputs": frontier,
        },
        "non_encoded_reasons_complete": reasons_complete,
        "closed": not pending and frontier_complete and reasons_complete,
    }
    return computed


def _generated_fact_errors(generated: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(generated, Mapping):
        return ["generated_facts must be a mapping"]
    expected_keys = {
        "corpus_release",
        "rulespec",
        "provision_spine",
        "rulespec_modules",
        "module_inputs",
    }
    if set(generated) != expected_keys:
        errors.append(
            "generated_facts keys must be exactly: " + ", ".join(sorted(expected_keys))
        )

    corpus = generated.get("corpus_release")
    if not isinstance(corpus, Mapping):
        errors.append("generated_facts.corpus_release must be a mapping")
    else:
        corpus_keys = {
            "repository",
            "ref",
            "commit",
            "path",
            "sha256",
            "version",
            "source_id",
            "source_as_of",
            "citation_root",
            "declared_block_count",
        }
        if set(corpus) != corpus_keys:
            errors.append("corpus_release has unexpected or missing provenance keys")
        if corpus.get("repository") != "TheAxiomFoundation/axiom-corpus":
            errors.append(
                "corpus_release.repository must identify TheAxiomFoundation/axiom-corpus"
            )
        if not isinstance(corpus.get("ref"), str) or not corpus["ref"].strip():
            errors.append("corpus_release.ref must be non-empty")
        if not _HEX_GIT_SHA.fullmatch(str(corpus.get("commit", ""))):
            errors.append("corpus_release.commit must be a full git commit SHA")
        if not isinstance(corpus.get("path"), str) or not corpus["path"].endswith(
            ".jsonl"
        ):
            errors.append("corpus_release.path must identify a JSONL file")
        if corpus.get("citation_root") != CORPUS_ROOT:
            errors.append(
                "corpus_release.citation_root is not the declared program root"
            )
        if not _HEX_SHA256.fullmatch(str(corpus.get("sha256", ""))):
            errors.append("corpus_release.sha256 must be a full sha256")

    rulespec = generated.get("rulespec")
    if not isinstance(rulespec, Mapping):
        errors.append("generated_facts.rulespec must be a mapping")
    else:
        if rulespec.get("repository") != "TheAxiomFoundation/rulespec-dk":
            errors.append(
                "rulespec.repository must identify TheAxiomFoundation/rulespec-dk"
            )
        if not _HEX_GIT_SHA.fullmatch(str(rulespec.get("commit", ""))):
            errors.append("rulespec.commit must be a full git commit SHA")
        if not _HEX_SHA256.fullmatch(str(rulespec.get("selected_content_sha256", ""))):
            errors.append("rulespec.selected_content_sha256 must be a full sha256")

    spine = generated.get("provision_spine")
    if not isinstance(spine, list) or not spine:
        errors.append("generated_facts.provision_spine must be a non-empty list")
        spine = []
    spine_citations: list[str] = []
    for index, row in enumerate(spine):
        if not isinstance(row, Mapping):
            errors.append(f"provision_spine[{index}] must be a mapping")
            continue
        citation = row.get("citation_path")
        spine_citations.append(citation if isinstance(citation, str) else "")
        if set(row) != {"ordinal", "citation_path", "heading", "body_sha256"}:
            errors.append(f"provision_spine[{index}] has unexpected keys")
        if row.get("ordinal") != index + 1:
            errors.append(f"provision_spine[{index}] has a non-contiguous ordinal")
        if not isinstance(citation, str) or not citation.startswith(f"{CORPUS_ROOT}/"):
            errors.append(f"provision_spine[{index}] has an invalid citation_path")
        if not isinstance(row.get("heading"), str) or not row["heading"].strip():
            errors.append(f"provision_spine[{index}] has an invalid heading")
        if not _HEX_SHA256.fullmatch(str(row.get("body_sha256", ""))):
            errors.append(f"provision_spine[{index}] has an invalid body_sha256")
    if len(spine_citations) != len(set(spine_citations)):
        errors.append("generated provision spine has duplicate citation paths")
    if isinstance(corpus, Mapping) and corpus.get("declared_block_count") != len(spine):
        errors.append("generated provision spine disagrees with declared_block_count")
    spine_body_hashes = {
        row["citation_path"]: row["body_sha256"]
        for row in spine
        if isinstance(row, Mapping)
        and isinstance(row.get("citation_path"), str)
        and isinstance(row.get("body_sha256"), str)
    }

    modules = generated.get("rulespec_modules")
    if not isinstance(modules, list) or not modules:
        errors.append("generated_facts.rulespec_modules must be a non-empty list")
        modules = []
    module_ids: set[str] = set()
    module_paths: set[str] = set()
    for index, row in enumerate(modules):
        if not isinstance(row, Mapping):
            errors.append(f"rulespec_modules[{index}] must be a mapping")
            continue
        module_id = row.get("module_id")
        path = row.get("path")
        required = {
            "path",
            "module_id",
            "sha256",
            "source_citation_path",
            "rule_count",
            "summary",
        }
        direct = row.get("source_citation_path") != CORPUS_ROOT
        if direct:
            required.add("source_sha256")
        if set(row) not in (required, required | {"status"}):
            errors.append(f"rulespec_modules[{index}] has unexpected keys")
        if not isinstance(path, str) or not path.endswith(".yaml"):
            errors.append(f"rulespec_modules[{index}] has an invalid path")
        elif path in module_paths:
            errors.append(f"duplicate RuleSpec module path: {path}")
        else:
            module_paths.add(path)
        if not isinstance(module_id, str) or not module_id.startswith("dk:statutes/"):
            errors.append(f"rulespec_modules[{index}] has an invalid module_id")
        elif module_id in module_ids:
            errors.append(f"duplicate RuleSpec module id: {module_id}")
        else:
            module_ids.add(module_id)
        if not _HEX_SHA256.fullmatch(str(row.get("sha256", ""))):
            errors.append(f"rulespec_modules[{index}] has an invalid sha256")
        citation = row.get("source_citation_path")
        if not isinstance(citation, str) or not (
            citation == CORPUS_ROOT or citation.startswith(f"{CORPUS_ROOT}/")
        ):
            errors.append(f"rulespec_modules[{index}] is outside the corpus root")
        if (
            isinstance(citation, str)
            and citation != CORPUS_ROOT
            and citation not in spine_citations
        ):
            errors.append(
                f"rulespec_modules[{index}] cites a provision outside the spine"
            )
        if direct and not _HEX_SHA256.fullmatch(str(row.get("source_sha256", ""))):
            errors.append(
                f"rulespec_modules[{index}] direct module has an invalid source_sha256"
            )
        if direct and row.get("source_sha256") != spine_body_hashes.get(citation):
            errors.append(
                f"rulespec_modules[{index}] source_sha256 does not match the "
                "corpus provision body_sha256"
            )
        if row.get("status") not in (None, "entity_not_supported"):
            errors.append(
                f"rulespec_modules[{index}] has unsupported status {row.get('status')!r}"
            )
        if (
            isinstance(row.get("rule_count"), bool)
            or not isinstance(row.get("rule_count"), int)
            or row["rule_count"] < 0
        ):
            errors.append(f"rulespec_modules[{index}] has an invalid rule_count")
        if not isinstance(row.get("summary"), str) or not row["summary"].strip():
            errors.append(f"rulespec_modules[{index}] has an invalid summary")

    module_inputs = generated.get("module_inputs")
    if not isinstance(module_inputs, list) or not module_inputs:
        errors.append("generated_facts.module_inputs must be a non-empty list")
        module_inputs = []
    slots: set[str] = set()
    for index, row in enumerate(module_inputs):
        if not isinstance(row, Mapping):
            errors.append(f"module_inputs[{index}] must be a mapping")
            continue
        if set(row) != {"slot", "name", "module", "read_by"}:
            errors.append(f"module_inputs[{index}] has unexpected keys")
        slot = row.get("slot")
        name = row.get("name")
        module = row.get("module")
        if not isinstance(slot, str) or slot != f"{module}#input.{name}":
            errors.append(f"module_inputs[{index}] has an invalid #input slot")
        elif slot in slots:
            errors.append(f"duplicate module input slot: {slot}")
        else:
            slots.add(slot)
        if module not in module_ids:
            errors.append(f"module_inputs[{index}] references an unknown module")
        readers = row.get("read_by")
        if (
            not isinstance(readers, list)
            or not readers
            or not all(isinstance(value, str) and value for value in readers)
        ):
            errors.append(f"module_inputs[{index}].read_by must be non-empty")
    return errors


def _validation_errors(document: Any) -> list[str]:
    if not isinstance(document, Mapping):
        return ["closure artifact must be a mapping"]
    errors: list[str] = []
    if document.get("schema") != SCHEMA:
        errors.append(f"schema must be {SCHEMA}")
    program = document.get("program")
    if not isinstance(program, Mapping):
        errors.append("program must be a mapping")
    else:
        if program.get("id") != PROGRAM_ID:
            errors.append(f"program.id must be {PROGRAM_ID}")
        if program.get("corpus_root") != CORPUS_ROOT:
            errors.append(f"program.corpus_root must be {CORPUS_ROOT}")

    generated = document.get("generated_facts")
    errors.extend(_generated_fact_errors(generated))
    if not isinstance(generated, Mapping):
        return errors
    spine = generated.get("provision_spine")
    module_inputs = generated.get("module_inputs")
    provision_order = {
        row["citation_path"]: index
        for index, row in enumerate(spine or [])
        if isinstance(row, Mapping) and isinstance(row.get("citation_path"), str)
    }
    input_names = {
        row["name"]
        for row in module_inputs or []
        if isinstance(row, Mapping) and isinstance(row.get("name"), str)
    }
    decision_errors: list[str] = []
    decisions = _canonical_decisions(
        document.get("committed_decisions"),
        provision_order=provision_order,
        input_names=input_names,
        errors=decision_errors,
    )
    errors.extend(decision_errors)
    if document.get("committed_decisions") != decisions:
        errors.append("committed_decisions are not canonical")

    derive_errors: list[str] = []
    expected_computed = _derive_computed(generated, decisions, derive_errors)
    errors.extend(derive_errors)
    committed_computed = document.get("computed")
    if committed_computed != expected_computed:
        expected_ledger = {
            row["citation_path"]: row.get("status")
            for row in expected_computed["ledger"]
        }
        actual_ledger = {
            row.get("citation_path"): row.get("status")
            for row in (
                committed_computed.get("ledger", [])
                if isinstance(committed_computed, Mapping)
                else []
            )
            if isinstance(row, Mapping)
        }
        if actual_ledger != expected_ledger:
            errors.append(
                "computed ledger does not cover the generated spine/status join"
            )
        expected_frontier = {
            row["input"] for row in expected_computed["boundary_frontier"]["inputs"]
        }
        actual_frontier = {
            row.get("input")
            for row in (
                committed_computed.get("boundary_frontier", {}).get("inputs", [])
                if isinstance(committed_computed, Mapping)
                and isinstance(committed_computed.get("boundary_frontier"), Mapping)
                else []
            )
            if isinstance(row, Mapping)
        }
        if actual_frontier != expected_frontier:
            errors.append("computed boundary frontier omits or adds a parsed input")
        errors.append("computed block is stale or internally inconsistent")
    return errors


def validate_artifact(document: Mapping[str, Any]) -> ClosureSummary:
    """Validate a committed artifact without reading sibling repositories.

    The function re-derives the ledger, frontier, and ``closed`` value from the
    artifact's generated facts plus committed decisions.  It raises
    :class:`ClosureLedgerError` on any inconsistency.
    """

    errors = _validation_errors(document)
    if errors:
        raise ClosureLedgerError(errors)
    computed = document["computed"]
    return ClosureSummary(
        closed=computed["closed"],
        pending_count=computed["provision_counts"]["pending"],
        frontier_complete=computed["boundary_frontier"]["complete"],
        non_encoded_reasons_complete=computed["non_encoded_reasons_complete"],
    )


def build_artifact(
    *,
    corpus_release: Path,
    corpus_ref: str,
    rulespec_root: Path,
    rulespec_ref: str,
    committed_decisions: Mapping[str, Any],
) -> tuple[dict[str, Any], tuple[str, ...]]:
    """Rebuild generated facts and computed claims, preserving decisions."""

    corpus, spine = _read_corpus_spine(corpus_release, corpus_ref)
    rulespec, modules, module_inputs = _read_rulespec_facts(rulespec_root, rulespec_ref)
    body_hashes = {row["citation_path"]: row["body_sha256"] for row in spine}
    for module in modules:
        citation = module["source_citation_path"]
        if citation == CORPUS_ROOT:
            continue
        if module.get("source_sha256") != body_hashes.get(citation):
            raise _SourceError(
                f"{rulespec_ref}:{module['path']}: source_sha256 does not match "
                f"the corpus body for {citation}"
            )
    generated = {
        "corpus_release": corpus,
        "rulespec": rulespec,
        "provision_spine": spine,
        "rulespec_modules": modules,
        "module_inputs": module_inputs,
    }
    provision_order = {row["citation_path"]: index for index, row in enumerate(spine)}
    input_names = {row["name"] for row in module_inputs}
    errors: list[str] = []
    decisions = _canonical_decisions(
        committed_decisions,
        provision_order=provision_order,
        input_names=input_names,
        errors=errors,
    )
    computed = _derive_computed(generated, decisions, errors)
    document = {
        "schema": SCHEMA,
        "program": {"id": PROGRAM_ID, "corpus_root": CORPUS_ROOT},
        "generated_facts": generated,
        "committed_decisions": decisions,
        "computed": computed,
    }
    errors.extend(_validation_errors(document))
    return document, tuple(dict.fromkeys(errors))


def serialize_artifact(document: Mapping[str, Any]) -> str:
    return _HEADER + yaml.safe_dump(
        dict(document),
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )


def verify_artifact(
    *,
    artifact_path: Path = ARTIFACT_PATH,
    corpus_release: Path = CORPUS_RELEASE_PATH,
    corpus_ref: str = CORPUS_REF,
    rulespec_root: Path = RULESPEC_ROOT,
    rulespec_ref: str = RULESPEC_REF,
) -> VerificationResult:
    """Fully reproduce ``artifact_path`` from corpus and RuleSpec sources."""

    errors: list[str] = []
    try:
        text = artifact_path.read_text()
        loaded = yaml.safe_load(text)
    except (OSError, yaml.YAMLError) as exc:
        return VerificationResult(
            None, None, (f"could not read {artifact_path}: {exc}",)
        )
    if not isinstance(loaded, dict):
        return VerificationResult(
            None, None, (f"{artifact_path} is not a YAML mapping",)
        )
    errors.extend(_validation_errors(loaded))
    try:
        expected, build_errors = build_artifact(
            corpus_release=corpus_release,
            corpus_ref=corpus_ref,
            rulespec_root=rulespec_root,
            rulespec_ref=rulespec_ref,
            committed_decisions=loaded.get("committed_decisions", {}),
        )
    except _SourceError as exc:
        return VerificationResult(
            loaded, None, tuple(dict.fromkeys([*errors, str(exc)]))
        )
    errors.extend(build_errors)
    if text != serialize_artifact(expected):
        errors.append(
            "closure artifact drift: run scripts/closure_ledger.py --generate"
        )
    return VerificationResult(
        loaded,
        expected,
        tuple(dict.fromkeys(errors)),
    )


def run(
    *,
    check: bool,
    artifact_path: Path,
    corpus_release: Path,
    corpus_ref: str,
    rulespec_root: Path,
    rulespec_ref: str,
) -> int:
    if check:
        result = verify_artifact(
            artifact_path=artifact_path,
            corpus_release=corpus_release,
            corpus_ref=corpus_ref,
            rulespec_root=rulespec_root,
            rulespec_ref=rulespec_ref,
        )
        if result.errors:
            for error in result.errors:
                print(f"closure ledger error: {error}", file=sys.stderr)
            return 1
        assert result.document is not None
        summary = validate_artifact(result.document)
        print(
            "closure ledger up to date: "
            f"closed={str(summary.closed).lower()}, "
            f"pending={summary.pending_count}, "
            f"frontier_complete={str(summary.frontier_complete).lower()}"
        )
        return 0

    try:
        decisions = _load_decisions(artifact_path)
        document, errors = build_artifact(
            corpus_release=corpus_release,
            corpus_ref=corpus_ref,
            rulespec_root=rulespec_root,
            rulespec_ref=rulespec_ref,
            committed_decisions=decisions,
        )
    except _SourceError as exc:
        print(f"closure ledger error: {exc}", file=sys.stderr)
        return 1
    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    artifact_path.write_text(serialize_artifact(document))
    if errors:
        for error in errors:
            print(f"closure ledger error: {error}", file=sys.stderr)
        print(
            f"Wrote {artifact_path}, but committed decisions are incomplete or invalid.",
            file=sys.stderr,
        )
        return 1
    print(f"Wrote {artifact_path}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--generate", action="store_true", help="Regenerate the artifact")
    mode.add_argument(
        "--check", action="store_true", help="Fail on source or artifact drift"
    )
    parser.add_argument("--artifact", type=Path, default=ARTIFACT_PATH)
    parser.add_argument("--corpus-release", type=Path, default=CORPUS_RELEASE_PATH)
    parser.add_argument("--corpus-ref", default=CORPUS_REF)
    parser.add_argument("--rulespec-root", type=Path, default=RULESPEC_ROOT)
    parser.add_argument("--rulespec-ref", default=RULESPEC_REF)
    args = parser.parse_args(argv)
    return run(
        check=args.check,
        artifact_path=args.artifact,
        corpus_release=args.corpus_release,
        corpus_ref=args.corpus_ref,
        rulespec_root=args.rulespec_root,
        rulespec_ref=args.rulespec_ref,
    )


if __name__ == "__main__":
    raise SystemExit(main())
