#!/usr/bin/env python3
"""Compute the per-jurisdiction conformance scoreboard.

Joins each committed universe (``conformance/<jur>.yaml``) with the committed
comparison reports (``dashboard/public/data/*.json``, both the v2 and the
v2.1-dispositioned schemas) and produces, per jurisdiction:

* a small **summary scoreboard** — ``conformance/scoreboard.json`` — carrying the
  headline counts and the exact conformance predicate verdict. Kept small so the
  dashboard loads it fast (Vercel-static).
* an adjacent **per-policy drill-down** — ``conformance/detail/<jur>.json`` — with
  one row per universe policy (covered/uncovered/excluded, raw/explained rates).

The predicate is
``conformant = covered==in_scope && unexplained_total==0 &&
axiom_attributed_open==0 && !invalid_exclusions`` (an excluded policy whose
output column shows nonzero live exposure invalidates its exclusion).

Modes::

    uv run scripts/conformance_scoreboard.py            # write scoreboard + detail
    uv run scripts/conformance_scoreboard.py --check     # CI: fail if committed drifts
    uv run scripts/conformance_scoreboard.py --markdown   # human summary to stdout
    uv run scripts/conformance_scoreboard.py --snapshot   # also append a dated history snapshot

History for the burn-down is kept as committed dated snapshots under
``conformance/history/<jur>/<YYYY-MM-DD>.json`` — idempotent per day — so the
series survives squashes and rebases (no git-log mining).
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from axiom_oracles.conformance.loader import parse as parse_universe  # noqa: E402
from axiom_oracles.conformance.scoreboard import (  # noqa: E402
    PolicyScore,
    score_jurisdiction,
)

CONFORMANCE_DIR = REPO_ROOT / "conformance"
DETAIL_DIR = CONFORMANCE_DIR / "detail"
HISTORY_DIR = CONFORMANCE_DIR / "history"
DASHBOARD_DATA_DIR = REPO_ROOT / "dashboard" / "public" / "data"

#: Canonical copy — the CI source of truth the ratchet and history read.
SCOREBOARD_PATH = CONFORMANCE_DIR / "scoreboard.json"
#: Dashboard-served mirror (identical bytes) so the static site can fetch it.
DASHBOARD_SCOREBOARD_PATH = DASHBOARD_DATA_DIR / "conformance_scoreboard.json"

SCOREBOARD_SCHEMA = "axiom_oracles.conformance_scoreboard.v1"


def _load_reports() -> list[dict]:
    """Load every committed comparison report from the dashboard data dir."""
    reports: list[dict] = []
    for path in sorted(DASHBOARD_DATA_DIR.glob("*.json")):
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError:
            continue
        if isinstance(data, dict) and data.get("suite") and data.get("engines"):
            reports.append(data)
    return reports


def _universe_paths() -> list[Path]:
    return sorted(
        p
        for p in CONFORMANCE_DIR.glob("*.yaml")
        if p.stem not in {"ratchet", "unexplained-ratchet"}
    )


def build_scoreboard() -> tuple[dict, dict[str, list[PolicyScore]]]:
    """Compute the summary scoreboard doc + per-jurisdiction policy detail."""
    reports = _load_reports()
    jurisdictions: list[dict] = []
    details: dict[str, list[PolicyScore]] = {}

    for path in _universe_paths():
        universe = parse_universe(path)
        scoreboard, policy_scores = score_jurisdiction(universe, reports)
        jurisdictions.append(scoreboard.to_summary())
        details[universe.jurisdiction] = policy_scores

    jurisdictions.sort(key=lambda j: j["jurisdiction"])
    document = {
        "schema": SCOREBOARD_SCHEMA,
        "_comment": (
            "Generated by scripts/conformance_scoreboard.py — do not hand-edit. "
            "Per-jurisdiction conformance headline + the exact predicate verdict "
            "(conformant = covered==in_scope && unexplained_total==0 && "
            "axiom_attributed_open==0). Per-policy drill-down lives in "
            "conformance/detail/<jur>.json; the burn-down history in "
            "conformance/history/<jur>/<date>.json."
        ),
        "jurisdictions": jurisdictions,
    }
    return document, details


def _serialize(document: dict) -> str:
    return json.dumps(document, indent=2, sort_keys=False) + "\n"


def _detail_document(jurisdiction: str, scores: list[PolicyScore]) -> dict:
    return {
        "schema": "axiom_oracles.conformance_detail.v1",
        "_comment": (
            "Generated by scripts/conformance_scoreboard.py — per-policy "
            "conformance drill-down for one jurisdiction. Do not hand-edit."
        ),
        "jurisdiction": jurisdiction,
        "policies": [asdict(s) for s in scores],
    }


def _snapshot_document(summary: dict, date: str) -> dict:
    """A dated burn-down point: only the numbers that move over time."""
    return {
        "schema": "axiom_oracles.conformance_snapshot.v1",
        "date": date,
        "jurisdiction": summary["jurisdiction"],
        "oracle": summary["oracle"],
        "policies_in_scope": summary["policies_in_scope"],
        "covered": summary["covered"],
        "covered_pct": summary["covered_pct"],
        "excluded": summary["excluded"],
        "unexplained_total": summary["unexplained_total"],
        "axiom_attributed_open": summary["axiom_attributed_open"],
        "temporal_debt": summary.get("temporal_debt"),
        "conformant": summary["conformant"],
    }


def write_all(document: dict, details: dict[str, list[PolicyScore]]) -> None:
    serialized = _serialize(document)
    SCOREBOARD_PATH.write_text(serialized)
    # Mirror the summary into the dashboard's served data dir (identical bytes).
    DASHBOARD_DATA_DIR.mkdir(parents=True, exist_ok=True)
    DASHBOARD_SCOREBOARD_PATH.write_text(serialized)
    DETAIL_DIR.mkdir(parents=True, exist_ok=True)
    for jurisdiction, scores in details.items():
        detail_doc = _serialize(_detail_document(jurisdiction, scores))
        (DETAIL_DIR / f"{jurisdiction}.json").write_text(detail_doc)
        # Served drill-down copy the dashboard fetches per jurisdiction.
        (DASHBOARD_DATA_DIR / f"conformance_detail_{jurisdiction}.json").write_text(
            detail_doc
        )


def write_snapshots(document: dict, date: str) -> list[Path]:
    """Append (idempotently, per day) a dated history snapshot per jurisdiction."""
    written: list[Path] = []
    for summary in document["jurisdictions"]:
        jurisdiction = summary["jurisdiction"]
        jur_dir = HISTORY_DIR / jurisdiction
        jur_dir.mkdir(parents=True, exist_ok=True)
        snapshot_path = jur_dir / f"{date}.json"
        snapshot = _snapshot_document(summary, date)
        serialized = _serialize(snapshot)
        # Idempotent per day: rewrite only if today's numbers changed.
        if not snapshot_path.exists() or snapshot_path.read_text() != serialized:
            snapshot_path.write_text(serialized)
            written.append(snapshot_path)
    return written


def _markdown(document: dict) -> str:
    lines = ["# Conformance scoreboard", ""]
    for summary in document["jurisdictions"]:
        badge = "✅ CONFORMANT" if summary["conformant"] else "⛔ not yet conformant"
        lines.append(f"## {summary['jurisdiction'].upper()} — {badge}")
        lines.append(f"Oracle: `{summary['oracle']}`")
        lines.append("")
        lines.append(
            f"- In scope: **{summary['policies_in_scope']}** · "
            f"Covered: **{summary['covered']}** "
            f"({summary['covered_pct']:.0f}%) · "
            f"Excluded: **{summary['excluded']}**"
        )
        lines.append(
            f"- Unexplained: **{summary['unexplained_total']}** · "
            f"Axiom-attributed open: **{summary['axiom_attributed_open']}** · "
            f"Oracle-attributed: {summary['oracle_attributed']} · "
            f"Bridge artifacts: {summary['bridge_artifacts']}"
        )
        excl = summary.get("excluded_by_reason") or {}
        if excl:
            parts = ", ".join(f"{k}: {v}" for k, v in excl.items())
            lines.append(f"- Excluded by reason: {parts}")
        if summary["blocking_reasons"]:
            lines.append("- Blocking conformance:")
            for reason in summary["blocking_reasons"]:
                lines.append(f"    - {reason}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="CI: fail if the committed scoreboard/detail differ from a fresh run.",
    )
    parser.add_argument(
        "--markdown", action="store_true", help="Print a human summary to stdout."
    )
    parser.add_argument(
        "--snapshot",
        action="store_true",
        help="Also append a dated history snapshot per jurisdiction (idempotent).",
    )
    parser.add_argument(
        "--date",
        default=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        help="Snapshot date (YYYY-MM-DD); defaults to today UTC.",
    )
    args = parser.parse_args()

    document, details = build_scoreboard()

    if args.markdown:
        print(_markdown(document))
        return 0

    if args.check:
        serialized = _serialize(document)
        for path in (SCOREBOARD_PATH, DASHBOARD_SCOREBOARD_PATH):
            if not path.exists():
                sys.stderr.write(
                    f"{path.relative_to(REPO_ROOT)} missing; run "
                    "`uv run scripts/conformance_scoreboard.py`.\n"
                )
                return 1
            if path.read_text() != serialized:
                sys.stderr.write(
                    f"{path.relative_to(REPO_ROOT)} is stale; run "
                    "`uv run scripts/conformance_scoreboard.py` (a universe or a "
                    "comparison report changed).\n"
                )
                return 1
        for jurisdiction, scores in details.items():
            expected = _serialize(_detail_document(jurisdiction, scores))
            for path in (
                DETAIL_DIR / f"{jurisdiction}.json",
                DASHBOARD_DATA_DIR / f"conformance_detail_{jurisdiction}.json",
            ):
                if not path.exists() or path.read_text() != expected:
                    sys.stderr.write(
                        f"{path.relative_to(REPO_ROOT)} is stale; run "
                        "`uv run scripts/conformance_scoreboard.py`.\n"
                    )
                    return 1
        n = len(document["jurisdictions"])
        conformant = sum(1 for j in document["jurisdictions"] if j["conformant"])
        print(
            f"conformance scoreboard OK: {n} jurisdiction(s), "
            f"{conformant} conformant"
        )
        return 0

    write_all(document, details)
    if args.snapshot:
        written = write_snapshots(document, args.date)
        print(
            f"Wrote {SCOREBOARD_PATH.relative_to(REPO_ROOT)} + "
            f"{len(details)} detail file(s); "
            f"{len(written)} history snapshot(s) updated for {args.date}."
        )
    else:
        print(
            f"Wrote {SCOREBOARD_PATH.relative_to(REPO_ROOT)} + "
            f"{len(details)} detail file(s) "
            f"({len(document['jurisdictions'])} jurisdictions)."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
