#!/usr/bin/env python3
"""Build the conformance burn-down series from committed dated snapshots.

The burn-down is derived from ``conformance/history/<jur>/<YYYY-MM-DD>.json`` —
dated scoreboard snapshots the CI/rerun workflow appends idempotently per day.
This is deliberately NOT git-log mining: committed snapshot files survive squashes
and rebases and are trivially readable in CI. If a jurisdiction has no history
yet, its series starts with today's live point (never a fabricated timestamp).

Writes ``dashboard/public/data/conformance_burndown.json`` — one series per
jurisdiction of ``{date, in_scope, covered, uncovered, unexplained,
axiom_attributed_open}`` — so the dashboard can draw coverage rising and the
gap (uncovered + unexplained + axiom-open) burning down over time.

Usage::

    uv run scripts/conformance_burndown.py            # write the series
    uv run scripts/conformance_burndown.py --check     # CI: fail if committed drifts
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

CONFORMANCE_DIR = REPO_ROOT / "conformance"
HISTORY_DIR = CONFORMANCE_DIR / "history"
OUTPUT_PATH = REPO_ROOT / "dashboard" / "public" / "data" / "conformance_burndown.json"


def _point_from_snapshot(snapshot: dict) -> dict:
    in_scope = int(snapshot.get("policies_in_scope", 0) or 0)
    covered = int(snapshot.get("covered", 0) or 0)
    unexplained = int(snapshot.get("unexplained_total", 0) or 0)
    axiom_open = int(snapshot.get("axiom_attributed_open", 0) or 0)
    return {
        "date": snapshot["date"],
        "in_scope": in_scope,
        "covered": covered,
        "uncovered": max(in_scope - covered, 0),
        "unexplained": unexplained,
        "axiom_attributed_open": axiom_open,
        # The full remaining gap to conformance on that date.
        "gap": max(in_scope - covered, 0) + unexplained + axiom_open,
        "conformant": bool(snapshot.get("conformant", False)),
    }


def _series_for(jurisdiction_dir: Path) -> list[dict]:
    points: list[dict] = []
    for snapshot_path in sorted(jurisdiction_dir.glob("*.json")):
        try:
            snapshot = json.loads(snapshot_path.read_text())
        except json.JSONDecodeError:
            continue
        if snapshot.get("date"):
            points.append(_point_from_snapshot(snapshot))
    points.sort(key=lambda p: p["date"])
    return points


def _live_series() -> dict[str, dict]:
    """Fallback single point from the live scoreboard when history is empty."""
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "_conformance_scoreboard", REPO_ROOT / "scripts" / "conformance_scoreboard.py"
    )
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(mod)
    document, _ = mod.build_scoreboard()
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out: dict[str, dict] = {}
    for summary in document["jurisdictions"]:
        snap = {
            "date": today,
            "policies_in_scope": summary["policies_in_scope"],
            "covered": summary["covered"],
            "unexplained_total": summary["unexplained_total"],
            "axiom_attributed_open": summary["axiom_attributed_open"],
            "conformant": summary["conformant"],
        }
        out[summary["jurisdiction"]] = snap
    return out


def build_burndown() -> dict:
    live = _live_series()
    jurisdictions: dict[str, list[dict]] = {}

    if HISTORY_DIR.exists():
        for jur_dir in sorted(HISTORY_DIR.iterdir()):
            if jur_dir.is_dir():
                series = _series_for(jur_dir)
                if series:
                    jurisdictions[jur_dir.name] = series

    # Any jurisdiction with no committed history starts its series today from the
    # live scoreboard — a real observed point, never an invented past.
    for jurisdiction, snapshot in live.items():
        if jurisdiction not in jurisdictions:
            jurisdictions[jurisdiction] = [_point_from_snapshot(snapshot)]

    return {
        "schema": "axiom_oracles.conformance_burndown.v1",
        "_comment": (
            "Generated by scripts/conformance_burndown.py from the committed "
            "dated snapshots in conformance/history/<jur>/. Not git-log-derived — "
            "snapshot files survive rebases. A jurisdiction with no history starts "
            "today from the live scoreboard (no fabricated timestamps)."
        ),
        "series": {
            jurisdiction: points
            for jurisdiction, points in sorted(jurisdictions.items())
        },
    }


def _serialize(document: dict) -> str:
    return json.dumps(document, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="CI: fail if the committed burn-down differs from a fresh build.",
    )
    args = parser.parse_args()

    document = build_burndown()
    serialized = _serialize(document)

    if args.check:
        if not OUTPUT_PATH.exists():
            sys.stderr.write(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} missing; run "
                "`uv run scripts/conformance_burndown.py`.\n"
            )
            return 1
        if OUTPUT_PATH.read_text() != serialized:
            sys.stderr.write(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is stale; run "
                "`uv run scripts/conformance_burndown.py` (a new snapshot landed).\n"
            )
            return 1
        n = sum(len(s) for s in document["series"].values())
        print(
            f"conformance burn-down OK: {len(document['series'])} series, "
            f"{n} point(s)"
        )
        return 0

    OUTPUT_PATH.write_text(serialized)
    print(
        f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}: "
        f"{len(document['series'])} jurisdiction series."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
