#!/usr/bin/env python3
"""Derive the three German measured-discovery closure ledgers.

The trust split mirrors ``scripts/closure_ledger.py``:

* ``generated_facts`` come from the pinned corpus/RuleSpec objects and the
  committed DE discovery snapshot;
* ``committed_decisions`` is intentionally empty in this discovery sprint;
* ``computed`` is a pure, fail-closed join.  Every provision, instrument and
  typed leaf remains pending.

``--check`` is hermetic.  It reads local git objects and committed files and
never imports or calls a network client.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT / "closure" / "de" / "source.json"
SNAPSHOT_PATH = REPO_ROOT / "conformance" / "closure" / "de-instrument-graph.json"
CORPUS_ROOT = Path.home() / "TheAxiomFoundation" / "axiom-corpus-de-wave"
RULESPEC_ROOT = Path.home() / "TheAxiomFoundation" / "rulespec-de"

SCHEMA = "axiom_oracles.closure.ledger.v3"
SNAPSHOT_SCHEMA = "axiom_oracles.closure.de_instrument_graph.v1"
PROGRAM_IDS = (
    "de/kindergeld",
    "de/unterhaltsvorschuss",
    "de/rv-employee-contribution",
)
CERTIFICATE_PATHS = {
    program_id: REPO_ROOT
    / "certificates"
    / f"de-{program_id.removeprefix('de/').replace('/', '-')}.json"
    for program_id in PROGRAM_IDS
}
ARTIFACT_PATHS = {
    program_id: REPO_ROOT
    / "conformance"
    / "closure"
    / f"de-{program_id.removeprefix('de/').replace('/', '-')}.yaml"
    for program_id in PROGRAM_IDS
}

_HEADER = """# axiom_oracles.closure.ledger.v3 — GENERATED, ALL-PENDING discovery ledger.
# generated_facts and computed are regenerated by scripts/de_closure_ledger.py.
# committed_decisions is deliberately empty: this sprint does not disposition law.
"""
_HEX_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_HEX_GIT_SHA = re.compile(r"^(?=[0-9a-f]{40}$)(?=.*[a-f])[0-9a-f]{40}$")
_IDENTIFIER = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")
_RESERVED = frozenset(
    {
        "and",
        "or",
        "not",
        "if",
        "else",
        "true",
        "false",
        "min",
        "max",
        "floor",
        "ceil",
        "round",
        "abs",
    }
)

_SPINE_SCOPES = {
    "de/kindergeld": {
        "kind": "ordinal_range",
        "corpus_root": "de/statute/estg",
        "first_ordinal": 62,
        "last_ordinal": 78,
        "description": "every direct EStG provision with corpus ordinal 62 through 78 inclusive",
    },
    "de/unterhaltsvorschuss": {
        "kind": "ordinal_range",
        "corpus_root": "de/statute/uhvorschg",
        "first_ordinal": 1,
        "last_ordinal": 12,
        "description": "every direct UhVorschG provision with corpus ordinal 1 through 12 inclusive",
    },
    "de/rv-employee-contribution": {
        "kind": "exact_citations",
        "citations": [
            "de/regulation/bsv-2018/1",
            "de/statute/sgb-6/168",
            "de/regulation/svbezgrv-2025/4",
        ],
        "description": "the three exact declared calculation sources",
    },
}

_CAPTURED_MAX_DEPTH = {
    "de/kindergeld": 1,
    "de/unterhaltsvorschuss": 2,
    "de/rv-employee-contribution": 1,
}

_KINDERGELD_LEAF_SEEDS = {
    "claimant_entitlement": "de-kg-leaf-001",
    "qualifying_child_count": "de-kg-leaf-002",
    "recipient_priority": "de-kg-leaf-003",
    "substitute_child_benefit_exclusion": "de-kg-leaf-004",
}
_LEAF_PREFIX = {
    "de/kindergeld": "de-kg-leaf",
    "de/unterhaltsvorschuss": "de-uhv-leaf",
    "de/rv-employee-contribution": "de-rv-leaf",
}


class ClosureLedgerError(ValueError):
    """A committed DE closure ledger is not internally valid."""

    def __init__(self, errors: Sequence[str]):
        self.errors = tuple(errors)
        super().__init__("; ".join(self.errors))


class _SourceError(RuntimeError):
    pass


@dataclass(frozen=True)
class VerificationResult:
    document: dict[str, Any] | None
    expected: dict[str, Any] | None
    errors: tuple[str, ...]

    @property
    def valid(self) -> bool:
        return not self.errors

    @property
    def closed(self) -> bool:
        return False


@dataclass(frozen=True)
class ClosureSummary:
    """Small fail-closed view returned to validators and certificate callers."""

    closed: bool
    spine_rows: int
    pending_provisions: int
    pending_instruments: int
    pending_inputs: int
    open_dependencies: int


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _canonical_sha(value: Any) -> str:
    return _sha256(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    )


def _git(root: Path, *args: str) -> bytes:
    environment = os.environ.copy()
    environment.update(
        {
            "GIT_NO_LAZY_FETCH": "1",
            "GIT_TERMINAL_PROMPT": "0",
        }
    )
    result = subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        check=False,
        env=environment,
    )
    if result.returncode:
        detail = result.stderr.decode(errors="replace").strip()
        raise _SourceError(f"git {' '.join(args)} failed in {root}: {detail}")
    return result.stdout


def _git_blob(root: Path, commit: str, path: str) -> bytes:
    return _git(root, "show", f"{commit}:{path}")


def _load_json_bytes(data: bytes, label: str) -> Any:
    try:
        return json.loads(data)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise _SourceError(f"could not parse {label}: {exc}") from exc


def load_document(path: Path) -> dict[str, Any]:
    try:
        value = yaml.safe_load(path.read_bytes())
    except (OSError, yaml.YAMLError) as exc:
        raise ClosureLedgerError((f"could not read {path}: {exc}",)) from exc
    if not isinstance(value, dict):
        raise ClosureLedgerError(("ledger must be a mapping",))
    return value


def _source_manifest(path: Path = SOURCE_PATH) -> tuple[dict[str, Any], bytes]:
    data = path.read_bytes()
    value = _load_json_bytes(data, str(path))
    if not isinstance(value, dict):
        raise _SourceError("closure/de/source.json must be an object")
    return value, data


def _corpus_rows(
    source: Mapping[str, Any], corpus_root: Path
) -> tuple[dict[str, dict[str, Any]], list[dict[str, Any]]]:
    corpus = source.get("corpus")
    if not isinstance(corpus, Mapping):
        raise _SourceError("source corpus block is missing")
    commit = corpus.get("commit")
    if not isinstance(commit, str) or not _HEX_GIT_SHA.fullmatch(commit):
        raise _SourceError("source corpus commit is not a full SHA")
    resolved = _git(corpus_root, "rev-parse", "--verify", f"{commit}^{{commit}}").decode().strip()
    if resolved != commit:
        raise _SourceError("pinned corpus commit did not resolve exactly")

    index: dict[str, dict[str, Any]] = {}
    receipts: list[dict[str, Any]] = []
    provision_sources = corpus.get("provision_sources")
    if not isinstance(provision_sources, list) or not provision_sources:
        raise _SourceError("source corpus provision_sources is empty")
    for item in sorted(provision_sources, key=lambda row: str(row.get("path", ""))):
        if not isinstance(item, Mapping):
            raise _SourceError("corpus provision source must be an object")
        rel = item.get("path")
        expected_sha = item.get("sha256")
        expected_count = item.get("row_count")
        if not isinstance(rel, str) or not isinstance(expected_sha, str):
            raise _SourceError("corpus source path/hash is malformed")
        blob = _git_blob(corpus_root, commit, rel)
        if _sha256(blob) != expected_sha:
            raise _SourceError(f"corpus blob hash mismatch: {rel}")
        raw_lines = blob.splitlines()
        if isinstance(expected_count, bool) or not isinstance(expected_count, int):
            raise _SourceError(f"corpus row_count is not an integer: {rel}")
        if len(raw_lines) != expected_count:
            raise _SourceError(f"corpus row count mismatch: {rel}")
        receipts.append({"path": rel, "sha256": expected_sha, "row_count": expected_count})
        for line_number, raw in enumerate(raw_lines, 1):
            row = _load_json_bytes(raw, f"{rel}:{line_number}")
            if not isinstance(row, dict) or not isinstance(row.get("citation_path"), str):
                raise _SourceError(f"corpus row lacks citation_path: {rel}:{line_number}")
            citation = row["citation_path"]
            if citation in index:
                raise _SourceError(f"duplicate corpus citation_path: {citation}")
            index[citation] = {
                "record": row,
                "line_number": line_number,
                "provision_file": rel,
                "row_sha256": _sha256(raw),
            }
    return index, receipts


def _spine(program_id: str, index: Mapping[str, Mapping[str, Any]]) -> list[dict[str, Any]]:
    scope = _SPINE_SCOPES[program_id]
    selected: list[Mapping[str, Any]] = []
    if scope["kind"] == "ordinal_range":
        parent = scope["corpus_root"]
        for item in index.values():
            row = item["record"]
            ordinal = row.get("ordinal")
            if (
                row.get("parent_citation_path") == parent
                and isinstance(ordinal, int)
                and not isinstance(ordinal, bool)
                and scope["first_ordinal"] <= ordinal <= scope["last_ordinal"]
            ):
                selected.append(item)
        selected.sort(key=lambda item: (item["record"]["ordinal"], item["record"]["citation_path"]))
    else:
        for citation in scope["citations"]:
            item = index.get(citation)
            if item is None:
                raise _SourceError(f"declared spine citation is absent: {citation}")
            selected.append(item)

    expected = 18 if program_id == "de/kindergeld" else 12 if program_id == "de/unterhaltsvorschuss" else 3
    if len(selected) != expected:
        raise _SourceError(f"{program_id} spine has {len(selected)} rows, expected {expected}")

    out: list[dict[str, Any]] = []
    for ledger_ordinal, item in enumerate(selected, 1):
        row = item["record"]
        body = row.get("body")
        if not isinstance(body, str):
            raise _SourceError(f"spine row has no body: {row['citation_path']}")
        body_sha = _sha256(body.encode())
        out.append(
            {
                "ordinal": ledger_ordinal,
                "corpus_ordinal": row.get("ordinal"),
                "citation_path": row["citation_path"],
                "heading": row.get("heading"),
                "body_sha256": body_sha,
                "row_sha256": item["row_sha256"],
                "citation_receipt": {
                    "path": item["provision_file"],
                    "line": item["line_number"],
                },
            }
        )
    return out


def _module_id(path: str) -> str:
    return f"de:{path.removesuffix('.yaml').removeprefix('de/')}"


def _module_inputs(document: Mapping[str, Any], module_id: str) -> list[dict[str, Any]]:
    rules = document.get("rules")
    if not isinstance(rules, list):
        return []
    rule_names = {
        row.get("name") for row in rules if isinstance(row, Mapping) and isinstance(row.get("name"), str)
    }
    readers: dict[str, set[str]] = {}
    for rule in rules:
        if not isinstance(rule, Mapping) or not isinstance(rule.get("name"), str):
            continue
        versions = rule.get("versions", [])
        if not isinstance(versions, list):
            continue
        for version in versions:
            if not isinstance(version, Mapping):
                continue
            formula = version.get("formula")
            if not isinstance(formula, str):
                continue
            for token in _IDENTIFIER.findall(formula):
                if token.lower() in _RESERVED or token in rule_names:
                    continue
                readers.setdefault(token, set()).add(rule["name"])
    return [
        {
            "slot": f"{module_id}#input.{name}",
            "name": name,
            "module": module_id,
            "read_by": sorted(read_by),
        }
        for name, read_by in sorted(readers.items())
    ]


def _rulespec_facts(
    source: Mapping[str, Any], program_id: str, rulespec_root: Path
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    rulespec = source.get("rulespec")
    programs = source.get("programs")
    if not isinstance(rulespec, Mapping) or not isinstance(programs, Mapping):
        raise _SourceError("source RuleSpec/program blocks are missing")
    program = programs.get(program_id)
    if not isinstance(program, Mapping):
        raise _SourceError(f"source program is missing: {program_id}")
    module_index = {
        row.get("citation_path"): row
        for row in rulespec.get("modules", [])
        if isinstance(row, Mapping) and isinstance(row.get("citation_path"), str)
    }
    modules: list[dict[str, Any]] = []
    inputs: list[dict[str, Any]] = []
    for declared in program.get("declared_sources", []):
        citation = declared.get("citation_path") if isinstance(declared, Mapping) else None
        if not isinstance(citation, str):
            raise _SourceError(f"malformed declared source for {program_id}")
        source_module = module_index.get(citation)
        artifact = source_module.get("artifact") if isinstance(source_module, Mapping) else None
        if not isinstance(artifact, Mapping):
            modules.append({"citation_path": citation, "state": "no_artifact"})
            continue
        ref = artifact.get("commit", artifact.get("ref"))
        path = artifact.get("path")
        expected_sha = artifact.get("sha256")
        if not all(isinstance(value, str) for value in (ref, path, expected_sha)):
            raise _SourceError(f"malformed RuleSpec artifact for {citation}")
        resolved = _git(rulespec_root, "rev-parse", "--verify", f"{ref}^{{commit}}").decode().strip()
        if not _HEX_GIT_SHA.fullmatch(resolved):
            raise _SourceError(f"RuleSpec ref did not resolve: {ref}")
        blob = _git_blob(rulespec_root, resolved, path)
        if _sha256(blob) != expected_sha:
            raise _SourceError(f"RuleSpec artifact hash mismatch: {path}")
        document = yaml.safe_load(blob)
        if not isinstance(document, Mapping):
            raise _SourceError(f"RuleSpec artifact is not a mapping: {path}")
        module_id = _module_id(path)
        imports = document.get("imports", [])
        if imports is None:
            imports = []
        if not isinstance(imports, list):
            raise _SourceError(f"RuleSpec imports is not a list: {path}")
        rules = document.get("rules", [])
        modules.append(
            {
                "citation_path": citation,
                "state": "captured",
                "ref": ref,
                "commit": resolved,
                "path": path,
                "sha256": expected_sha,
                "module_id": module_id,
                "rule_count": len(rules) if isinstance(rules, list) else 0,
                "declared_imports": copy.deepcopy(imports),
            }
        )
        inputs.extend(_module_inputs(document, module_id))
    modules.sort(key=lambda row: row["citation_path"])
    inputs.sort(key=lambda row: row["slot"])
    return modules, inputs


def _leaf_frontier(
    source: Mapping[str, Any], program_id: str, module_inputs: Sequence[Mapping[str, Any]]
) -> list[dict[str, Any]]:
    program = source["programs"][program_id]
    boundary_by_name = {
        row["input"]: row
        for row in program.get("boundaries", [])
        if isinstance(row, Mapping) and isinstance(row.get("input"), str)
    }
    grouped: dict[str, dict[str, Any]] = {}
    for item in module_inputs:
        name = item["name"]
        row = grouped.setdefault(name, {"slots": [], "read_by": set()})
        row["slots"].append(item["slot"])
        row["read_by"].update(item["read_by"])
    # Source-boundary rows are part of the declared program frontier even when
    # the current amount-only module does not read them yet.
    for name in boundary_by_name:
        grouped.setdefault(name, {"slots": [], "read_by": set()})

    out: list[dict[str, Any]] = []
    for name, grouped_row in sorted(grouped.items()):
        committed = boundary_by_name.get(name)
        if committed is not None:
            leaf_kind = committed.get("leaf_kind")
            if leaf_kind != "law_derived":
                raise _SourceError(f"unsupported committed source leaf kind for {name}")
        else:
            leaf_kind = "unclassified"
        row: dict[str, Any] = {
            "id": (
                _KINDERGELD_LEAF_SEEDS[name]
                if program_id == "de/kindergeld" and name in _KINDERGELD_LEAF_SEEDS
                else f"{_LEAF_PREFIX[program_id]}-{_sha256(name.encode())[:16]}"
            ),
            "input": name,
            "slots": sorted(set(grouped_row["slots"])),
            "read_by": sorted(grouped_row["read_by"]),
            "leaf_kind": leaf_kind,
            "status": "pending",
        }
        if committed is not None:
            row["citation_path"] = committed["citation_path"]
            row["source_commitment"] = {
                "classification": committed["classification"],
                "reason": committed["reason"],
            }
        out.append(row)
    return out


def _snapshot_facts(
    program_id: str, snapshot_path: Path, source_path: Path
) -> dict[str, Any]:
    raw = snapshot_path.read_bytes()
    snapshot = _load_json_bytes(raw, str(snapshot_path))
    validate_snapshot(snapshot)
    for key, bound_path in (
        ("source", source_path),
        (
            "query_set",
            REPO_ROOT / str(snapshot.get("query_set", {}).get("path", "")),
        ),
    ):
        binding = snapshot.get(key)
        if not isinstance(binding, Mapping):
            raise _SourceError(f"snapshot {key} binding is missing")
        try:
            relative = bound_path.resolve().relative_to(REPO_ROOT).as_posix()
            digest = _sha256(bound_path.read_bytes())
        except (OSError, ValueError) as exc:
            raise _SourceError(f"could not verify snapshot {key} binding: {exc}") from exc
        if binding != {"path": relative, "sha256": digest}:
            raise _SourceError(f"snapshot {key} binding does not match committed bytes")
    programs = snapshot["programs"]
    match = next((row for row in programs if row.get("id") == program_id), None)
    if match is None:
        raise _SourceError(f"snapshot lacks program: {program_id}")
    channels = snapshot["channels"]
    receipts = {
        name: value["receipt_sha256"]
        for name, value in channels.items()
    }
    facts = {
        "snapshot_path": snapshot_path.relative_to(REPO_ROOT).as_posix(),
        "snapshot_sha256": _sha256(raw),
        "channel_receipts": receipts,
        "candidate_count": len(match["instruments"]),
        "candidates": copy.deepcopy(match["instruments"]),
    }
    if "seed_bindings" in match:
        facts["seed_bindings"] = copy.deepcopy(match["seed_bindings"])
    return facts


def _measurement_basis(
    program_id: str,
    program: Mapping[str, Any],
    modules: Sequence[Mapping[str, Any]],
    leaves: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Bind the two work counts and label the depth figure as an estimate."""

    certificate_path = CERTIFICATE_PATHS[program_id]
    raw = certificate_path.read_bytes()
    certificate = _load_json_bytes(raw, str(certificate_path))
    if not isinstance(certificate, Mapping) or certificate.get("program") != program_id:
        raise _SourceError(f"certificate program mismatch: {certificate_path}")
    verdicts = certificate.get("verdicts")
    if not isinstance(verdicts, Mapping):
        raise _SourceError(f"certificate verdicts are missing: {certificate_path}")

    captured_oracle: dict[str, dict[str, Any]] = {}
    conformant = verdicts.get("conformant")
    if isinstance(conformant, Mapping):
        for group in conformant.get("reference_legs", []):
            if not isinstance(group, Mapping):
                continue
            for leg in group.get("required_axiom_legs", []):
                if (
                    isinstance(leg, Mapping)
                    and isinstance(leg.get("id"), str)
                    and leg.get("state") == "complete"
                ):
                    captured_oracle[leg["id"]] = {
                        key: leg[key]
                        for key in ("id", "artifact", "artifact_sha256", "state")
                        if key in leg
                    }

    executable = verdicts.get("executable")
    captured_executable: list[dict[str, Any]] = []
    if isinstance(executable, Mapping) and executable.get("value") is True:
        manifest = executable.get("manifest")
        if isinstance(manifest, Mapping):
            captured_executable.append(
                {
                    "id": "released-engine-reproduction-contract",
                    **{
                        key: manifest[key]
                        for key in ("path", "sha256")
                        if key in manifest
                    },
                    "state": "complete",
                }
            )

    captured_module_ids = sorted(
        row["module_id"]
        for row in modules
        if row.get("state") == "captured" and isinstance(row.get("module_id"), str)
    )
    return {
        "work_inventory": {
            "certificate_path": certificate_path.relative_to(REPO_ROOT).as_posix(),
            "certificate_sha256": _sha256(raw),
            "oracle_target": 2,
            "captured_oracle_legs": [captured_oracle[key] for key in sorted(captured_oracle)],
            "executable_target": 1,
            "captured_executable_contracts": captured_executable,
            "target_method": "two independent oracle comparison legs and one released-engine reproduction contract, matching the existing DE Kindergeld premise shape",
        },
        "depth_estimate": {
            "value": _CAPTURED_MAX_DEPTH[program_id],
            "mode": "manual_lower_bound_from_captured_declared-module layers",
            "root_nodes": copy.deepcopy(program["root_nodes"]),
            "captured_module_ids": captured_module_ids,
            "frontier_input_ids": [row["id"] for row in leaves],
            "uncertainty": "whole declared modules are enumerated conservatively to mirror the DK producer; root-reachable cross-module bindings and transitive imports remain a stabilization-sprint question",
        },
    }


def validate_snapshot(snapshot: Any) -> None:
    errors: list[str] = []
    if not isinstance(snapshot, Mapping):
        raise ClosureLedgerError(("instrument snapshot must be a mapping",))
    if snapshot.get("schema") != SNAPSHOT_SCHEMA:
        errors.append("instrument snapshot schema mismatch")
    snapshot_receipt = snapshot.get("receipt_sha256")
    if (
        not isinstance(snapshot_receipt, str)
        or not _HEX_SHA256.fullmatch(snapshot_receipt)
        or _canonical_sha(
            {key: value for key, value in snapshot.items() if key != "receipt_sha256"}
        )
        != snapshot_receipt
    ):
        errors.append("instrument snapshot receipt does not bind its content")
    channels = snapshot.get("channels")
    if not isinstance(channels, Mapping) or set(channels) != {
        "corpus_release",
        "subject_matter_search",
        "citation_scan",
    }:
        errors.append("instrument snapshot must contain exactly the three DE channels")
    else:
        for name, channel in channels.items():
            if not isinstance(channel, Mapping):
                errors.append(f"channel {name} must be a mapping")
                continue
            receipt = channel.get("receipt_sha256")
            if not isinstance(receipt, str) or not _HEX_SHA256.fullmatch(receipt):
                errors.append(f"channel {name} receipt_sha256 is invalid")
                continue
            unsigned = {key: value for key, value in channel.items() if key != "receipt_sha256"}
            if _canonical_sha(unsigned) != receipt:
                errors.append(f"channel {name} receipt does not bind its content")
        citation = channels.get("citation_scan")
        if isinstance(citation, Mapping) and (
            citation.get("state") != "not_yet_available"
            or citation.get("issue") != "axiom-corpus#611"
        ):
            errors.append("citation-scan channel must be the #611 not-yet-available placeholder")
    programs = snapshot.get("programs")
    if not isinstance(programs, list):
        errors.append("instrument snapshot programs must be a list")
    else:
        ids = [row.get("id") for row in programs if isinstance(row, Mapping)]
        if ids != sorted(PROGRAM_IDS):
            errors.append("instrument snapshot programs are missing or noncanonical")
        known_refs: set[str] = set()
        if isinstance(channels, Mapping):
            for channel in channels.values():
                if isinstance(channel, Mapping):
                    for key in ("evidence", "attempts", "rows"):
                        values = channel.get(key, [])
                        if isinstance(values, list):
                            for value in values:
                                if isinstance(value, Mapping) and isinstance(value.get("id"), str):
                                    known_refs.add(value["id"])
        for program in programs:
            if not isinstance(program, Mapping) or not isinstance(program.get("instruments"), list):
                errors.append("snapshot program/instruments is malformed")
                continue
            instruments = program["instruments"]
            instrument_ids = [row.get("id") for row in instruments if isinstance(row, Mapping)]
            if instrument_ids != sorted(instrument_ids) or len(instrument_ids) != len(set(instrument_ids)):
                errors.append(f"snapshot instruments for {program.get('id')} are noncanonical")
            for instrument in instruments:
                if not isinstance(instrument, Mapping):
                    errors.append("snapshot instrument must be a mapping")
                    continue
                if instrument.get("status") != "pending":
                    errors.append("every snapshot instrument must be pending")
                refs = instrument.get("discovery_refs")
                if not isinstance(refs, list) or refs != sorted(set(refs)) or not refs:
                    errors.append(f"snapshot instrument {instrument.get('id')} has invalid discovery refs")
                elif known_refs and any(ref not in known_refs for ref in refs):
                    errors.append(f"snapshot instrument {instrument.get('id')} has an unknown discovery ref")
            if program.get("id") == "de/kindergeld":
                bindings = program.get("seed_bindings")
                if (
                    not isinstance(bindings, list)
                    or any(not isinstance(row, Mapping) for row in bindings)
                    or [row.get("id") for row in bindings]
                    != [f"de-kg-instr-{number:03d}" for number in range(1, 6)]
                    or any(row.get("status") != "pending" for row in bindings)
                ):
                    errors.append("snapshot lacks Kindergeld seed bindings 001 through 005")
    if errors:
        raise ClosureLedgerError(errors)


def _computed(
    spine: Sequence[Mapping[str, Any]],
    leaves: Sequence[Mapping[str, Any]],
    graph: Mapping[str, Any],
    measurement_basis: Mapping[str, Any],
) -> dict[str, Any]:
    ledger = [
        {**copy.deepcopy(row), "status": "pending"}
        for row in spine
    ]
    pending_citations = [row["citation_path"] for row in ledger]
    candidates = copy.deepcopy(graph["candidates"])
    pending_instruments = [row["id"] for row in candidates]
    law_derived = [row["input"] for row in leaves if row["leaf_kind"] == "law_derived"]
    unclassified = [row["input"] for row in leaves if row["leaf_kind"] == "unclassified"]
    work = measurement_basis["work_inventory"]
    depth = measurement_basis["depth_estimate"]
    oracle_work = work["oracle_target"] - len(work["captured_oracle_legs"])
    executable_work = work["executable_target"] - len(
        work["captured_executable_contracts"]
    )
    return {
        "ledger": ledger,
        "provision_counts": {
            "total": len(ledger),
            "encoded": 0,
            "partially-encoded": 0,
            "classified-with-reason": 0,
            "excluded-with-reason": 0,
            "pending": len(ledger),
        },
        "partially_encoded": [],
        "pending": pending_citations,
        "boundary_frontier": {
            "input_count": len(leaves),
            "pending_count": len(leaves),
            "law_derived_count": len(law_derived),
            "unclassified_count": len(unclassified),
            "pending": [row["input"] for row in leaves],
            "complete": False,
            "inputs": copy.deepcopy(list(leaves)),
        },
        "instrument_frontier": {
            "instrument_count": len(candidates),
            "counts": {
                "total": len(candidates),
                "encoded": 0,
                "classified-with-reason": 0,
                "excluded-with-reason": 0,
                "pending": len(candidates),
            },
            "pending": pending_instruments,
            "complete": False,
            "ledger": candidates,
        },
        "dependency_closure": {
            "law_derived_inputs": law_derived,
            "law_derived_input_count": len(law_derived),
            "unclassified_inputs": unclassified,
            "unclassified_input_count": len(unclassified),
            "instruments_bearing_on_computed": [],
            "instruments_bearing_on_computed_count": 0,
            "open_dependency_count": len(law_derived) + len(unclassified),
            "closed": False,
        },
        "measured_denominators": {
            "spine_rows": len(spine),
            "bearing_candidate_instruments": len(candidates),
            "law_derived_leaf_nodes": len(law_derived),
            "max_depth_estimate": depth["value"],
            "remaining_oracle_work": oracle_work,
            "remaining_executable_work": executable_work,
        },
        "measurement_method": {
            "spine_rows": "count of rows selected by the preregistered exact-citation/range scope from the pinned corpus release",
            "bearing_candidate_instruments": "unique all-pending candidates discovered by any captured channel; potential bearing, not a legal disposition",
            "law_derived_leaf_nodes": "unique typed frontier inputs that closure/de/source.json already commits as law_derived",
            "max_depth_estimate": "maximum currently captured chain from a declared output root through its RuleSpec dependency modules to a typed frontier input; lower bound until pending instruments and leaves are dispositioned",
            "remaining_oracle_work": "oracle_target minus complete oracle rows in the sha-bound current certificate work inventory",
            "remaining_executable_work": "executable_target minus complete reproduction-contract rows in the sha-bound current certificate work inventory",
            "uncertainty": "instrument count and depth are lower bounds because every network query was unretrieved and corpus citation scan #611 is unavailable; work counts can increase when the claim surface is stabilized or pending candidates are reviewed",
        },
        "non_encoded_reasons_complete": True,
        "closed": False,
    }


def generate_document(
    program_id: str,
    *,
    source_path: Path = SOURCE_PATH,
    snapshot_path: Path = SNAPSHOT_PATH,
    corpus_root: Path = CORPUS_ROOT,
    rulespec_root: Path = RULESPEC_ROOT,
) -> dict[str, Any]:
    if program_id not in PROGRAM_IDS:
        raise _SourceError(f"unknown DE closure program: {program_id}")
    source, source_raw = _source_manifest(source_path)
    index, corpus_receipts = _corpus_rows(source, corpus_root)
    spine = _spine(program_id, index)
    modules, module_inputs = _rulespec_facts(source, program_id, rulespec_root)
    leaves = _leaf_frontier(source, program_id, module_inputs)
    graph = _snapshot_facts(program_id, snapshot_path, source_path)
    program = source["programs"][program_id]
    measurement_basis = _measurement_basis(program_id, program, modules, leaves)
    corpus = source["corpus"]
    generated = {
        "source_manifest": {
            "path": source_path.relative_to(REPO_ROOT).as_posix(),
            "sha256": _sha256(source_raw),
        },
        "corpus_release": {
            "repository": corpus["repository"],
            "commit": corpus["commit"],
            "release": corpus["release"],
            "release_content_sha256": corpus["release_content_sha256"],
            "resolution": copy.deepcopy(source["resolution"]),
            "provision_sources": corpus_receipts,
        },
        "provision_spine": spine,
        "rulespec_modules": modules,
        "module_inputs": module_inputs,
        "leaf_frontier": leaves,
        "dependency_enumeration": {
            "method": "all formula inputs in every exact declared-source RuleSpec module, plus source.json program boundary rows",
            "scope": "whole declared modules, mirroring the DK v3 producer; not a claim of root-reachable import closure",
            "imports": "captured per module; selected DE modules currently declare none",
        },
        "instrument_graph": graph,
        "measurement_basis": measurement_basis,
    }
    computed = _computed(spine, leaves, graph, measurement_basis)
    return {
        "schema": SCHEMA,
        "program": {
            "id": program_id,
            "jurisdiction": "de",
            "period": source["period"],
            "claim_mode": program["claim_mode"],
            "root_nodes": copy.deepcopy(program["root_nodes"]),
            "declared_sources": copy.deepcopy(program["declared_sources"]),
            "spine_scope": copy.deepcopy(_SPINE_SCOPES[program_id]),
        },
        "generated_facts": generated,
        "committed_decisions": {
            "provisions": [],
            "instrument_dispositions": [],
            "leaf_classifications": [],
        },
        "computed": computed,
    }


def _is_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def validate_artifact(document: Any) -> ClosureSummary:
    errors: list[str] = []
    if not isinstance(document, Mapping):
        raise ClosureLedgerError(("ledger must be a mapping",))
    if document.get("schema") != SCHEMA:
        errors.append("schema must be axiom_oracles.closure.ledger.v3")
    if set(document) != {"schema", "program", "generated_facts", "committed_decisions", "computed"}:
        errors.append("ledger top-level keys are not canonical")
    program = document.get("program")
    generated = document.get("generated_facts")
    decisions = document.get("committed_decisions")
    computed = document.get("computed")
    if not isinstance(program, Mapping) or program.get("id") not in PROGRAM_IDS:
        errors.append("program block/id is invalid")
    if not isinstance(generated, Mapping):
        errors.append("generated_facts must be a mapping")
    if not isinstance(decisions, Mapping):
        errors.append("committed_decisions must be a mapping")
    elif set(decisions) != {"provisions", "instrument_dispositions", "leaf_classifications"} or any(
        decisions.get(key) != [] for key in decisions
    ):
        errors.append("committed_decisions must contain exactly three empty lists")
    if not isinstance(computed, Mapping):
        errors.append("computed must be a mapping")
    if errors:
        raise ClosureLedgerError(errors)

    assert isinstance(generated, Mapping) and isinstance(computed, Mapping)
    spine = generated.get("provision_spine")
    leaves = generated.get("leaf_frontier")
    graph = generated.get("instrument_graph")
    measurement_basis = generated.get("measurement_basis")
    if (
        not isinstance(spine, list)
        or not isinstance(leaves, list)
        or not isinstance(graph, Mapping)
        or not isinstance(measurement_basis, Mapping)
    ):
        raise ClosureLedgerError(("generated spine, leaf frontier, or instrument graph is malformed",))
    candidates = graph.get("candidates")
    if not isinstance(candidates, list):
        raise ClosureLedgerError(("generated instrument candidates must be a list",))

    expected_generated_keys = {
        "source_manifest",
        "corpus_release",
        "provision_spine",
        "rulespec_modules",
        "module_inputs",
        "leaf_frontier",
        "dependency_enumeration",
        "instrument_graph",
        "measurement_basis",
    }
    if set(generated) != expected_generated_keys:
        errors.append("generated_facts keys are not canonical")
    source_binding = generated.get("source_manifest")
    if (
        not isinstance(source_binding, Mapping)
        or set(source_binding) != {"path", "sha256"}
        or not isinstance(source_binding.get("path"), str)
        or not isinstance(source_binding.get("sha256"), str)
        or not _HEX_SHA256.fullmatch(source_binding["sha256"])
    ):
        errors.append("source_manifest binding is malformed")
    if (
        not isinstance(graph.get("snapshot_sha256"), str)
        or not _HEX_SHA256.fullmatch(graph["snapshot_sha256"])
        or not _is_int(graph.get("candidate_count"))
        or graph.get("candidate_count") != len(candidates)
    ):
        errors.append("instrument graph hash/count binding is malformed")
    channel_receipts = graph.get("channel_receipts")
    if (
        not isinstance(channel_receipts, Mapping)
        or set(channel_receipts)
        != {"corpus_release", "subject_matter_search", "citation_scan"}
        or any(
            not isinstance(value, str) or not _HEX_SHA256.fullmatch(value)
            for value in channel_receipts.values()
        )
    ):
        errors.append("instrument channel receipt bindings are malformed")

    spine_citations = [
        row.get("citation_path") for row in spine if isinstance(row, Mapping)
    ]
    if (
        len(spine_citations) != len(spine)
        or len(spine_citations) != len(set(spine_citations))
        or [row.get("ordinal") for row in spine if isinstance(row, Mapping)]
        != list(range(1, len(spine) + 1))
        or any(
            not isinstance(row.get("body_sha256"), str)
            or not _HEX_SHA256.fullmatch(row["body_sha256"])
            or not isinstance(row.get("row_sha256"), str)
            or not _HEX_SHA256.fullmatch(row["row_sha256"])
            for row in spine
            if isinstance(row, Mapping)
        )
    ):
        errors.append("provision spine identities, ordering, or hashes are malformed")

    leaf_ids = [row.get("id") for row in leaves if isinstance(row, Mapping)]
    leaf_inputs = [row.get("input") for row in leaves if isinstance(row, Mapping)]
    if (
        len(leaf_ids) != len(leaves)
        or any(not isinstance(value, str) for value in leaf_ids + leaf_inputs)
        or len(leaf_ids) != len(set(leaf_ids))
        or len(leaf_inputs) != len(set(leaf_inputs))
        or leaf_inputs != sorted(leaf_inputs)
        or any(
            not isinstance(row.get("slots"), list)
            or row["slots"] != sorted(set(row["slots"]))
            or not isinstance(row.get("read_by"), list)
            or row["read_by"] != sorted(set(row["read_by"]))
            for row in leaves
            if isinstance(row, Mapping)
        )
    ):
        errors.append("leaf frontier ids, inputs, slots, or ordering are malformed")

    candidate_ids = [row.get("id") for row in candidates if isinstance(row, Mapping)]
    if (
        len(candidate_ids) != len(candidates)
        or any(not isinstance(value, str) for value in candidate_ids)
        or len(candidate_ids) != len(set(candidate_ids))
        or candidate_ids != sorted(candidate_ids)
    ):
        errors.append("instrument candidate ids are missing, duplicated, or noncanonical")

    work_basis = measurement_basis.get("work_inventory")
    depth_basis = measurement_basis.get("depth_estimate")
    if (
        not isinstance(work_basis, Mapping)
        or not isinstance(depth_basis, Mapping)
        or not _is_int(work_basis.get("oracle_target"))
        or not isinstance(work_basis.get("captured_oracle_legs"), list)
        or not _is_int(work_basis.get("executable_target"))
        or not isinstance(work_basis.get("captured_executable_contracts"), list)
        or not _is_int(depth_basis.get("value"))
        or len(work_basis["captured_oracle_legs"]) > work_basis["oracle_target"]
        or len(work_basis["captured_executable_contracts"])
        > work_basis["executable_target"]
    ):
        errors.append("measurement basis is malformed")
    if errors:
        raise ClosureLedgerError(errors)

    try:
        expected = _computed(spine, leaves, graph, measurement_basis)
    except (KeyError, TypeError) as exc:
        raise ClosureLedgerError((f"generated all-pending facts are malformed: {exc}",)) from exc
    # Exact equality is deliberate: it rejects coordinated count/list/complete
    # forgeries, bare ``closed: true``, and bool-as-int substitutions.
    if computed != expected:
        errors.append("computed block does not equal the pure all-pending derivation")

    for section, fields in (
        (computed.get("provision_counts"), ("total", "encoded", "partially-encoded", "classified-with-reason", "excluded-with-reason", "pending")),
        (computed.get("boundary_frontier"), ("input_count", "pending_count", "law_derived_count", "unclassified_count")),
        (
            computed.get("dependency_closure"),
            (
                "open_dependency_count",
                "law_derived_input_count",
                "unclassified_input_count",
                "instruments_bearing_on_computed_count",
            ),
        ),
    ):
        if not isinstance(section, Mapping):
            errors.append("computed count section is malformed")
            continue
        for field in fields:
            if not _is_int(section.get(field)):
                errors.append(f"{field} must be an integer, not bool")
    instrument_frontier = computed.get("instrument_frontier")
    if isinstance(instrument_frontier, Mapping):
        if not _is_int(instrument_frontier.get("instrument_count")):
            errors.append("instrument_count must be an integer, not bool")
        counts = instrument_frontier.get("counts")
        if not isinstance(counts, Mapping) or any(
            not _is_int(counts.get(field))
            for field in ("total", "encoded", "classified-with-reason", "excluded-with-reason", "pending")
        ):
            errors.append("instrument counts must be integers, not bool")
    else:
        errors.append("instrument_frontier is malformed")
    measured = computed.get("measured_denominators")
    measured_fields = (
        "spine_rows",
        "bearing_candidate_instruments",
        "law_derived_leaf_nodes",
        "max_depth_estimate",
        "remaining_oracle_work",
        "remaining_executable_work",
    )
    if not isinstance(measured, Mapping) or set(measured) != set(measured_fields):
        errors.append("measured_denominators is malformed")
    elif any(not _is_int(measured.get(field)) for field in measured_fields):
        errors.append("measured denominator counts must be integers, not bool")

    if computed.get("closed") is not False:
        errors.append("all-pending ledger closed must be exact false")
    dependency = computed.get("dependency_closure")
    if not isinstance(dependency, Mapping) or dependency.get("closed") is not False:
        errors.append("dependency closure closed must be exact false")
    boundary = computed.get("boundary_frontier")
    if not isinstance(boundary, Mapping) or boundary.get("complete") is not False:
        errors.append("boundary frontier complete must be exact false")
    if not isinstance(instrument_frontier, Mapping) or instrument_frontier.get("complete") is not False:
        errors.append("instrument frontier complete must be exact false")
    if any(
        not isinstance(row, Mapping)
        or row.get("status") != "pending"
        or row.get("leaf_kind") not in {"law_derived", "unclassified"}
        for row in leaves
    ):
        errors.append("every generated leaf must be pending and explicitly typed")
    if any(not isinstance(row, Mapping) or row.get("status") != "pending" for row in candidates):
        errors.append("every generated instrument must be pending")
    if errors:
        raise ClosureLedgerError(errors)
    return ClosureSummary(
        closed=False,
        spine_rows=len(spine),
        pending_provisions=len(spine),
        pending_instruments=len(candidates),
        pending_inputs=len(leaves),
        open_dependencies=len(leaves),
    )


def verify_artifact(
    artifact_path: Path,
    *,
    source_path: Path = SOURCE_PATH,
    snapshot_path: Path = SNAPSHOT_PATH,
    corpus_root: Path = CORPUS_ROOT,
    rulespec_root: Path = RULESPEC_ROOT,
) -> VerificationResult:
    document: dict[str, Any] | None = None
    expected: dict[str, Any] | None = None
    errors: list[str] = []
    try:
        document = load_document(artifact_path)
        validate_artifact(document)
        program_id = document["program"]["id"]
        if ARTIFACT_PATHS.get(program_id) != artifact_path:
            errors.append(f"artifact path does not match program id {program_id}")
        expected = generate_document(
            program_id,
            source_path=source_path,
            snapshot_path=snapshot_path,
            corpus_root=corpus_root,
            rulespec_root=rulespec_root,
        )
        if document != expected:
            errors.append("committed artifact differs from hermetic rederivation")
    except (ClosureLedgerError, _SourceError, OSError, yaml.YAMLError) as exc:
        if isinstance(exc, ClosureLedgerError):
            errors.extend(exc.errors)
        else:
            errors.append(str(exc))
    return VerificationResult(document, expected, tuple(errors))


def serialize(document: Mapping[str, Any]) -> str:
    return _HEADER + yaml.safe_dump(
        document,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=1000,
    )


def _selected_programs(value: str | None) -> list[str]:
    if value is None or value == "all":
        return list(PROGRAM_IDS)
    if value in PROGRAM_IDS:
        return [value]
    for program_id, path in ARTIFACT_PATHS.items():
        if value == str(path) or value == path.name:
            return [program_id]
    raise _SourceError(f"unknown artifact/program selector: {value}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--generate", action="store_true", help="rewrite the selected committed ledger(s)")
    mode.add_argument("--check", action="store_true", help="hermetically rederive and compare")
    parser.add_argument("--artifact", help="program id, artifact filename/path, or 'all' (default)")
    parser.add_argument("--source", type=Path, default=SOURCE_PATH)
    parser.add_argument("--snapshot", type=Path, default=SNAPSHOT_PATH)
    parser.add_argument("--corpus-root", type=Path, default=CORPUS_ROOT)
    parser.add_argument("--rulespec-root", type=Path, default=RULESPEC_ROOT)
    args = parser.parse_args(argv)
    try:
        programs = _selected_programs(args.artifact)
        if args.generate:
            for program_id in programs:
                document = generate_document(
                    program_id,
                    source_path=args.source,
                    snapshot_path=args.snapshot,
                    corpus_root=args.corpus_root,
                    rulespec_root=args.rulespec_root,
                )
                validate_artifact(document)
                path = ARTIFACT_PATHS[program_id]
                path.write_text(serialize(document))
                print(f"wrote {path.relative_to(REPO_ROOT)}")
            return 0
        failed = False
        for program_id in programs:
            path = ARTIFACT_PATHS[program_id]
            result = verify_artifact(
                path,
                source_path=args.source,
                snapshot_path=args.snapshot,
                corpus_root=args.corpus_root,
                rulespec_root=args.rulespec_root,
            )
            if result.valid:
                print(f"ok: {path.relative_to(REPO_ROOT)} (closed=false)")
            else:
                failed = True
                for error in result.errors:
                    print(f"error: {path.relative_to(REPO_ROOT)}: {error}", file=sys.stderr)
        return 1 if failed else 0
    except (_SourceError, ClosureLedgerError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
